import { SubmitCurrentTeamProfileData, SubmitCurrentTeamProfileVariables, ConvertTeamProfileSubmissionData, ConvertTeamProfileSubmissionVariables, CreateSossonTeamData, CreateSossonTeamVariables, UpdateSossonTeamData, UpdateSossonTeamVariables, CreateSossonTeamMemberData, CreateSossonTeamMemberVariables, UpdateSossonTeamMemberData, UpdateSossonTeamMemberVariables, CreateSossonTeamLeavePeriodData, CreateSossonTeamLeavePeriodVariables, CreateSossonWorkTimeEntryData, CreateSossonWorkTimeEntryVariables, CreateSossonPayrollPeriodData, CreateSossonPayrollPeriodVariables, CreatePlanningJobSheetData, CreatePlanningJobSheetVariables, UpdatePlanningJobSheetProgressData, UpdatePlanningJobSheetProgressVariables, CompletePlanningJobSheetData, CompletePlanningJobSheetVariables, CreateClientData, CreateClientVariables, UpdateClientData, UpdateClientVariables, CreateChantierData, CreateChantierVariables, UpdateChantierStatutData, UpdateChantierStatutVariables, CreateDevisData, CreateDevisVariables, UpdateDevisStatutData, UpdateDevisStatutVariables, CreateFactureData, CreateFactureVariables, SetFactureStatutData, SetFactureStatutVariables, CreateDocumentFolderData, CreateDocumentFolderVariables, CreateDocumentAttacheData, CreateDocumentAttacheVariables, UpdateDocumentAttacheLinksData, UpdateDocumentAttacheLinksVariables, CreatePrevisionnelImportBatchData, CreatePrevisionnelImportBatchVariables, UpdatePrevisionnelMonthlyAmountData, UpdatePrevisionnelMonthlyAmountVariables, UpdatePrevisionnelLineAmountsData, UpdatePrevisionnelLineAmountsVariables, LinkPrevisionnelLineToChantierData, LinkPrevisionnelLineToChantierVariables, UpsertPrevisionnelCellEditData, UpsertPrevisionnelCellEditVariables, CreateEmailThreadData, CreateEmailThreadVariables, UpdateEmailThreadStatusAndLinksData, UpdateEmailThreadStatusAndLinksVariables, CreateEmailMessageData, CreateEmailMessageVariables, CreateEmailAttachmentData, CreateEmailAttachmentVariables, CreatePlanningEventData, CreatePlanningEventVariables, UpdatePlanningEventStatusData, UpdatePlanningEventStatusVariables, UpdatePlanningEventDetailsData, UpdatePlanningEventDetailsVariables, CancelPlanningEventData, CancelPlanningEventVariables, CreatePlanningAssignmentData, CreatePlanningAssignmentVariables, UpdatePlanningAssignmentStatusData, UpdatePlanningAssignmentStatusVariables, CreateAnalyticsSnapshotData, CreateAnalyticsSnapshotVariables, CreateRapportData, CreateRapportVariables, MarkRapportGeneratedData, MarkRapportGeneratedVariables, CreateAuditEventData, CreateAuditEventVariables, CreateCheckpointRunData, CreateCheckpointRunVariables, CreateCheckpointStepData, CreateCheckpointStepVariables, CreateCheckpointArtifactData, CreateCheckpointArtifactVariables, CreateCheckpointDecisionData, CreateCheckpointDecisionVariables, CreateDataImportRunData, CreateDataImportRunVariables, CreateDataImportIssueData, CreateDataImportIssueVariables, CreateEntityChangeLogData, CreateEntityChangeLogVariables, GetCurrentUserData, ListUsersData, GetCurrentTeamProfileSubmissionData, ListTeamProfileSubmissionsData, ListSossonTeamsData, ListSossonWorkTimeEntriesData, ListSossonWorkTimeEntriesVariables, ListSossonPayrollPeriodsData, ListSossonPayrollPeriodsVariables, ListOperationalClientsData, GetClientData, GetClientVariables, ListOperationalChantiersData, GetChantierData, GetChantierVariables, ListDevisData, ListDevisByClientData, ListDevisByClientVariables, ListDevisByChantierData, ListDevisByChantierVariables, ListFacturesData, ListFacturesByStatutData, ListFacturesByStatutVariables, ListDocumentFoldersData, ListDocumentsAttachesData, ListDocumentsByChantierData, ListDocumentsByChantierVariables, ListPrevisionnelExercisesData, ListPrevisionnelLinesByExerciseData, ListPrevisionnelLinesByExerciseVariables, SearchClientAliasesData, SearchClientAliasesVariables, ListPrevisionnelCellEditsData, ListPrevisionnelCellEditsVariables, ListEmailThreadsData, ListEmailThreadsByChantierData, ListEmailThreadsByChantierVariables, ListUnreadEmailThreadsData, GetEmailThreadData, GetEmailThreadVariables, ListPlanningEventsByPeriodData, ListPlanningEventsByPeriodVariables, ListPlanningEventsByChantierData, ListPlanningEventsByChantierVariables, ListPlanningJobSheetsByEventData, ListPlanningJobSheetsByEventVariables, ListAnalyticsSnapshotsData, ListAnalyticsSnapshotsVariables, GetAnalyticsSnapshotData, GetAnalyticsSnapshotVariables, ListRapportsData, GetRapportData, GetRapportVariables, ListRecentAuditEventsData, ListRecentAuditEventsVariables, ListEntityChangeLogsData, ListEntityChangeLogsVariables, ListCheckpointRunsData, ListCheckpointRunsVariables, GetCheckpointRunData, GetCheckpointRunVariables, ListDataImportRunsData, ListDataImportRunsVariables, GetDataImportRunData, GetDataImportRunVariables } from '../';
import { UseDataConnectQueryResult, useDataConnectQueryOptions, UseDataConnectMutationResult, useDataConnectMutationOptions} from '@tanstack-query-firebase/react/data-connect';
import { UseQueryResult, UseMutationResult} from '@tanstack/react-query';
import { DataConnect } from 'firebase/data-connect';
import { FirebaseError } from 'firebase/app';


export function useSubmitCurrentTeamProfile(options?: useDataConnectMutationOptions<SubmitCurrentTeamProfileData, FirebaseError, SubmitCurrentTeamProfileVariables>): UseDataConnectMutationResult<SubmitCurrentTeamProfileData, SubmitCurrentTeamProfileVariables>;
export function useSubmitCurrentTeamProfile(dc: DataConnect, options?: useDataConnectMutationOptions<SubmitCurrentTeamProfileData, FirebaseError, SubmitCurrentTeamProfileVariables>): UseDataConnectMutationResult<SubmitCurrentTeamProfileData, SubmitCurrentTeamProfileVariables>;

export function useConvertTeamProfileSubmission(options?: useDataConnectMutationOptions<ConvertTeamProfileSubmissionData, FirebaseError, ConvertTeamProfileSubmissionVariables>): UseDataConnectMutationResult<ConvertTeamProfileSubmissionData, ConvertTeamProfileSubmissionVariables>;
export function useConvertTeamProfileSubmission(dc: DataConnect, options?: useDataConnectMutationOptions<ConvertTeamProfileSubmissionData, FirebaseError, ConvertTeamProfileSubmissionVariables>): UseDataConnectMutationResult<ConvertTeamProfileSubmissionData, ConvertTeamProfileSubmissionVariables>;

export function useCreateSossonTeam(options?: useDataConnectMutationOptions<CreateSossonTeamData, FirebaseError, CreateSossonTeamVariables>): UseDataConnectMutationResult<CreateSossonTeamData, CreateSossonTeamVariables>;
export function useCreateSossonTeam(dc: DataConnect, options?: useDataConnectMutationOptions<CreateSossonTeamData, FirebaseError, CreateSossonTeamVariables>): UseDataConnectMutationResult<CreateSossonTeamData, CreateSossonTeamVariables>;

export function useUpdateSossonTeam(options?: useDataConnectMutationOptions<UpdateSossonTeamData, FirebaseError, UpdateSossonTeamVariables>): UseDataConnectMutationResult<UpdateSossonTeamData, UpdateSossonTeamVariables>;
export function useUpdateSossonTeam(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateSossonTeamData, FirebaseError, UpdateSossonTeamVariables>): UseDataConnectMutationResult<UpdateSossonTeamData, UpdateSossonTeamVariables>;

export function useCreateSossonTeamMember(options?: useDataConnectMutationOptions<CreateSossonTeamMemberData, FirebaseError, CreateSossonTeamMemberVariables>): UseDataConnectMutationResult<CreateSossonTeamMemberData, CreateSossonTeamMemberVariables>;
export function useCreateSossonTeamMember(dc: DataConnect, options?: useDataConnectMutationOptions<CreateSossonTeamMemberData, FirebaseError, CreateSossonTeamMemberVariables>): UseDataConnectMutationResult<CreateSossonTeamMemberData, CreateSossonTeamMemberVariables>;

export function useUpdateSossonTeamMember(options?: useDataConnectMutationOptions<UpdateSossonTeamMemberData, FirebaseError, UpdateSossonTeamMemberVariables>): UseDataConnectMutationResult<UpdateSossonTeamMemberData, UpdateSossonTeamMemberVariables>;
export function useUpdateSossonTeamMember(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateSossonTeamMemberData, FirebaseError, UpdateSossonTeamMemberVariables>): UseDataConnectMutationResult<UpdateSossonTeamMemberData, UpdateSossonTeamMemberVariables>;

export function useCreateSossonTeamLeavePeriod(options?: useDataConnectMutationOptions<CreateSossonTeamLeavePeriodData, FirebaseError, CreateSossonTeamLeavePeriodVariables>): UseDataConnectMutationResult<CreateSossonTeamLeavePeriodData, CreateSossonTeamLeavePeriodVariables>;
export function useCreateSossonTeamLeavePeriod(dc: DataConnect, options?: useDataConnectMutationOptions<CreateSossonTeamLeavePeriodData, FirebaseError, CreateSossonTeamLeavePeriodVariables>): UseDataConnectMutationResult<CreateSossonTeamLeavePeriodData, CreateSossonTeamLeavePeriodVariables>;

export function useCreateSossonWorkTimeEntry(options?: useDataConnectMutationOptions<CreateSossonWorkTimeEntryData, FirebaseError, CreateSossonWorkTimeEntryVariables>): UseDataConnectMutationResult<CreateSossonWorkTimeEntryData, CreateSossonWorkTimeEntryVariables>;
export function useCreateSossonWorkTimeEntry(dc: DataConnect, options?: useDataConnectMutationOptions<CreateSossonWorkTimeEntryData, FirebaseError, CreateSossonWorkTimeEntryVariables>): UseDataConnectMutationResult<CreateSossonWorkTimeEntryData, CreateSossonWorkTimeEntryVariables>;

export function useCreateSossonPayrollPeriod(options?: useDataConnectMutationOptions<CreateSossonPayrollPeriodData, FirebaseError, CreateSossonPayrollPeriodVariables>): UseDataConnectMutationResult<CreateSossonPayrollPeriodData, CreateSossonPayrollPeriodVariables>;
export function useCreateSossonPayrollPeriod(dc: DataConnect, options?: useDataConnectMutationOptions<CreateSossonPayrollPeriodData, FirebaseError, CreateSossonPayrollPeriodVariables>): UseDataConnectMutationResult<CreateSossonPayrollPeriodData, CreateSossonPayrollPeriodVariables>;

export function useCreatePlanningJobSheet(options?: useDataConnectMutationOptions<CreatePlanningJobSheetData, FirebaseError, CreatePlanningJobSheetVariables>): UseDataConnectMutationResult<CreatePlanningJobSheetData, CreatePlanningJobSheetVariables>;
export function useCreatePlanningJobSheet(dc: DataConnect, options?: useDataConnectMutationOptions<CreatePlanningJobSheetData, FirebaseError, CreatePlanningJobSheetVariables>): UseDataConnectMutationResult<CreatePlanningJobSheetData, CreatePlanningJobSheetVariables>;

export function useUpdatePlanningJobSheetProgress(options?: useDataConnectMutationOptions<UpdatePlanningJobSheetProgressData, FirebaseError, UpdatePlanningJobSheetProgressVariables>): UseDataConnectMutationResult<UpdatePlanningJobSheetProgressData, UpdatePlanningJobSheetProgressVariables>;
export function useUpdatePlanningJobSheetProgress(dc: DataConnect, options?: useDataConnectMutationOptions<UpdatePlanningJobSheetProgressData, FirebaseError, UpdatePlanningJobSheetProgressVariables>): UseDataConnectMutationResult<UpdatePlanningJobSheetProgressData, UpdatePlanningJobSheetProgressVariables>;

export function useCompletePlanningJobSheet(options?: useDataConnectMutationOptions<CompletePlanningJobSheetData, FirebaseError, CompletePlanningJobSheetVariables>): UseDataConnectMutationResult<CompletePlanningJobSheetData, CompletePlanningJobSheetVariables>;
export function useCompletePlanningJobSheet(dc: DataConnect, options?: useDataConnectMutationOptions<CompletePlanningJobSheetData, FirebaseError, CompletePlanningJobSheetVariables>): UseDataConnectMutationResult<CompletePlanningJobSheetData, CompletePlanningJobSheetVariables>;

export function useCreateClient(options?: useDataConnectMutationOptions<CreateClientData, FirebaseError, CreateClientVariables>): UseDataConnectMutationResult<CreateClientData, CreateClientVariables>;
export function useCreateClient(dc: DataConnect, options?: useDataConnectMutationOptions<CreateClientData, FirebaseError, CreateClientVariables>): UseDataConnectMutationResult<CreateClientData, CreateClientVariables>;

export function useUpdateClient(options?: useDataConnectMutationOptions<UpdateClientData, FirebaseError, UpdateClientVariables>): UseDataConnectMutationResult<UpdateClientData, UpdateClientVariables>;
export function useUpdateClient(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateClientData, FirebaseError, UpdateClientVariables>): UseDataConnectMutationResult<UpdateClientData, UpdateClientVariables>;

export function useCreateChantier(options?: useDataConnectMutationOptions<CreateChantierData, FirebaseError, CreateChantierVariables>): UseDataConnectMutationResult<CreateChantierData, CreateChantierVariables>;
export function useCreateChantier(dc: DataConnect, options?: useDataConnectMutationOptions<CreateChantierData, FirebaseError, CreateChantierVariables>): UseDataConnectMutationResult<CreateChantierData, CreateChantierVariables>;

export function useUpdateChantierStatut(options?: useDataConnectMutationOptions<UpdateChantierStatutData, FirebaseError, UpdateChantierStatutVariables>): UseDataConnectMutationResult<UpdateChantierStatutData, UpdateChantierStatutVariables>;
export function useUpdateChantierStatut(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateChantierStatutData, FirebaseError, UpdateChantierStatutVariables>): UseDataConnectMutationResult<UpdateChantierStatutData, UpdateChantierStatutVariables>;

export function useCreateDevis(options?: useDataConnectMutationOptions<CreateDevisData, FirebaseError, CreateDevisVariables>): UseDataConnectMutationResult<CreateDevisData, CreateDevisVariables>;
export function useCreateDevis(dc: DataConnect, options?: useDataConnectMutationOptions<CreateDevisData, FirebaseError, CreateDevisVariables>): UseDataConnectMutationResult<CreateDevisData, CreateDevisVariables>;

export function useUpdateDevisStatut(options?: useDataConnectMutationOptions<UpdateDevisStatutData, FirebaseError, UpdateDevisStatutVariables>): UseDataConnectMutationResult<UpdateDevisStatutData, UpdateDevisStatutVariables>;
export function useUpdateDevisStatut(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateDevisStatutData, FirebaseError, UpdateDevisStatutVariables>): UseDataConnectMutationResult<UpdateDevisStatutData, UpdateDevisStatutVariables>;

export function useCreateFacture(options?: useDataConnectMutationOptions<CreateFactureData, FirebaseError, CreateFactureVariables>): UseDataConnectMutationResult<CreateFactureData, CreateFactureVariables>;
export function useCreateFacture(dc: DataConnect, options?: useDataConnectMutationOptions<CreateFactureData, FirebaseError, CreateFactureVariables>): UseDataConnectMutationResult<CreateFactureData, CreateFactureVariables>;

export function useSetFactureStatut(options?: useDataConnectMutationOptions<SetFactureStatutData, FirebaseError, SetFactureStatutVariables>): UseDataConnectMutationResult<SetFactureStatutData, SetFactureStatutVariables>;
export function useSetFactureStatut(dc: DataConnect, options?: useDataConnectMutationOptions<SetFactureStatutData, FirebaseError, SetFactureStatutVariables>): UseDataConnectMutationResult<SetFactureStatutData, SetFactureStatutVariables>;

export function useCreateDocumentFolder(options?: useDataConnectMutationOptions<CreateDocumentFolderData, FirebaseError, CreateDocumentFolderVariables>): UseDataConnectMutationResult<CreateDocumentFolderData, CreateDocumentFolderVariables>;
export function useCreateDocumentFolder(dc: DataConnect, options?: useDataConnectMutationOptions<CreateDocumentFolderData, FirebaseError, CreateDocumentFolderVariables>): UseDataConnectMutationResult<CreateDocumentFolderData, CreateDocumentFolderVariables>;

export function useCreateDocumentAttache(options?: useDataConnectMutationOptions<CreateDocumentAttacheData, FirebaseError, CreateDocumentAttacheVariables>): UseDataConnectMutationResult<CreateDocumentAttacheData, CreateDocumentAttacheVariables>;
export function useCreateDocumentAttache(dc: DataConnect, options?: useDataConnectMutationOptions<CreateDocumentAttacheData, FirebaseError, CreateDocumentAttacheVariables>): UseDataConnectMutationResult<CreateDocumentAttacheData, CreateDocumentAttacheVariables>;

export function useUpdateDocumentAttacheLinks(options?: useDataConnectMutationOptions<UpdateDocumentAttacheLinksData, FirebaseError, UpdateDocumentAttacheLinksVariables>): UseDataConnectMutationResult<UpdateDocumentAttacheLinksData, UpdateDocumentAttacheLinksVariables>;
export function useUpdateDocumentAttacheLinks(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateDocumentAttacheLinksData, FirebaseError, UpdateDocumentAttacheLinksVariables>): UseDataConnectMutationResult<UpdateDocumentAttacheLinksData, UpdateDocumentAttacheLinksVariables>;

export function useCreatePrevisionnelImportBatch(options?: useDataConnectMutationOptions<CreatePrevisionnelImportBatchData, FirebaseError, CreatePrevisionnelImportBatchVariables>): UseDataConnectMutationResult<CreatePrevisionnelImportBatchData, CreatePrevisionnelImportBatchVariables>;
export function useCreatePrevisionnelImportBatch(dc: DataConnect, options?: useDataConnectMutationOptions<CreatePrevisionnelImportBatchData, FirebaseError, CreatePrevisionnelImportBatchVariables>): UseDataConnectMutationResult<CreatePrevisionnelImportBatchData, CreatePrevisionnelImportBatchVariables>;

export function useUpdatePrevisionnelMonthlyAmount(options?: useDataConnectMutationOptions<UpdatePrevisionnelMonthlyAmountData, FirebaseError, UpdatePrevisionnelMonthlyAmountVariables>): UseDataConnectMutationResult<UpdatePrevisionnelMonthlyAmountData, UpdatePrevisionnelMonthlyAmountVariables>;
export function useUpdatePrevisionnelMonthlyAmount(dc: DataConnect, options?: useDataConnectMutationOptions<UpdatePrevisionnelMonthlyAmountData, FirebaseError, UpdatePrevisionnelMonthlyAmountVariables>): UseDataConnectMutationResult<UpdatePrevisionnelMonthlyAmountData, UpdatePrevisionnelMonthlyAmountVariables>;

export function useUpdatePrevisionnelLineAmounts(options?: useDataConnectMutationOptions<UpdatePrevisionnelLineAmountsData, FirebaseError, UpdatePrevisionnelLineAmountsVariables>): UseDataConnectMutationResult<UpdatePrevisionnelLineAmountsData, UpdatePrevisionnelLineAmountsVariables>;
export function useUpdatePrevisionnelLineAmounts(dc: DataConnect, options?: useDataConnectMutationOptions<UpdatePrevisionnelLineAmountsData, FirebaseError, UpdatePrevisionnelLineAmountsVariables>): UseDataConnectMutationResult<UpdatePrevisionnelLineAmountsData, UpdatePrevisionnelLineAmountsVariables>;

export function useLinkPrevisionnelLineToChantier(options?: useDataConnectMutationOptions<LinkPrevisionnelLineToChantierData, FirebaseError, LinkPrevisionnelLineToChantierVariables>): UseDataConnectMutationResult<LinkPrevisionnelLineToChantierData, LinkPrevisionnelLineToChantierVariables>;
export function useLinkPrevisionnelLineToChantier(dc: DataConnect, options?: useDataConnectMutationOptions<LinkPrevisionnelLineToChantierData, FirebaseError, LinkPrevisionnelLineToChantierVariables>): UseDataConnectMutationResult<LinkPrevisionnelLineToChantierData, LinkPrevisionnelLineToChantierVariables>;

export function useUpsertPrevisionnelCellEdit(options?: useDataConnectMutationOptions<UpsertPrevisionnelCellEditData, FirebaseError, UpsertPrevisionnelCellEditVariables>): UseDataConnectMutationResult<UpsertPrevisionnelCellEditData, UpsertPrevisionnelCellEditVariables>;
export function useUpsertPrevisionnelCellEdit(dc: DataConnect, options?: useDataConnectMutationOptions<UpsertPrevisionnelCellEditData, FirebaseError, UpsertPrevisionnelCellEditVariables>): UseDataConnectMutationResult<UpsertPrevisionnelCellEditData, UpsertPrevisionnelCellEditVariables>;

export function useCreateEmailThread(options?: useDataConnectMutationOptions<CreateEmailThreadData, FirebaseError, CreateEmailThreadVariables>): UseDataConnectMutationResult<CreateEmailThreadData, CreateEmailThreadVariables>;
export function useCreateEmailThread(dc: DataConnect, options?: useDataConnectMutationOptions<CreateEmailThreadData, FirebaseError, CreateEmailThreadVariables>): UseDataConnectMutationResult<CreateEmailThreadData, CreateEmailThreadVariables>;

export function useUpdateEmailThreadStatusAndLinks(options?: useDataConnectMutationOptions<UpdateEmailThreadStatusAndLinksData, FirebaseError, UpdateEmailThreadStatusAndLinksVariables>): UseDataConnectMutationResult<UpdateEmailThreadStatusAndLinksData, UpdateEmailThreadStatusAndLinksVariables>;
export function useUpdateEmailThreadStatusAndLinks(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateEmailThreadStatusAndLinksData, FirebaseError, UpdateEmailThreadStatusAndLinksVariables>): UseDataConnectMutationResult<UpdateEmailThreadStatusAndLinksData, UpdateEmailThreadStatusAndLinksVariables>;

export function useCreateEmailMessage(options?: useDataConnectMutationOptions<CreateEmailMessageData, FirebaseError, CreateEmailMessageVariables>): UseDataConnectMutationResult<CreateEmailMessageData, CreateEmailMessageVariables>;
export function useCreateEmailMessage(dc: DataConnect, options?: useDataConnectMutationOptions<CreateEmailMessageData, FirebaseError, CreateEmailMessageVariables>): UseDataConnectMutationResult<CreateEmailMessageData, CreateEmailMessageVariables>;

export function useCreateEmailAttachment(options?: useDataConnectMutationOptions<CreateEmailAttachmentData, FirebaseError, CreateEmailAttachmentVariables>): UseDataConnectMutationResult<CreateEmailAttachmentData, CreateEmailAttachmentVariables>;
export function useCreateEmailAttachment(dc: DataConnect, options?: useDataConnectMutationOptions<CreateEmailAttachmentData, FirebaseError, CreateEmailAttachmentVariables>): UseDataConnectMutationResult<CreateEmailAttachmentData, CreateEmailAttachmentVariables>;

export function useCreatePlanningEvent(options?: useDataConnectMutationOptions<CreatePlanningEventData, FirebaseError, CreatePlanningEventVariables>): UseDataConnectMutationResult<CreatePlanningEventData, CreatePlanningEventVariables>;
export function useCreatePlanningEvent(dc: DataConnect, options?: useDataConnectMutationOptions<CreatePlanningEventData, FirebaseError, CreatePlanningEventVariables>): UseDataConnectMutationResult<CreatePlanningEventData, CreatePlanningEventVariables>;

export function useUpdatePlanningEventStatus(options?: useDataConnectMutationOptions<UpdatePlanningEventStatusData, FirebaseError, UpdatePlanningEventStatusVariables>): UseDataConnectMutationResult<UpdatePlanningEventStatusData, UpdatePlanningEventStatusVariables>;
export function useUpdatePlanningEventStatus(dc: DataConnect, options?: useDataConnectMutationOptions<UpdatePlanningEventStatusData, FirebaseError, UpdatePlanningEventStatusVariables>): UseDataConnectMutationResult<UpdatePlanningEventStatusData, UpdatePlanningEventStatusVariables>;

export function useUpdatePlanningEventDetails(options?: useDataConnectMutationOptions<UpdatePlanningEventDetailsData, FirebaseError, UpdatePlanningEventDetailsVariables>): UseDataConnectMutationResult<UpdatePlanningEventDetailsData, UpdatePlanningEventDetailsVariables>;
export function useUpdatePlanningEventDetails(dc: DataConnect, options?: useDataConnectMutationOptions<UpdatePlanningEventDetailsData, FirebaseError, UpdatePlanningEventDetailsVariables>): UseDataConnectMutationResult<UpdatePlanningEventDetailsData, UpdatePlanningEventDetailsVariables>;

export function useCancelPlanningEvent(options?: useDataConnectMutationOptions<CancelPlanningEventData, FirebaseError, CancelPlanningEventVariables>): UseDataConnectMutationResult<CancelPlanningEventData, CancelPlanningEventVariables>;
export function useCancelPlanningEvent(dc: DataConnect, options?: useDataConnectMutationOptions<CancelPlanningEventData, FirebaseError, CancelPlanningEventVariables>): UseDataConnectMutationResult<CancelPlanningEventData, CancelPlanningEventVariables>;

export function useCreatePlanningAssignment(options?: useDataConnectMutationOptions<CreatePlanningAssignmentData, FirebaseError, CreatePlanningAssignmentVariables>): UseDataConnectMutationResult<CreatePlanningAssignmentData, CreatePlanningAssignmentVariables>;
export function useCreatePlanningAssignment(dc: DataConnect, options?: useDataConnectMutationOptions<CreatePlanningAssignmentData, FirebaseError, CreatePlanningAssignmentVariables>): UseDataConnectMutationResult<CreatePlanningAssignmentData, CreatePlanningAssignmentVariables>;

export function useUpdatePlanningAssignmentStatus(options?: useDataConnectMutationOptions<UpdatePlanningAssignmentStatusData, FirebaseError, UpdatePlanningAssignmentStatusVariables>): UseDataConnectMutationResult<UpdatePlanningAssignmentStatusData, UpdatePlanningAssignmentStatusVariables>;
export function useUpdatePlanningAssignmentStatus(dc: DataConnect, options?: useDataConnectMutationOptions<UpdatePlanningAssignmentStatusData, FirebaseError, UpdatePlanningAssignmentStatusVariables>): UseDataConnectMutationResult<UpdatePlanningAssignmentStatusData, UpdatePlanningAssignmentStatusVariables>;

export function useCreateAnalyticsSnapshot(options?: useDataConnectMutationOptions<CreateAnalyticsSnapshotData, FirebaseError, CreateAnalyticsSnapshotVariables>): UseDataConnectMutationResult<CreateAnalyticsSnapshotData, CreateAnalyticsSnapshotVariables>;
export function useCreateAnalyticsSnapshot(dc: DataConnect, options?: useDataConnectMutationOptions<CreateAnalyticsSnapshotData, FirebaseError, CreateAnalyticsSnapshotVariables>): UseDataConnectMutationResult<CreateAnalyticsSnapshotData, CreateAnalyticsSnapshotVariables>;

export function useCreateRapport(options?: useDataConnectMutationOptions<CreateRapportData, FirebaseError, CreateRapportVariables>): UseDataConnectMutationResult<CreateRapportData, CreateRapportVariables>;
export function useCreateRapport(dc: DataConnect, options?: useDataConnectMutationOptions<CreateRapportData, FirebaseError, CreateRapportVariables>): UseDataConnectMutationResult<CreateRapportData, CreateRapportVariables>;

export function useMarkRapportGenerated(options?: useDataConnectMutationOptions<MarkRapportGeneratedData, FirebaseError, MarkRapportGeneratedVariables>): UseDataConnectMutationResult<MarkRapportGeneratedData, MarkRapportGeneratedVariables>;
export function useMarkRapportGenerated(dc: DataConnect, options?: useDataConnectMutationOptions<MarkRapportGeneratedData, FirebaseError, MarkRapportGeneratedVariables>): UseDataConnectMutationResult<MarkRapportGeneratedData, MarkRapportGeneratedVariables>;

export function useCreateAuditEvent(options?: useDataConnectMutationOptions<CreateAuditEventData, FirebaseError, CreateAuditEventVariables>): UseDataConnectMutationResult<CreateAuditEventData, CreateAuditEventVariables>;
export function useCreateAuditEvent(dc: DataConnect, options?: useDataConnectMutationOptions<CreateAuditEventData, FirebaseError, CreateAuditEventVariables>): UseDataConnectMutationResult<CreateAuditEventData, CreateAuditEventVariables>;

export function useCreateCheckpointRun(options?: useDataConnectMutationOptions<CreateCheckpointRunData, FirebaseError, CreateCheckpointRunVariables>): UseDataConnectMutationResult<CreateCheckpointRunData, CreateCheckpointRunVariables>;
export function useCreateCheckpointRun(dc: DataConnect, options?: useDataConnectMutationOptions<CreateCheckpointRunData, FirebaseError, CreateCheckpointRunVariables>): UseDataConnectMutationResult<CreateCheckpointRunData, CreateCheckpointRunVariables>;

export function useCreateCheckpointStep(options?: useDataConnectMutationOptions<CreateCheckpointStepData, FirebaseError, CreateCheckpointStepVariables>): UseDataConnectMutationResult<CreateCheckpointStepData, CreateCheckpointStepVariables>;
export function useCreateCheckpointStep(dc: DataConnect, options?: useDataConnectMutationOptions<CreateCheckpointStepData, FirebaseError, CreateCheckpointStepVariables>): UseDataConnectMutationResult<CreateCheckpointStepData, CreateCheckpointStepVariables>;

export function useCreateCheckpointArtifact(options?: useDataConnectMutationOptions<CreateCheckpointArtifactData, FirebaseError, CreateCheckpointArtifactVariables>): UseDataConnectMutationResult<CreateCheckpointArtifactData, CreateCheckpointArtifactVariables>;
export function useCreateCheckpointArtifact(dc: DataConnect, options?: useDataConnectMutationOptions<CreateCheckpointArtifactData, FirebaseError, CreateCheckpointArtifactVariables>): UseDataConnectMutationResult<CreateCheckpointArtifactData, CreateCheckpointArtifactVariables>;

export function useCreateCheckpointDecision(options?: useDataConnectMutationOptions<CreateCheckpointDecisionData, FirebaseError, CreateCheckpointDecisionVariables>): UseDataConnectMutationResult<CreateCheckpointDecisionData, CreateCheckpointDecisionVariables>;
export function useCreateCheckpointDecision(dc: DataConnect, options?: useDataConnectMutationOptions<CreateCheckpointDecisionData, FirebaseError, CreateCheckpointDecisionVariables>): UseDataConnectMutationResult<CreateCheckpointDecisionData, CreateCheckpointDecisionVariables>;

export function useCreateDataImportRun(options?: useDataConnectMutationOptions<CreateDataImportRunData, FirebaseError, CreateDataImportRunVariables>): UseDataConnectMutationResult<CreateDataImportRunData, CreateDataImportRunVariables>;
export function useCreateDataImportRun(dc: DataConnect, options?: useDataConnectMutationOptions<CreateDataImportRunData, FirebaseError, CreateDataImportRunVariables>): UseDataConnectMutationResult<CreateDataImportRunData, CreateDataImportRunVariables>;

export function useCreateDataImportIssue(options?: useDataConnectMutationOptions<CreateDataImportIssueData, FirebaseError, CreateDataImportIssueVariables>): UseDataConnectMutationResult<CreateDataImportIssueData, CreateDataImportIssueVariables>;
export function useCreateDataImportIssue(dc: DataConnect, options?: useDataConnectMutationOptions<CreateDataImportIssueData, FirebaseError, CreateDataImportIssueVariables>): UseDataConnectMutationResult<CreateDataImportIssueData, CreateDataImportIssueVariables>;

export function useCreateEntityChangeLog(options?: useDataConnectMutationOptions<CreateEntityChangeLogData, FirebaseError, CreateEntityChangeLogVariables>): UseDataConnectMutationResult<CreateEntityChangeLogData, CreateEntityChangeLogVariables>;
export function useCreateEntityChangeLog(dc: DataConnect, options?: useDataConnectMutationOptions<CreateEntityChangeLogData, FirebaseError, CreateEntityChangeLogVariables>): UseDataConnectMutationResult<CreateEntityChangeLogData, CreateEntityChangeLogVariables>;

export function useGetCurrentUser(options?: useDataConnectQueryOptions<GetCurrentUserData>): UseDataConnectQueryResult<GetCurrentUserData, undefined>;
export function useGetCurrentUser(dc: DataConnect, options?: useDataConnectQueryOptions<GetCurrentUserData>): UseDataConnectQueryResult<GetCurrentUserData, undefined>;

export function useListUsers(options?: useDataConnectQueryOptions<ListUsersData>): UseDataConnectQueryResult<ListUsersData, undefined>;
export function useListUsers(dc: DataConnect, options?: useDataConnectQueryOptions<ListUsersData>): UseDataConnectQueryResult<ListUsersData, undefined>;

export function useGetCurrentTeamProfileSubmission(options?: useDataConnectQueryOptions<GetCurrentTeamProfileSubmissionData>): UseDataConnectQueryResult<GetCurrentTeamProfileSubmissionData, undefined>;
export function useGetCurrentTeamProfileSubmission(dc: DataConnect, options?: useDataConnectQueryOptions<GetCurrentTeamProfileSubmissionData>): UseDataConnectQueryResult<GetCurrentTeamProfileSubmissionData, undefined>;

export function useListTeamProfileSubmissions(options?: useDataConnectQueryOptions<ListTeamProfileSubmissionsData>): UseDataConnectQueryResult<ListTeamProfileSubmissionsData, undefined>;
export function useListTeamProfileSubmissions(dc: DataConnect, options?: useDataConnectQueryOptions<ListTeamProfileSubmissionsData>): UseDataConnectQueryResult<ListTeamProfileSubmissionsData, undefined>;

export function useListSossonTeams(options?: useDataConnectQueryOptions<ListSossonTeamsData>): UseDataConnectQueryResult<ListSossonTeamsData, undefined>;
export function useListSossonTeams(dc: DataConnect, options?: useDataConnectQueryOptions<ListSossonTeamsData>): UseDataConnectQueryResult<ListSossonTeamsData, undefined>;

export function useListSossonWorkTimeEntries(vars: ListSossonWorkTimeEntriesVariables, options?: useDataConnectQueryOptions<ListSossonWorkTimeEntriesData>): UseDataConnectQueryResult<ListSossonWorkTimeEntriesData, ListSossonWorkTimeEntriesVariables>;
export function useListSossonWorkTimeEntries(dc: DataConnect, vars: ListSossonWorkTimeEntriesVariables, options?: useDataConnectQueryOptions<ListSossonWorkTimeEntriesData>): UseDataConnectQueryResult<ListSossonWorkTimeEntriesData, ListSossonWorkTimeEntriesVariables>;

export function useListSossonPayrollPeriods(vars: ListSossonPayrollPeriodsVariables, options?: useDataConnectQueryOptions<ListSossonPayrollPeriodsData>): UseDataConnectQueryResult<ListSossonPayrollPeriodsData, ListSossonPayrollPeriodsVariables>;
export function useListSossonPayrollPeriods(dc: DataConnect, vars: ListSossonPayrollPeriodsVariables, options?: useDataConnectQueryOptions<ListSossonPayrollPeriodsData>): UseDataConnectQueryResult<ListSossonPayrollPeriodsData, ListSossonPayrollPeriodsVariables>;

export function useListOperationalClients(options?: useDataConnectQueryOptions<ListOperationalClientsData>): UseDataConnectQueryResult<ListOperationalClientsData, undefined>;
export function useListOperationalClients(dc: DataConnect, options?: useDataConnectQueryOptions<ListOperationalClientsData>): UseDataConnectQueryResult<ListOperationalClientsData, undefined>;

export function useGetClient(vars: GetClientVariables, options?: useDataConnectQueryOptions<GetClientData>): UseDataConnectQueryResult<GetClientData, GetClientVariables>;
export function useGetClient(dc: DataConnect, vars: GetClientVariables, options?: useDataConnectQueryOptions<GetClientData>): UseDataConnectQueryResult<GetClientData, GetClientVariables>;

export function useListOperationalChantiers(options?: useDataConnectQueryOptions<ListOperationalChantiersData>): UseDataConnectQueryResult<ListOperationalChantiersData, undefined>;
export function useListOperationalChantiers(dc: DataConnect, options?: useDataConnectQueryOptions<ListOperationalChantiersData>): UseDataConnectQueryResult<ListOperationalChantiersData, undefined>;

export function useGetChantier(vars: GetChantierVariables, options?: useDataConnectQueryOptions<GetChantierData>): UseDataConnectQueryResult<GetChantierData, GetChantierVariables>;
export function useGetChantier(dc: DataConnect, vars: GetChantierVariables, options?: useDataConnectQueryOptions<GetChantierData>): UseDataConnectQueryResult<GetChantierData, GetChantierVariables>;

export function useListDevis(options?: useDataConnectQueryOptions<ListDevisData>): UseDataConnectQueryResult<ListDevisData, undefined>;
export function useListDevis(dc: DataConnect, options?: useDataConnectQueryOptions<ListDevisData>): UseDataConnectQueryResult<ListDevisData, undefined>;

export function useListDevisByClient(vars: ListDevisByClientVariables, options?: useDataConnectQueryOptions<ListDevisByClientData>): UseDataConnectQueryResult<ListDevisByClientData, ListDevisByClientVariables>;
export function useListDevisByClient(dc: DataConnect, vars: ListDevisByClientVariables, options?: useDataConnectQueryOptions<ListDevisByClientData>): UseDataConnectQueryResult<ListDevisByClientData, ListDevisByClientVariables>;

export function useListDevisByChantier(vars: ListDevisByChantierVariables, options?: useDataConnectQueryOptions<ListDevisByChantierData>): UseDataConnectQueryResult<ListDevisByChantierData, ListDevisByChantierVariables>;
export function useListDevisByChantier(dc: DataConnect, vars: ListDevisByChantierVariables, options?: useDataConnectQueryOptions<ListDevisByChantierData>): UseDataConnectQueryResult<ListDevisByChantierData, ListDevisByChantierVariables>;

export function useListFactures(options?: useDataConnectQueryOptions<ListFacturesData>): UseDataConnectQueryResult<ListFacturesData, undefined>;
export function useListFactures(dc: DataConnect, options?: useDataConnectQueryOptions<ListFacturesData>): UseDataConnectQueryResult<ListFacturesData, undefined>;

export function useListFacturesByStatut(vars: ListFacturesByStatutVariables, options?: useDataConnectQueryOptions<ListFacturesByStatutData>): UseDataConnectQueryResult<ListFacturesByStatutData, ListFacturesByStatutVariables>;
export function useListFacturesByStatut(dc: DataConnect, vars: ListFacturesByStatutVariables, options?: useDataConnectQueryOptions<ListFacturesByStatutData>): UseDataConnectQueryResult<ListFacturesByStatutData, ListFacturesByStatutVariables>;

export function useListDocumentFolders(options?: useDataConnectQueryOptions<ListDocumentFoldersData>): UseDataConnectQueryResult<ListDocumentFoldersData, undefined>;
export function useListDocumentFolders(dc: DataConnect, options?: useDataConnectQueryOptions<ListDocumentFoldersData>): UseDataConnectQueryResult<ListDocumentFoldersData, undefined>;

export function useListDocumentsAttaches(options?: useDataConnectQueryOptions<ListDocumentsAttachesData>): UseDataConnectQueryResult<ListDocumentsAttachesData, undefined>;
export function useListDocumentsAttaches(dc: DataConnect, options?: useDataConnectQueryOptions<ListDocumentsAttachesData>): UseDataConnectQueryResult<ListDocumentsAttachesData, undefined>;

export function useListDocumentsByChantier(vars: ListDocumentsByChantierVariables, options?: useDataConnectQueryOptions<ListDocumentsByChantierData>): UseDataConnectQueryResult<ListDocumentsByChantierData, ListDocumentsByChantierVariables>;
export function useListDocumentsByChantier(dc: DataConnect, vars: ListDocumentsByChantierVariables, options?: useDataConnectQueryOptions<ListDocumentsByChantierData>): UseDataConnectQueryResult<ListDocumentsByChantierData, ListDocumentsByChantierVariables>;

export function useListPrevisionnelExercises(options?: useDataConnectQueryOptions<ListPrevisionnelExercisesData>): UseDataConnectQueryResult<ListPrevisionnelExercisesData, undefined>;
export function useListPrevisionnelExercises(dc: DataConnect, options?: useDataConnectQueryOptions<ListPrevisionnelExercisesData>): UseDataConnectQueryResult<ListPrevisionnelExercisesData, undefined>;

export function useListPrevisionnelLinesByExercise(vars: ListPrevisionnelLinesByExerciseVariables, options?: useDataConnectQueryOptions<ListPrevisionnelLinesByExerciseData>): UseDataConnectQueryResult<ListPrevisionnelLinesByExerciseData, ListPrevisionnelLinesByExerciseVariables>;
export function useListPrevisionnelLinesByExercise(dc: DataConnect, vars: ListPrevisionnelLinesByExerciseVariables, options?: useDataConnectQueryOptions<ListPrevisionnelLinesByExerciseData>): UseDataConnectQueryResult<ListPrevisionnelLinesByExerciseData, ListPrevisionnelLinesByExerciseVariables>;

export function useSearchClientAliases(vars: SearchClientAliasesVariables, options?: useDataConnectQueryOptions<SearchClientAliasesData>): UseDataConnectQueryResult<SearchClientAliasesData, SearchClientAliasesVariables>;
export function useSearchClientAliases(dc: DataConnect, vars: SearchClientAliasesVariables, options?: useDataConnectQueryOptions<SearchClientAliasesData>): UseDataConnectQueryResult<SearchClientAliasesData, SearchClientAliasesVariables>;

export function useListPrevisionnelCellEdits(vars: ListPrevisionnelCellEditsVariables, options?: useDataConnectQueryOptions<ListPrevisionnelCellEditsData>): UseDataConnectQueryResult<ListPrevisionnelCellEditsData, ListPrevisionnelCellEditsVariables>;
export function useListPrevisionnelCellEdits(dc: DataConnect, vars: ListPrevisionnelCellEditsVariables, options?: useDataConnectQueryOptions<ListPrevisionnelCellEditsData>): UseDataConnectQueryResult<ListPrevisionnelCellEditsData, ListPrevisionnelCellEditsVariables>;

export function useListEmailThreads(options?: useDataConnectQueryOptions<ListEmailThreadsData>): UseDataConnectQueryResult<ListEmailThreadsData, undefined>;
export function useListEmailThreads(dc: DataConnect, options?: useDataConnectQueryOptions<ListEmailThreadsData>): UseDataConnectQueryResult<ListEmailThreadsData, undefined>;

export function useListEmailThreadsByChantier(vars: ListEmailThreadsByChantierVariables, options?: useDataConnectQueryOptions<ListEmailThreadsByChantierData>): UseDataConnectQueryResult<ListEmailThreadsByChantierData, ListEmailThreadsByChantierVariables>;
export function useListEmailThreadsByChantier(dc: DataConnect, vars: ListEmailThreadsByChantierVariables, options?: useDataConnectQueryOptions<ListEmailThreadsByChantierData>): UseDataConnectQueryResult<ListEmailThreadsByChantierData, ListEmailThreadsByChantierVariables>;

export function useListUnreadEmailThreads(options?: useDataConnectQueryOptions<ListUnreadEmailThreadsData>): UseDataConnectQueryResult<ListUnreadEmailThreadsData, undefined>;
export function useListUnreadEmailThreads(dc: DataConnect, options?: useDataConnectQueryOptions<ListUnreadEmailThreadsData>): UseDataConnectQueryResult<ListUnreadEmailThreadsData, undefined>;

export function useGetEmailThread(vars: GetEmailThreadVariables, options?: useDataConnectQueryOptions<GetEmailThreadData>): UseDataConnectQueryResult<GetEmailThreadData, GetEmailThreadVariables>;
export function useGetEmailThread(dc: DataConnect, vars: GetEmailThreadVariables, options?: useDataConnectQueryOptions<GetEmailThreadData>): UseDataConnectQueryResult<GetEmailThreadData, GetEmailThreadVariables>;

export function useListPlanningEventsByPeriod(vars: ListPlanningEventsByPeriodVariables, options?: useDataConnectQueryOptions<ListPlanningEventsByPeriodData>): UseDataConnectQueryResult<ListPlanningEventsByPeriodData, ListPlanningEventsByPeriodVariables>;
export function useListPlanningEventsByPeriod(dc: DataConnect, vars: ListPlanningEventsByPeriodVariables, options?: useDataConnectQueryOptions<ListPlanningEventsByPeriodData>): UseDataConnectQueryResult<ListPlanningEventsByPeriodData, ListPlanningEventsByPeriodVariables>;

export function useListPlanningEventsByChantier(vars: ListPlanningEventsByChantierVariables, options?: useDataConnectQueryOptions<ListPlanningEventsByChantierData>): UseDataConnectQueryResult<ListPlanningEventsByChantierData, ListPlanningEventsByChantierVariables>;
export function useListPlanningEventsByChantier(dc: DataConnect, vars: ListPlanningEventsByChantierVariables, options?: useDataConnectQueryOptions<ListPlanningEventsByChantierData>): UseDataConnectQueryResult<ListPlanningEventsByChantierData, ListPlanningEventsByChantierVariables>;

export function useListPlanningJobSheetsByEvent(vars: ListPlanningJobSheetsByEventVariables, options?: useDataConnectQueryOptions<ListPlanningJobSheetsByEventData>): UseDataConnectQueryResult<ListPlanningJobSheetsByEventData, ListPlanningJobSheetsByEventVariables>;
export function useListPlanningJobSheetsByEvent(dc: DataConnect, vars: ListPlanningJobSheetsByEventVariables, options?: useDataConnectQueryOptions<ListPlanningJobSheetsByEventData>): UseDataConnectQueryResult<ListPlanningJobSheetsByEventData, ListPlanningJobSheetsByEventVariables>;

export function useListAnalyticsSnapshots(vars: ListAnalyticsSnapshotsVariables, options?: useDataConnectQueryOptions<ListAnalyticsSnapshotsData>): UseDataConnectQueryResult<ListAnalyticsSnapshotsData, ListAnalyticsSnapshotsVariables>;
export function useListAnalyticsSnapshots(dc: DataConnect, vars: ListAnalyticsSnapshotsVariables, options?: useDataConnectQueryOptions<ListAnalyticsSnapshotsData>): UseDataConnectQueryResult<ListAnalyticsSnapshotsData, ListAnalyticsSnapshotsVariables>;

export function useGetAnalyticsSnapshot(vars: GetAnalyticsSnapshotVariables, options?: useDataConnectQueryOptions<GetAnalyticsSnapshotData>): UseDataConnectQueryResult<GetAnalyticsSnapshotData, GetAnalyticsSnapshotVariables>;
export function useGetAnalyticsSnapshot(dc: DataConnect, vars: GetAnalyticsSnapshotVariables, options?: useDataConnectQueryOptions<GetAnalyticsSnapshotData>): UseDataConnectQueryResult<GetAnalyticsSnapshotData, GetAnalyticsSnapshotVariables>;

export function useListRapports(options?: useDataConnectQueryOptions<ListRapportsData>): UseDataConnectQueryResult<ListRapportsData, undefined>;
export function useListRapports(dc: DataConnect, options?: useDataConnectQueryOptions<ListRapportsData>): UseDataConnectQueryResult<ListRapportsData, undefined>;

export function useGetRapport(vars: GetRapportVariables, options?: useDataConnectQueryOptions<GetRapportData>): UseDataConnectQueryResult<GetRapportData, GetRapportVariables>;
export function useGetRapport(dc: DataConnect, vars: GetRapportVariables, options?: useDataConnectQueryOptions<GetRapportData>): UseDataConnectQueryResult<GetRapportData, GetRapportVariables>;

export function useListRecentAuditEvents(vars: ListRecentAuditEventsVariables, options?: useDataConnectQueryOptions<ListRecentAuditEventsData>): UseDataConnectQueryResult<ListRecentAuditEventsData, ListRecentAuditEventsVariables>;
export function useListRecentAuditEvents(dc: DataConnect, vars: ListRecentAuditEventsVariables, options?: useDataConnectQueryOptions<ListRecentAuditEventsData>): UseDataConnectQueryResult<ListRecentAuditEventsData, ListRecentAuditEventsVariables>;

export function useListEntityChangeLogs(vars: ListEntityChangeLogsVariables, options?: useDataConnectQueryOptions<ListEntityChangeLogsData>): UseDataConnectQueryResult<ListEntityChangeLogsData, ListEntityChangeLogsVariables>;
export function useListEntityChangeLogs(dc: DataConnect, vars: ListEntityChangeLogsVariables, options?: useDataConnectQueryOptions<ListEntityChangeLogsData>): UseDataConnectQueryResult<ListEntityChangeLogsData, ListEntityChangeLogsVariables>;

export function useListCheckpointRuns(vars: ListCheckpointRunsVariables, options?: useDataConnectQueryOptions<ListCheckpointRunsData>): UseDataConnectQueryResult<ListCheckpointRunsData, ListCheckpointRunsVariables>;
export function useListCheckpointRuns(dc: DataConnect, vars: ListCheckpointRunsVariables, options?: useDataConnectQueryOptions<ListCheckpointRunsData>): UseDataConnectQueryResult<ListCheckpointRunsData, ListCheckpointRunsVariables>;

export function useGetCheckpointRun(vars: GetCheckpointRunVariables, options?: useDataConnectQueryOptions<GetCheckpointRunData>): UseDataConnectQueryResult<GetCheckpointRunData, GetCheckpointRunVariables>;
export function useGetCheckpointRun(dc: DataConnect, vars: GetCheckpointRunVariables, options?: useDataConnectQueryOptions<GetCheckpointRunData>): UseDataConnectQueryResult<GetCheckpointRunData, GetCheckpointRunVariables>;

export function useListDataImportRuns(vars: ListDataImportRunsVariables, options?: useDataConnectQueryOptions<ListDataImportRunsData>): UseDataConnectQueryResult<ListDataImportRunsData, ListDataImportRunsVariables>;
export function useListDataImportRuns(dc: DataConnect, vars: ListDataImportRunsVariables, options?: useDataConnectQueryOptions<ListDataImportRunsData>): UseDataConnectQueryResult<ListDataImportRunsData, ListDataImportRunsVariables>;

export function useGetDataImportRun(vars: GetDataImportRunVariables, options?: useDataConnectQueryOptions<GetDataImportRunData>): UseDataConnectQueryResult<GetDataImportRunData, GetDataImportRunVariables>;
export function useGetDataImportRun(dc: DataConnect, vars: GetDataImportRunVariables, options?: useDataConnectQueryOptions<GetDataImportRunData>): UseDataConnectQueryResult<GetDataImportRunData, GetDataImportRunVariables>;
