mutation @transaction {
  exercises001: previsionnelExercise_upsertMany(data: [
    {
      id: "af5ec199-3d32-5a45-8497-d3048bff0ca2",
      batchId: "6eafb4bd-e2e2-505d-b358-8238cb9b5af2",
      sheet: "2013-14",
      exercise: "2013-14",
      startYear: 2013,
      endYear: 2014,
      lineCount: 48,
      chantierCount: 48,
      caPrevision: 911845,
      caContrat: 911845,
      plannedTotal: 791125,
      realizedTotal: 766810,
      invoicedTotal: 0
    },
    {
      id: "5948d916-0109-55ce-b6e3-b1b8308bdec4",
      batchId: "6eafb4bd-e2e2-505d-b358-8238cb9b5af2",
      sheet: "2014-15",
      exercise: "2014-15",
      startYear: 2014,
      endYear: 2015,
      lineCount: 68,
      chantierCount: 68,
      caPrevision: 1003845,
      caContrat: 1003845,
      plannedTotal: 910138,
      realizedTotal: 888339,
      invoicedTotal: 0
    },
    {
      id: "8e1890be-b944-5602-b61c-65edeb496b36",
      batchId: "6eafb4bd-e2e2-505d-b358-8238cb9b5af2",
      sheet: "2015-16",
      exercise: "2015-16",
      startYear: 2015,
      endYear: 2016,
      lineCount: 76,
      chantierCount: 76,
      caPrevision: 0,
      caContrat: 973694,
      plannedTotal: 905294.8,
      realizedTotal: 842328,
      invoicedTotal: 0
    },
    {
      id: "6ee923a6-4d3b-5253-82bf-0159efa72a1a",
      batchId: "6eafb4bd-e2e2-505d-b358-8238cb9b5af2",
      sheet: "2016-17",
      exercise: "2016-17",
      startYear: 2016,
      endYear: 2017,
      lineCount: 26,
      chantierCount: 26,
      caPrevision: 0,
      caContrat: 1076637,
      plannedTotal: 237309,
      realizedTotal: 248718,
      invoicedTotal: 0
    },
    {
      id: "ef167b0f-b2f5-57cf-ba66-bef48a5a8892",
      batchId: "6eafb4bd-e2e2-505d-b358-8238cb9b5af2",
      sheet: "2017-18",
      exercise: "2017-18",
      startYear: 2017,
      endYear: 2018,
      lineCount: 59,
      chantierCount: 59,
      caPrevision: 1751348.76,
      caContrat: 1312961.94,
      plannedTotal: 1115829.12,
      realizedTotal: 994993.77,
      invoicedTotal: 0
    },
    {
      id: "52b3fb59-b13a-5050-a8d5-712bed5d7111",
      batchId: "6eafb4bd-e2e2-505d-b358-8238cb9b5af2",
      sheet: "2018-19",
      exercise: "2018-19",
      startYear: 2018,
      endYear: 2019,
      lineCount: 60,
      chantierCount: 60,
      caPrevision: 2035953.64,
      caContrat: 1384583.46,
      plannedTotal: 984110.68,
      realizedTotal: 984110,
      invoicedTotal: 0
    },
    {
      id: "b5ed4097-8e47-5ba3-9af3-ad8898eca4e1",
      batchId: "6eafb4bd-e2e2-505d-b358-8238cb9b5af2",
      sheet: "2019-20",
      exercise: "2019-20",
      startYear: 2019,
      endYear: 2020,
      lineCount: 75,
      chantierCount: 75,
      caPrevision: 2032018.93,
      caContrat: 1637337.08,
      plannedTotal: 1083034.93,
      realizedTotal: 1083031.92,
      invoicedTotal: 0
    },
    {
      id: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      batchId: "6eafb4bd-e2e2-505d-b358-8238cb9b5af2",
      sheet: "2020-21",
      exercise: "2020-21",
      startYear: 2020,
      endYear: 2021,
      lineCount: 65,
      chantierCount: 65,
      caPrevision: 2192400.37,
      caContrat: 2193304.54,
      plannedTotal: 1407862.1,
      realizedTotal: 1406126.14,
      invoicedTotal: 703642.5
    },
    {
      id: "2730836e-b7b4-5529-8d77-632f8ce2af1b",
      batchId: "6eafb4bd-e2e2-505d-b358-8238cb9b5af2",
      sheet: "2021-22",
      exercise: "2021-22",
      startYear: 2021,
      endYear: 2022,
      lineCount: 67,
      chantierCount: 67,
      caPrevision: 2881527.58,
      caContrat: 2867308.99,
      plannedTotal: 1407287.84,
      realizedTotal: 1406547.86,
      invoicedTotal: 1406453.6
    },
    {
      id: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      batchId: "6eafb4bd-e2e2-505d-b358-8238cb9b5af2",
      sheet: "2022-23",
      exercise: "2022-23",
      startYear: 2022,
      endYear: 2023,
      lineCount: 65,
      chantierCount: 65,
      caPrevision: 4037794.03,
      caContrat: 3892373.82,
      plannedTotal: 1837253.19,
      realizedTotal: 1836973.35,
      invoicedTotal: 1836973.35
    },
    {
      id: "71924609-bbd4-5739-a422-cc8df804aac6",
      batchId: "6eafb4bd-e2e2-505d-b358-8238cb9b5af2",
      sheet: "2023-24",
      exercise: "2023-24",
      startYear: 2023,
      endYear: 2024,
      lineCount: 84,
      chantierCount: 84,
      caPrevision: 4506234.63,
      caContrat: 4415848.93,
      plannedTotal: 2146738.78,
      realizedTotal: 2147133.41,
      invoicedTotal: 2145772.61
    },
    {
      id: "139213a0-302f-59cc-aa47-ddf6d0731154",
      batchId: "6eafb4bd-e2e2-505d-b358-8238cb9b5af2",
      sheet: "2024-25",
      exercise: "2024-25",
      startYear: 2024,
      endYear: 2025,
      lineCount: 104,
      chantierCount: 104,
      caPrevision: 6116610.41,
      caContrat: 3608226.76,
      plannedTotal: 2034341.3,
      realizedTotal: 1927312.73,
      invoicedTotal: 1915682.38
    },
    {
      id: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      batchId: "6eafb4bd-e2e2-505d-b358-8238cb9b5af2",
      sheet: "2025-26",
      exercise: "2025-26",
      startYear: 2025,
      endYear: 2026,
      lineCount: 101,
      chantierCount: 101,
      caPrevision: 6334248.36,
      caContrat: 1638743.76,
      plannedTotal: 2170205.81,
      realizedTotal: 1362790.96,
      invoicedTotal: 1162968.72
    }
  ])
}
