mutation @transaction {
  clients001: client_upsertMany(data: [
    {
      id: "3f66023c-da4f-5fb2-a567-8a0c98cd85e2",
      type: "particulier",
      nom: "Aassgard",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "e6e7f6ad-13ea-5769-af23-bf90446b5a86",
      type: "particulier",
      nom: "Adb Treviers",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "df259ba4-b36f-5f77-9016-9543d6cb4a54",
      type: "particulier",
      nom: "Adb Val D'Arry",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "0ced39fa-6543-5e09-91dd-2e7a6ad65dec",
      type: "particulier",
      nom: "Aec ref heckel",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "43e881a7-241d-5f3b-a414-30db82f51f55",
      type: "particulier",
      nom: "Agelia",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "e0821946-ce1e-523b-a79b-151c4affcb55",
      type: "particulier",
      nom: "Agren",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "79ea0631-ae56-58cc-9a86-405125df7a5a",
      type: "particulier",
      nom: "Allemagne",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "1e9cffaa-92a1-58d4-ab23-2d1cd71c8ef5",
      type: "particulier",
      nom: "Alto",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "31289dad-22eb-5dd4-8a36-b57d8d811a6d",
      type: "particulier",
      nom: "Amcm",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "2b4b1e97-ecd0-57cd-9385-913f5954b4e5",
      type: "particulier",
      nom: "Amram",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "4b8dc882-7db0-5df2-91bc-ca5bfe663fa7",
      type: "particulier",
      nom: "Anquetil",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "2fa7856c-e24d-5173-977c-8750ac8cf4b9",
      type: "particulier",
      nom: "Antoine ferreira",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "23115f94-d844-5698-b020-14e623d84f84",
      type: "particulier",
      nom: "Antoine Ferrera POPUP",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "2f2e8f37-7af8-5500-9a8b-b83c5ed172de",
      type: "particulier",
      nom: "Apaei",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "dc5b9248-925c-5171-86ff-26344d1a64c6",
      type: "particulier",
      nom: "Arche Des Bebes",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "47268d49-7589-5b3c-a6d4-0e49cee8dfaa",
      type: "particulier",
      nom: "Arnould Lemoine",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "a738d31f-a66f-5c7c-b05b-e75a58b16a85",
      type: "particulier",
      nom: "ARNOULD LEMOINE portes",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "241da042-1e0d-5eed-9b70-9b76d2ae792a",
      type: "particulier",
      nom: "Arnould Lemoine Terrasse 2",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "15745471-48c9-57c1-9c40-ea2963aea6e8",
      type: "particulier",
      nom: "Arnoult Lemoine",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "375d3f53-2b0a-5577-9348-9c7227601dd8",
      type: "particulier",
      nom: "Artu Maubanc",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "17c0d9e8-21ac-5a7e-95f3-1ae2b236b993",
      type: "particulier",
      nom: "Atilla",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "005279bf-2eb5-50f3-bff9-dd0a0a694aee",
      type: "particulier",
      nom: "Auber",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "b816c25f-3734-5df9-939e-cb3803a2ba4e",
      type: "particulier",
      nom: "Bacon",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "03bbf32d-d65a-5cb3-bb7d-4b2e8753a59f",
      type: "particulier",
      nom: "Bacon Alvin",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "d43fff91-0e39-5083-93d3-92410f0f6e0e",
      type: "particulier",
      nom: "Banse Brotelande",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "d12afc56-5fb3-5c87-8ca6-04dbd7a09f4c",
      type: "particulier",
      nom: "Baron",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "f1f31dc2-6416-5e2d-b24b-726c45ea5122",
      type: "particulier",
      nom: "BARRE à Thaon",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "864d95a4-f088-5b8f-8b6b-b67c8aec9542",
      type: "particulier",
      nom: "Bassiere",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "5da63188-cf5c-501c-8fd3-24bcad2c8980",
      type: "particulier",
      nom: "Beaussier",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "89a041f1-15c2-595c-bd16-de9bb573a609",
      type: "particulier",
      nom: "Bellenger mob",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "fa1348f6-c6a2-5ade-8345-214c2830c10c",
      type: "particulier",
      nom: "BEN Julien",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "88bf6248-0679-5496-a50f-8c26f4b535be",
      type: "particulier",
      nom: "Benoist",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "453c901e-439f-50a5-9e2c-75e53d2cde55",
      type: "particulier",
      nom: "Benoist Yo",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "5bafe49f-d048-5a9c-a890-fdec0f7db3f4",
      type: "particulier",
      nom: "Benoist yohann",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "01e90885-b7d1-5f2d-8bf6-64013b058cf6",
      type: "particulier",
      nom: "Bergar",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "86005441-8584-5832-acde-82c07d8b8a95",
      type: "particulier",
      nom: "Bergard",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "ce626d72-6684-5bfa-b0d6-0fefd24ace7f",
      type: "particulier",
      nom: "Bernard",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "dc156fff-ae29-550b-b3af-231b3038f59f",
      type: "particulier",
      nom: "BERNARD Goeff",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "a645467e-98df-5edb-b4bd-410c42db44a2",
      type: "particulier",
      nom: "Bertrand",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "ef63a9e9-eff9-5767-9489-38d75761ca59",
      type: "particulier",
      nom: "Besnier mob",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "76a561ca-6060-525c-b3bf-54bdb3b9e7fc",
      type: "particulier",
      nom: "Bicard",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "c4acc9d2-f0f4-5400-a212-874695eb9fd6",
      type: "particulier",
      nom: "Bicard-burlot",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "8522625e-f629-524d-b005-fe54bdbe7b1e",
      type: "particulier",
      nom: "Bicart",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "35796466-74cf-5644-8df6-101a9b274fa8",
      type: "particulier",
      nom: "Bihel sbtp",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "5d2d3b82-a599-58bd-9abb-e280b1ea2938",
      type: "particulier",
      nom: "BILLE francois",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "8bac2d43-da26-50e9-aaf2-6478553852c9",
      type: "particulier",
      nom: "Billet",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "d34aff0b-6321-5e8b-9f9d-48f9737f7080",
      type: "particulier",
      nom: "Billoin Heuguebart",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "ae255225-2ac0-5319-8f58-226d5a9b2f25",
      type: "particulier",
      nom: "Binet",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "637997e2-30e7-59cb-9624-8b99f48cd34a",
      type: "particulier",
      nom: "Bisson",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "ff6edfb0-1aef-521d-95b1-cf0a56cccc4b",
      type: "particulier",
      nom: "Blottiere Lamarre",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    }
  ])
}
