mutation @transaction {
  clients004: client_upsertMany(data: [
    {
      id: "de095f46-6e3c-5e8d-9a1f-023e6cc7075d",
      type: "particulier",
      nom: "Delamare",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "d800d795-e348-57d9-a184-54f77db2406d",
      type: "particulier",
      nom: "Delasalle",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "c3fa4f44-8dbe-5ebc-acc9-28cea1fe3c2a",
      type: "particulier",
      nom: "Delente",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "8172091c-eba8-54da-a1ce-931cc792a482",
      type: "particulier",
      nom: "Delentecommelchal",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "f28f3fef-d8e1-5f5a-8757-bdc0ee0e6a43",
      type: "particulier",
      nom: "Delorme",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "7a79085d-3d23-5d67-83ab-0f1a9990700c",
      type: "particulier",
      nom: "DENIS Archiviolette",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "696d8026-91d1-5e44-a57d-2701eed9429f",
      type: "particulier",
      nom: "Denos Kopp",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "c2aead3d-8156-5367-9bbe-2aaf0872e6e9",
      type: "particulier",
      nom: "DENOS KOPP Varaville",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "2865daf2-1885-5396-bcb4-01b9fef5295d",
      type: "particulier",
      nom: "Deprez",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "1c2cb019-48f6-514e-b20d-de354f6a5334",
      type: "particulier",
      nom: "Desfeux reno",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "ba21b0a9-8170-5cd6-978b-5b51c57db705",
      type: "particulier",
      nom: "Desfontaine",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "3ac06c50-5b0d-59a6-aa1e-4f08b27a2bbe",
      type: "particulier",
      nom: "Desloges",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "234a101d-2cef-5f48-9f61-2413c75bf4fb",
      type: "particulier",
      nom: "Desnos",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "f020c703-292a-5b30-975e-a464a6c90def",
      type: "particulier",
      nom: "Devezaux",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "aa55d2ab-5294-583b-97d8-aae793b250b3",
      type: "particulier",
      nom: "Dlh",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "a7e06ec7-718a-5643-aa71-32421e4b5842",
      type: "particulier",
      nom: "Dmub Sarljulmas",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "df845d9f-71d7-58d0-a7b3-14f57a46204a",
      type: "particulier",
      nom: "Drocourt",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "419b282b-c271-5ac2-8266-475a2eb78bfc",
      type: "particulier",
      nom: "DROCOURT Marina",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "ad6a2a15-afdc-52e7-9a38-e9b0ff40f1db",
      type: "particulier",
      nom: "Dubois Chaignet",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "ffd8132f-8921-5863-866a-fe20f25b87d7",
      type: "particulier",
      nom: "Dubosq",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "559103be-420c-5e27-af70-397e3e06e10a",
      type: "particulier",
      nom: "Dubreul",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "3e2f4959-612f-549e-909c-72d85381f0ad",
      type: "particulier",
      nom: "Duchenne",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "999ac1e5-d9f3-5319-a127-a8768733669f",
      type: "particulier",
      nom: "Duchesne",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "b50a77e0-d46f-52e4-b233-fe4650d406da",
      type: "particulier",
      nom: "Dufour",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "c9a7c679-f79c-55c8-baf6-92f3f9f40e79",
      type: "particulier",
      nom: "Dufour G",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "bb0123ad-0a33-51bc-a0f8-1b568f488144",
      type: "particulier",
      nom: "DUFOUR Gaêtan",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "86fca1cd-ed3a-5e24-baee-0dae918f5555",
      type: "particulier",
      nom: "DUFOUR Maxime",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "e1bf1ca3-6db0-53bc-bb09-e161ada1e525",
      type: "particulier",
      nom: "Dumas",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "2381f335-89c0-5690-bf71-8146e976c6b6",
      type: "particulier",
      nom: "Dumat 2",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "f205a359-f6a3-5239-8793-107b1f17bece",
      type: "particulier",
      nom: "Dumat Matta",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "7d671083-efe2-5c6f-9ee9-654df49abe97",
      type: "particulier",
      nom: "Dumont cocain",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "a10a279b-05b7-5d49-8845-f71100e8aa5f",
      type: "particulier",
      nom: "Dumont lelong",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "4ea28230-791d-5705-9f40-c0d13c719fdf",
      type: "particulier",
      nom: "Dupont",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "0b969251-2aa0-5b12-81be-9b6a2928e5de",
      type: "particulier",
      nom: "Dupont Chalesle",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "8e480e86-d9eb-59e3-88fb-3d167241483d",
      type: "particulier",
      nom: "DUPONT CHALESLE iso ext",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "3306ecf2-347b-5a84-b861-c58072698717",
      type: "particulier",
      nom: "Duquenoy",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "18f01e4a-f64d-5718-976b-6b98e18eaa79",
      type: "particulier",
      nom: "Dutripon R",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "27aeb192-980b-5eb1-b1c4-b065fcce2be1",
      type: "particulier",
      nom: "DUVAL à moult",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "b9645639-f7d0-5900-9bc2-34d9f56a899f",
      type: "particulier",
      nom: "Earl Ferme Du Parc",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "507f8132-d111-5d0d-8b81-41fbdcccc459",
      type: "public",
      nom: "Ecole Merville",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "96a6df6e-48a9-5031-aa74-917c9c51297c",
      type: "particulier",
      nom: "Ecurie Basseneville",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "d6a48b98-d6ec-563f-a990-4f72ae1d7c29",
      type: "particulier",
      nom: "ENP fourniture Laine 80mm",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "19dd85bb-675b-537c-80a9-9c6126308711",
      type: "particulier",
      nom: "Eoles aventures",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "dd6c7e19-3eec-55d0-80aa-1a6f87f045b9",
      type: "particulier",
      nom: "Epinette",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "a818534d-7af3-5007-8b4a-52c2ff6552e0",
      type: "particulier",
      nom: "Esnault",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "873b5e0b-2c45-5564-bc46-4527d324d725",
      type: "particulier",
      nom: "Estorges",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "9aa5e33d-bd00-5930-a2c5-0cacfef111ca",
      type: "particulier",
      nom: "Etourmy Bailly",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "fb3bc8e5-f056-5d4c-9cc4-b47785e3d9c9",
      type: "particulier",
      nom: "Euromatec",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "78d1bd33-069f-574a-82c0-af1f1a26bea8",
      type: "particulier",
      nom: "Exaequo",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "3d4d9a17-4cde-547b-ad39-fbdd60125388",
      type: "particulier",
      nom: "Fablet",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    }
  ])
}
