mutation @transaction {
  clients011: client_upsertMany(data: [
    {
      id: "df8161e2-bf64-51dd-8077-4955216aadb6",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Rousseau",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "9f9915c9-d0f5-56f5-b88d-60093a800cb4",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Roussel",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "fb326462-bd70-5f68-9d78-afc2c997218e",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Saillard",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "1f1625eb-18e3-518d-a3b6-29709b7d7101",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Saison",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "7920e1da-b019-575f-8fae-ef8d7d61ea16",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Saiter",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "a470802a-4281-5c13-9e28-9c1200f6006e",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Samson",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "c7644622-1f80-5d6f-a01b-c71633487b33",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "SAMSON Agnes",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "81cdc722-1726-5913-a773-2197fc42ec8e",
      origineImport: "previsionnel",
      type: "professionnel",
      nom: "Sarl Alp",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "97bdebb9-e591-559f-b6da-9e6f45e65291",
      origineImport: "previsionnel",
      type: "professionnel",
      nom: "Sarl ecs bretteville",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "004c736f-4ecb-5cc2-8faa-ceb97b8cffa4",
      origineImport: "previsionnel",
      type: "professionnel",
      nom: "Sarl Esnault Les Marinas",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "0659edea-693d-5b30-a3f5-0d08aae13f43",
      origineImport: "previsionnel",
      type: "professionnel",
      nom: "Sarl ferme du parc",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "b1843c66-02ca-5bf0-85d0-acc9cd9db651",
      origineImport: "previsionnel",
      type: "professionnel",
      nom: "Sarl La Fournee",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "128e8cfb-ea4d-5187-9a6d-a66993d68aa4",
      origineImport: "previsionnel",
      type: "professionnel",
      nom: "Sarl sosson depot repar",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "d702245f-2e5e-514d-8ce8-301e44f5165f",
      origineImport: "previsionnel",
      type: "professionnel",
      nom: "Sarl sosson sci galou",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "13fd849e-899c-581d-8811-c02340d27c31",
      origineImport: "previsionnel",
      type: "professionnel",
      nom: "Sas Colleville Production",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "72d9b697-d026-5128-b1a9-a406e923fbce",
      origineImport: "previsionnel",
      type: "professionnel",
      nom: "Sas Lpcr",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "db2ce1d1-8b2f-5fdd-9e20-4388295072a2",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Saussaye",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "9200ccd5-aaba-519e-9796-6a26a0f39153",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Sautot",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "c9144ef9-4a4d-5819-bd32-c3f43043a44f",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "SAUTOT Box",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "eef1ee57-cd82-5f80-9739-b6b64163ff9d",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "SAUTOT Terrasse",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "5d4845d0-cddb-5696-86d4-95d3ff9b902d",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Savary",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "82cedece-029d-5d89-9f68-346d79c41171",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Sbtp Bihel",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "1f4debf8-dee7-51c9-b995-aebb0818253f",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Schacher",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "d1be87b6-38f1-53a9-a8cd-1fa532ae55bb",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Schiel",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "a848e5c8-e83a-5913-afcf-83ca62c8170c",
      origineImport: "previsionnel",
      type: "professionnel",
      nom: "Sci Amsd",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "202cd42d-46d0-51aa-80af-47aa3dbe1ee7",
      origineImport: "previsionnel",
      type: "professionnel",
      nom: "Sci Cotard",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "1a7936d8-eadd-5a5b-9ce4-90b8d05cc899",
      origineImport: "previsionnel",
      type: "professionnel",
      nom: "Sci Des Mottets",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "c7be6f26-b6d1-5657-a321-86468fc6ff3d",
      origineImport: "previsionnel",
      type: "professionnel",
      nom: "Sci Felah",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "2e33ddf3-3ee9-57d8-89e2-eaf64878f28d",
      origineImport: "previsionnel",
      type: "professionnel",
      nom: "Sci fill st sylvain",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "aca8bc5e-37ac-5096-a66d-804aa77c058e",
      origineImport: "previsionnel",
      type: "professionnel",
      nom: "Sci Galou",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "b234d215-fb30-5f41-9666-057ff8a767f3",
      origineImport: "previsionnel",
      type: "professionnel",
      nom: "Sci Ifl",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "44cb8c0b-f2d4-5ef8-abab-71e31d60d17c",
      origineImport: "previsionnel",
      type: "professionnel",
      nom: "Sci jls",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "e588261d-0e3c-54d6-bd08-a06f2abb45bf",
      origineImport: "previsionnel",
      type: "professionnel",
      nom: "Sci Jpblb",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "7c72f06c-eb32-5883-a0fe-7a6b4d77066c",
      origineImport: "previsionnel",
      type: "professionnel",
      nom: "Sci la jalousie",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "233844d5-b016-52b8-9b80-20b920b0a10f",
      origineImport: "previsionnel",
      type: "professionnel",
      nom: "Sci La Moinerie",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "dffe7436-d23a-5328-b64b-2c333b6d57f5",
      origineImport: "previsionnel",
      type: "professionnel",
      nom: "Sci Labradorite",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "f6a0b81b-d831-5e63-90db-14987aecd6ad",
      origineImport: "previsionnel",
      type: "professionnel",
      nom: "Sci Micsteph",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "eb3c8122-2fd0-5b57-9109-5b771ec92520",
      origineImport: "previsionnel",
      type: "professionnel",
      nom: "Sci Nomelani",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "b5c41f3e-4a4a-5616-9ffd-a97181c19943",
      origineImport: "previsionnel",
      type: "professionnel",
      nom: "Sci Palliere",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "dfd0649a-b211-59ae-ae53-175015137c89",
      origineImport: "previsionnel",
      type: "professionnel",
      nom: "Sci Pjr",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "10da6d7d-e908-51fb-9664-311c42dbf2bc",
      origineImport: "previsionnel",
      type: "professionnel",
      nom: "Sci Prj",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "c1de986c-74af-5e22-ae03-60dc4daf8c4c",
      origineImport: "previsionnel",
      type: "professionnel",
      nom: "Sci Watier",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "b39ad262-fe09-5549-96cf-822629991652",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Scournec jean max",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "2f6a57d8-7e88-5abd-95a6-22ede06ad4bf",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Scp michel",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "194b3b7d-2511-5fcb-afbc-e2d07728018e",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "SEC à Moulines",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "f4f38322-7ea4-506b-87d5-9af7be4f6442",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Seegers",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "32937092-a38d-5b8c-915e-d851548c7a7e",
      origineImport: "previsionnel",
      type: "professionnel",
      nom: "Selarl Pharmacie Du Val De Seulles",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "4f265ad2-b525-552b-ad66-927133a97c30",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Selle iso ite",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "ca680d46-db96-513d-b883-20a0ac3507e6",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Shacher",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "5188b7be-98a3-5e14-afd7-8249e8d28068",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Signoret",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    }
  ])
}
