mutation @transaction {
  clients012: client_upsertMany(data: [
    {
      id: "1265ab84-a735-5ada-871b-21ff600fb178",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Simonet",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "93cc4a4e-dcb4-5788-9d06-4cd1c0afbc0a",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Sinigaglia",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "f0aa4612-b79b-5151-8a30-8a5625b53871",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Skrzypeck",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "b2371668-639e-5418-a786-2f69d63d967f",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Sochon",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "a8201396-8e94-5d60-99a6-ac76e363e34c",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Sofinab",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "0c83622f-0f03-507d-b1cd-62da9b15f1bd",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Sourdin",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "14a4d407-a57b-5c0b-848c-b442692d9af6",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Spie batignol",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "f505f120-c09d-5d5a-9a7c-97a36ac13748",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Stab",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "290b5b05-2e37-5ddc-902d-509250b0d0ed",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Stenou",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "30b60963-9a04-5170-9736-7e33b1fe4c4c",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Stenou/Baloche",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "a9683211-8ab3-5f54-ad8c-b916354af2ab",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Suard 32000",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "cf7a39dc-a169-53b3-8c73-e6b3f600f1f0",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Taillepied",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "e8760822-2896-506a-9518-a9d42326cdec",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Talmar",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "cb423553-357a-5de9-bf1e-b663a9547a5b",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Tanguy",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "dc1333ba-f82b-5519-968a-a9769e7be0c3",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Tesson",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "11edf431-3369-5093-a6bb-fb99119cbd1e",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Thereze",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "b31e6072-27e4-5c6e-8248-267d60fdda30",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Thire",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "2bbd101f-c21a-54f3-9aaf-b3efa649934e",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Thomann",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "d07fe66a-1902-5018-8ea4-bd1f83664fa1",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Thouvenin",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "c7d9e879-fa29-5093-837d-f940141d95d3",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "TOUSSAINT à Olendon",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "a455fabe-5dd0-59cd-91d4-6187c0b3b7ea",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Toutain",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "d6d2d11f-63a4-554e-b8e3-816551c4a0ee",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Urbain",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "0c403277-08d7-5d6f-93de-733f35431cd4",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Urban",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "95f9dea7-2d3f-52af-a045-52fa559ca234",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Valdenaire",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "d1ae3495-d48e-51a4-ba78-fafec9ea06a2",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Valsemey",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "a97b5561-46c3-5960-9d47-34928abeaf84",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Vandermersch",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "41351551-17f6-53ce-884d-7cfa323c8460",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Vaucher",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "1d410b91-eb54-55a4-b8a8-b0928ffb5f2b",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Vente matériel Emerick",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "0271f657-a4c2-5d9f-9983-5be50f8d0832",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Vergriete",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "f18691a7-6ca9-5f9e-a639-47d3cf549656",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Viglieri",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "563badef-c3ea-5449-82ed-e597576a5c39",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Viquesnel",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "41868a36-e129-5652-9038-3a761329b567",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Viquesnel mob",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "a55d275e-d567-5b24-b713-f78f21544a34",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Viray",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "cb0e4e53-deb2-5f82-af84-24cecdc2dec5",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Vital Sport Ifs",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "0c184b00-276e-5412-830f-d074e09ef653",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Vivier",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    },
    {
      id: "666e814d-5d2c-5363-98e2-64fed35851a9",
      origineImport: "previsionnel",
      type: "particulier",
      nom: "Zaghbouni",
      email: null,
      telephone: null,
      adresse: null,
      ville: null,
      codePostal: null
    }
  ])
}
