mutation @transaction {
  chantiers005: chantier_upsertMany(data: [
    {
      id: "5cc9f00f-31fa-5b60-ba9c-a721dee2344c",
      origineImport: "previsionnel",
      clientId: "666e814d-5d2c-5363-98e2-64fed35851a9",
      nom: "Zaghbouni (2024-25)",
      statut: "cloture",
      dateDebut: "2024-10-01",
      dateFinPrevue: "2024-11-01",
      dateFin: "2024-11-01",
      budgetPrevisionnel: 117072,
      description: "Import PREVISIONNEL.xlsx - onglet 2024-25, ligne 132, categorie divers.",
      adresse: null
    },
    {
      id: "3df470a3-cf8a-5846-beaf-b3b64ed5513e",
      origineImport: "previsionnel",
      clientId: "22f3e9ed-0837-5c6f-98a6-1b4cffc9648b",
      nom: "Boujrad (2024-25)",
      statut: "cloture",
      dateDebut: "2024-10-01",
      dateFinPrevue: "2024-11-01",
      dateFin: "2024-11-01",
      budgetPrevisionnel: 15459.29,
      description: "Import PREVISIONNEL.xlsx - onglet 2024-25, ligne 136, categorie renovation.",
      adresse: null
    },
    {
      id: "068161f1-5fa1-5b91-bbc2-a4d7d92e877c",
      origineImport: "previsionnel",
      clientId: "9b7ee751-e846-5f2c-9f2c-63daab5e4011",
      nom: "Glowacki (2024-25)",
      statut: "cloture",
      dateDebut: "2024-10-01",
      dateFinPrevue: "2024-11-01",
      dateFin: "2024-11-01",
      budgetPrevisionnel: 92534.81,
      description: "Import PREVISIONNEL.xlsx - onglet 2024-25, ligne 137, categorie renovation.",
      adresse: null
    },
    {
      id: "5be82230-5f48-54ac-bd3d-d3998c61d6ce",
      origineImport: "previsionnel",
      clientId: "815a44cd-dcf4-55d9-a7b2-ef25ecf5a93a",
      nom: "Res,La Roche A Bunel (2024-25)",
      statut: "cloture",
      dateDebut: "2024-10-01",
      dateFinPrevue: "2024-11-01",
      dateFin: "2024-11-01",
      budgetPrevisionnel: 32699.43,
      description: "Import PREVISIONNEL.xlsx - onglet 2024-25, ligne 141, categorie renovation.",
      adresse: null
    },
    {
      id: "e78608a7-4e71-5aec-9649-e12751ad81ff",
      origineImport: "previsionnel",
      clientId: "ebfe7e0a-d277-567c-afa7-80b47c9246f7",
      nom: "GEZE extension (2024-25)",
      statut: "cloture",
      dateDebut: "2024-10-01",
      dateFinPrevue: "2024-11-01",
      dateFin: "2024-11-01",
      budgetPrevisionnel: -0.31,
      description: "Import PREVISIONNEL.xlsx - onglet 2024-25, ligne 162, categorie couverture.",
      adresse: null
    },
    {
      id: "4cb30f0b-6a93-5ad1-890a-8820e33ca6ae",
      origineImport: "previsionnel",
      clientId: "d34aff0b-6321-5e8b-9f9d-48f9737f7080",
      nom: "Billoin Heuguebart (2023-24)",
      statut: "cloture",
      dateDebut: "2024-09-01",
      dateFinPrevue: "2024-10-01",
      dateFin: "2024-10-01",
      budgetPrevisionnel: 124073,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 37, categorie maison.",
      adresse: null
    },
    {
      id: "6a942a6b-8aa7-55bd-86d7-32133e9e2f15",
      origineImport: "previsionnel",
      clientId: "7d3a2a5e-0182-5e63-b83b-d4f0ffa32ddd",
      nom: "Henry (2023-24)",
      statut: "cloture",
      dateDebut: "2024-09-01",
      dateFinPrevue: "2024-10-01",
      dateFin: "2024-10-01",
      budgetPrevisionnel: 42074.15,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 52, categorie extension.",
      adresse: null
    },
    {
      id: "b0616c1f-d26d-5993-b0e0-a4224c5c7d16",
      origineImport: "previsionnel",
      clientId: "32937092-a38d-5b8c-915e-d851548c7a7e",
      nom: "Selarl Pharmacie Du Val De Seulles (2023-24)",
      statut: "cloture",
      dateDebut: "2024-09-01",
      dateFinPrevue: "2024-10-01",
      dateFin: "2024-10-01",
      budgetPrevisionnel: 2671.2,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 83, categorie charpente.",
      adresse: null
    },
    {
      id: "41efbe92-da47-5901-bc40-2a71685f1051",
      origineImport: "previsionnel",
      clientId: "dc1333ba-f82b-5519-968a-a9769e7be0c3",
      nom: "Tesson (2023-24)",
      statut: "cloture",
      dateDebut: "2024-09-01",
      dateFinPrevue: "2024-10-01",
      dateFin: "2024-10-01",
      budgetPrevisionnel: 2380.21,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 84, categorie charpente.",
      adresse: null
    },
    {
      id: "b92db96b-073f-586f-83ed-d3cb02330e2a",
      origineImport: "previsionnel",
      clientId: "3708e8e8-696f-5ead-8882-b67379ba25b1",
      nom: "CFA Normandie (2023-24)",
      statut: "cloture",
      dateDebut: "2024-09-01",
      dateFinPrevue: "2024-10-01",
      dateFin: "2024-10-01",
      budgetPrevisionnel: 21381,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 85, categorie charpente.",
      adresse: null
    },
    {
      id: "b56a07b0-a7b0-5370-96d6-ffa9c97c9ff0",
      origineImport: "previsionnel",
      clientId: "1e9cffaa-92a1-58d4-ab23-2d1cd71c8ef5",
      nom: "Alto (2023-24)",
      statut: "cloture",
      dateDebut: "2024-09-01",
      dateFinPrevue: "2024-10-01",
      dateFin: "2024-10-01",
      budgetPrevisionnel: 11515.44,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 86, categorie charpente.",
      adresse: null
    },
    {
      id: "82464561-84e2-5500-bc65-6eeb6f4940b3",
      origineImport: "previsionnel",
      clientId: "3ac06c50-5b0d-59a6-aa1e-4f08b27a2bbe",
      nom: "Desloges (2023-24)",
      statut: "cloture",
      dateDebut: "2024-09-01",
      dateFinPrevue: "2024-10-01",
      dateFin: "2024-10-01",
      budgetPrevisionnel: 13930.03,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 106, categorie divers.",
      adresse: null
    },
    {
      id: "f6e8febd-5bdd-51f8-87c4-e0ec0ebdf832",
      origineImport: "previsionnel",
      clientId: "27d890b9-ec3f-5714-bf0b-970bf9f6b48f",
      nom: "Parisotto (2023-24)",
      statut: "cloture",
      dateDebut: "2024-08-01",
      dateFinPrevue: "2024-10-01",
      dateFin: "2024-10-01",
      budgetPrevisionnel: 33961,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 61, categorie extension.",
      adresse: null
    },
    {
      id: "3ab24089-9a37-58ee-97f8-3bded2fb857e",
      origineImport: "previsionnel",
      clientId: "ae255225-2ac0-5319-8f58-226d5a9b2f25",
      nom: "Binet (2023-24)",
      statut: "cloture",
      dateDebut: "2024-07-01",
      dateFinPrevue: "2024-10-01",
      dateFin: "2024-10-01",
      budgetPrevisionnel: 22549.76,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 60, categorie extension.",
      adresse: null
    },
    {
      id: "61eaddf1-764e-5ac9-acbe-30967ee9f27a",
      origineImport: "previsionnel",
      clientId: "233844d5-b016-52b8-9b80-20b920b0a10f",
      nom: "Sci La Moinerie (2023-24)",
      statut: "cloture",
      dateDebut: "2024-07-01",
      dateFinPrevue: "2024-08-01",
      dateFin: "2024-08-01",
      budgetPrevisionnel: 10000,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 134, categorie couverture.",
      adresse: null
    },
    {
      id: "4f646bd4-1b4d-5fc5-ad53-19559c9f3c0c",
      origineImport: "previsionnel",
      clientId: "72d9b697-d026-5128-b1a9-a406e923fbce",
      nom: "Sas Lpcr (2023-24)",
      statut: "cloture",
      dateDebut: "2024-07-01",
      dateFinPrevue: "2024-10-01",
      dateFin: "2024-10-01",
      budgetPrevisionnel: 13651.52,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 136, categorie couverture.",
      adresse: null
    },
    {
      id: "595339ec-da23-52ce-88fa-b12f9c9e6714",
      origineImport: "previsionnel",
      clientId: "5d4845d0-cddb-5696-86d4-95d3ff9b902d",
      nom: "Savary 2 (2023-24)",
      statut: "cloture",
      dateDebut: "2024-06-01",
      dateFinPrevue: "2024-10-01",
      dateFin: "2024-10-01",
      budgetPrevisionnel: 136000.38,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 79, categorie extension.",
      adresse: null
    },
    {
      id: "55c4d5bd-244c-5046-a8c0-5063986225a3",
      origineImport: "previsionnel",
      clientId: "147ef48e-0ea8-54e6-ad9a-c2aecbc42ac2",
      nom: "Bonneau (2023-24)",
      statut: "cloture",
      dateDebut: "2024-05-01",
      dateFinPrevue: "2024-08-01",
      dateFin: "2024-08-01",
      budgetPrevisionnel: 117477,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 55, categorie extension.",
      adresse: null
    },
    {
      id: "ca059c8e-9b24-518d-a3b7-b2efd766ad6b",
      origineImport: "previsionnel",
      clientId: "8956670b-c475-5b62-9b7c-a4d1ce22f58a",
      nom: "Gue (2023-24)",
      statut: "cloture",
      dateDebut: "2024-05-01",
      dateFinPrevue: "2024-09-01",
      dateFin: "2024-09-01",
      budgetPrevisionnel: 38994.55,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 62, categorie extension.",
      adresse: null
    },
    {
      id: "f75f8829-01af-571e-8289-18739a78d348",
      origineImport: "previsionnel",
      clientId: "a169bb47-3b58-5553-a6f3-6195e88985e2",
      nom: "Mairie De Combray (2023-24)",
      statut: "cloture",
      dateDebut: "2024-05-01",
      dateFinPrevue: "2024-06-01",
      dateFin: "2024-06-01",
      budgetPrevisionnel: 98.03,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 101, categorie divers.",
      adresse: null
    },
    {
      id: "12be3a0f-a8f2-516f-8fcf-3db7ac1a4b5d",
      origineImport: "previsionnel",
      clientId: "4e861075-e1d3-5a43-8658-6d5faa7a75cd",
      nom: "Huber (2023-24)",
      statut: "cloture",
      dateDebut: "2024-05-01",
      dateFinPrevue: "2024-06-01",
      dateFin: "2024-06-01",
      budgetPrevisionnel: 1997.04,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 102, categorie divers.",
      adresse: null
    },
    {
      id: "30dc48b2-2aa4-511e-a8b2-196ce7e6b10f",
      origineImport: "previsionnel",
      clientId: "c3137e26-a5eb-5ce8-b8fc-87bb65d6c90f",
      nom: "Garnier (2023-24)",
      statut: "cloture",
      dateDebut: "2024-05-01",
      dateFinPrevue: "2024-06-01",
      dateFin: "2024-06-01",
      budgetPrevisionnel: 699.14,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 103, categorie divers.",
      adresse: null
    },
    {
      id: "0c2f70ef-b9e0-5466-a55b-6953f8b19e14",
      origineImport: "previsionnel",
      clientId: "280a0d4f-29d2-59b0-aced-b6900665b59a",
      nom: "Caen Couvertures (2023-24)",
      statut: "cloture",
      dateDebut: "2024-05-01",
      dateFinPrevue: "2024-06-01",
      dateFin: "2024-06-01",
      budgetPrevisionnel: 3397.29,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 137, categorie couverture.",
      adresse: null
    },
    {
      id: "7abeecab-6f23-5b99-b59b-0c5deddc2e7c",
      origineImport: "previsionnel",
      clientId: "280a0d4f-29d2-59b0-aced-b6900665b59a",
      nom: "Caen Couvertures (2023-24)",
      statut: "cloture",
      dateDebut: "2024-05-01",
      dateFinPrevue: "2024-06-01",
      dateFin: "2024-06-01",
      budgetPrevisionnel: 6993,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 138, categorie couverture.",
      adresse: null
    },
    {
      id: "f42d8685-0852-5c84-9324-dc1c1791f73f",
      origineImport: "previsionnel",
      clientId: "8ad958ab-e84e-53b1-9fd4-452671f41b5a",
      nom: "Renaude (2023-24)",
      statut: "cloture",
      dateDebut: "2024-04-01",
      dateFinPrevue: "2024-09-01",
      dateFin: "2024-09-01",
      budgetPrevisionnel: 101895,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 36, categorie maison.",
      adresse: null
    },
    {
      id: "a92596b1-0580-5946-83c0-a8a8b1ad838f",
      origineImport: "previsionnel",
      clientId: "b7478a5b-0c18-5d9b-b2a7-0144e80f42f0",
      nom: "Mairie de BSL (2023-24)",
      statut: "cloture",
      dateDebut: "2024-04-01",
      dateFinPrevue: "2024-06-01",
      dateFin: "2024-06-01",
      budgetPrevisionnel: 37210.39,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 87, categorie charpente.",
      adresse: null
    },
    {
      id: "8ac046b0-c224-54c4-95e5-7321ed35c744",
      origineImport: "previsionnel",
      clientId: "e588261d-0e3c-54d6-bd08-a06f2abb45bf",
      nom: "Sci Jpblb (2023-24)",
      statut: "cloture",
      dateDebut: "2024-04-01",
      dateFinPrevue: "2024-05-01",
      dateFin: "2024-05-01",
      budgetPrevisionnel: 10604.15,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 107, categorie divers.",
      adresse: null
    },
    {
      id: "0e446f15-aaf5-512b-abb8-ee0160b66b69",
      origineImport: "previsionnel",
      clientId: "55d7c01e-9fcf-50c6-aa41-8a6bc553ca8b",
      nom: "Clement (2023-24)",
      statut: "cloture",
      dateDebut: "2024-04-01",
      dateFinPrevue: "2024-06-01",
      dateFin: "2024-06-01",
      budgetPrevisionnel: 4125,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 108, categorie divers.",
      adresse: null
    },
    {
      id: "5fbf0e65-743c-5edc-9a18-f6d33b1c16c0",
      origineImport: "previsionnel",
      clientId: "f0bda559-0347-5329-8ad0-ff9290c99125",
      nom: "Grange (2023-24)",
      statut: "cloture",
      dateDebut: "2024-03-01",
      dateFinPrevue: "2024-10-01",
      dateFin: "2024-10-01",
      budgetPrevisionnel: 160352.12,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 38, categorie maison.",
      adresse: null
    },
    {
      id: "e350092b-760f-568b-a460-899937d92bdb",
      origineImport: "previsionnel",
      clientId: "d1be87b6-38f1-53a9-a8cd-1fa532ae55bb",
      nom: "Schiel (2023-24)",
      statut: "cloture",
      dateDebut: "2024-03-01",
      dateFinPrevue: "2024-04-01",
      dateFin: "2024-04-01",
      budgetPrevisionnel: 972.88,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 45, categorie maison.",
      adresse: null
    },
    {
      id: "3cc15c29-d554-5ada-b320-173757f23169",
      origineImport: "previsionnel",
      clientId: "598238f3-e7b8-56aa-a43b-0b7b50b4ebd3",
      nom: "Chatelet (2023-24)",
      statut: "cloture",
      dateDebut: "2024-03-01",
      dateFinPrevue: "2024-08-01",
      dateFin: "2024-08-01",
      budgetPrevisionnel: 95064,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 88, categorie charpente.",
      adresse: null
    },
    {
      id: "d97f0a88-1d94-5395-88ed-fb21edc66e6f",
      origineImport: "previsionnel",
      clientId: "4fe10e46-7696-504a-acd8-60c61d4bf813",
      nom: "Parkour (2023-24)",
      statut: "cloture",
      dateDebut: "2024-03-01",
      dateFinPrevue: "2024-04-01",
      dateFin: "2024-04-01",
      budgetPrevisionnel: 33973.2,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 109, categorie divers.",
      adresse: null
    },
    {
      id: "0065b12c-38a1-5add-9bfa-a705642202fe",
      origineImport: "previsionnel",
      clientId: "01e90885-b7d1-5f2d-8bf6-64013b058cf6",
      nom: "Bergar (2023-24)",
      statut: "cloture",
      dateDebut: "2024-02-01",
      dateFinPrevue: "2024-10-01",
      dateFin: "2024-10-01",
      budgetPrevisionnel: 257744.9,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 40, categorie maison.",
      adresse: null
    },
    {
      id: "013f193a-096a-50f4-8af7-1f7488b2cdc3",
      origineImport: "previsionnel",
      clientId: "f476fa77-60da-5ebf-bfce-f7be309d7d86",
      nom: "Gabard (2023-24)",
      statut: "cloture",
      dateDebut: "2024-02-01",
      dateFinPrevue: "2024-03-01",
      dateFin: "2024-03-01",
      budgetPrevisionnel: 3811.58,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 89, categorie charpente.",
      adresse: null
    },
    {
      id: "787fbe17-8ba6-551c-b839-cc783bbfdf4b",
      origineImport: "previsionnel",
      clientId: "dc1333ba-f82b-5519-968a-a9769e7be0c3",
      nom: "Tesson (2023-24)",
      statut: "cloture",
      dateDebut: "2024-01-01",
      dateFinPrevue: "2024-02-01",
      dateFin: "2024-02-01",
      budgetPrevisionnel: 17500,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 64, categorie extension.",
      adresse: null
    },
    {
      id: "e82d7016-3df3-530d-8e5e-7f6c559cde93",
      origineImport: "previsionnel",
      clientId: "4af50642-1dd8-5c16-984d-339203432fb9",
      nom: "Lemoine (2023-24)",
      statut: "cloture",
      dateDebut: "2024-01-01",
      dateFinPrevue: "2024-03-01",
      dateFin: "2024-03-01",
      budgetPrevisionnel: 493.95,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 69, categorie extension.",
      adresse: null
    },
    {
      id: "9b110431-2fb6-594a-bc3f-f6f00fc479ff",
      origineImport: "previsionnel",
      clientId: "5a00bc9a-f1d7-553e-aea4-7192f70b00c3",
      nom: "MARIE Aurelien (2023-24)",
      statut: "cloture",
      dateDebut: "2024-01-01",
      dateFinPrevue: "2024-03-01",
      dateFin: "2024-03-01",
      budgetPrevisionnel: 856.57,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 92, categorie charpente.",
      adresse: null
    },
    {
      id: "3fc640af-78db-5a80-8291-9e6b64bfec75",
      origineImport: "previsionnel",
      clientId: "1f1625eb-18e3-518d-a3b6-29709b7d7101",
      nom: "Saison (2023-24)",
      statut: "cloture",
      dateDebut: "2024-01-01",
      dateFinPrevue: "2024-02-01",
      dateFin: "2024-02-01",
      budgetPrevisionnel: 22497,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 96, categorie charpente.",
      adresse: null
    },
    {
      id: "64b6cb65-652c-5355-a8b6-f8763c4b65f2",
      origineImport: "previsionnel",
      clientId: "b90c4718-3efb-5a67-a955-ebcc38dc9a44",
      nom: "Ferraro (2023-24)",
      statut: "cloture",
      dateDebut: "2024-01-01",
      dateFinPrevue: "2024-02-01",
      dateFin: "2024-02-01",
      budgetPrevisionnel: 13337.39,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 139, categorie couverture.",
      adresse: null
    },
    {
      id: "edbe8f24-029e-5238-bf0e-b86bfb73afd5",
      origineImport: "previsionnel",
      clientId: "a470802a-4281-5c13-9e28-9c1200f6006e",
      nom: "Samson (2023-24)",
      statut: "cloture",
      dateDebut: "2023-12-01",
      dateFinPrevue: "2024-08-01",
      dateFin: "2024-08-01",
      budgetPrevisionnel: 137336,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 44, categorie maison.",
      adresse: null
    },
    {
      id: "b92b6368-a027-5bd5-87ca-755274e9bf4f",
      origineImport: "previsionnel",
      clientId: "90317170-bc7f-54f2-b585-68e02446d940",
      nom: "Claparede (2023-24)",
      statut: "cloture",
      dateDebut: "2023-12-01",
      dateFinPrevue: "2024-01-01",
      dateFin: "2024-01-01",
      budgetPrevisionnel: 7545,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 68, categorie extension.",
      adresse: null
    },
    {
      id: "c66e79c1-96cb-5777-8db4-ac6d7204a35e",
      origineImport: "previsionnel",
      clientId: "3a9f655f-fed3-5b96-98e3-2548e05d074d",
      nom: "Gauguin (2023-24)",
      statut: "cloture",
      dateDebut: "2023-12-01",
      dateFinPrevue: "2024-04-01",
      dateFin: "2024-04-01",
      budgetPrevisionnel: 51775.97,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 77, categorie extension.",
      adresse: null
    },
    {
      id: "3bc5c5fb-821e-5f67-b389-3a8698020f52",
      origineImport: "previsionnel",
      clientId: "8172091c-eba8-54da-a1ce-931cc792a482",
      nom: "Delentecommelchal (2023-24)",
      statut: "cloture",
      dateDebut: "2023-12-01",
      dateFinPrevue: "2024-02-01",
      dateFin: "2024-02-01",
      budgetPrevisionnel: 12484,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 126, categorie renovation.",
      adresse: null
    },
    {
      id: "b58b18ca-afd4-554e-9d7f-81ac3654ec70",
      origineImport: "previsionnel",
      clientId: "34f2886d-9e7b-5d10-9539-57aae281d063",
      nom: "Bourget/Popovic (2023-24)",
      statut: "cloture",
      dateDebut: "2023-11-01",
      dateFinPrevue: "2024-08-01",
      dateFin: "2024-08-01",
      budgetPrevisionnel: 160722.22,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 43, categorie maison.",
      adresse: null
    },
    {
      id: "7481a4fa-45fd-5b68-9f12-3ef99460f6c8",
      origineImport: "previsionnel",
      clientId: "6f852fde-70c3-5db6-9f9d-c0acb9ac3803",
      nom: "Le Tanneur (2023-24)",
      statut: "cloture",
      dateDebut: "2023-11-01",
      dateFinPrevue: "2024-02-01",
      dateFin: "2024-02-01",
      budgetPrevisionnel: 46206,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 90, categorie charpente.",
      adresse: null
    },
    {
      id: "9ec9d0ee-4239-5533-98a3-12ac22dec7d1",
      origineImport: "previsionnel",
      clientId: "6d516d8c-9884-5233-9556-6d4f9d9f55ff",
      nom: "Lockquest (2023-24)",
      statut: "cloture",
      dateDebut: "2023-11-01",
      dateFinPrevue: "2023-12-01",
      dateFin: "2023-12-01",
      budgetPrevisionnel: 15674,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 93, categorie charpente.",
      adresse: null
    },
    {
      id: "3356b03a-82ff-5649-afc1-994d906e39c5",
      origineImport: "previsionnel",
      clientId: "40e45dd7-df52-52e4-808b-a3137517ab35",
      nom: "Ferraro Terrasse (2023-24)",
      statut: "cloture",
      dateDebut: "2023-11-01",
      dateFinPrevue: "2023-12-01",
      dateFin: "2023-12-01",
      budgetPrevisionnel: 5000,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 112, categorie divers.",
      adresse: null
    },
    {
      id: "e2762463-aa7f-5df2-8bc1-1e07f7d6309d",
      origineImport: "previsionnel",
      clientId: "8c846b99-322c-51d4-816b-d46dac3b83f9",
      nom: "Froger (2023-24)",
      statut: "cloture",
      dateDebut: "2023-11-01",
      dateFinPrevue: "2024-02-01",
      dateFin: "2024-02-01",
      budgetPrevisionnel: 8481.41,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 113, categorie divers.",
      adresse: null
    },
    {
      id: "63bf6157-079f-5968-a229-174219235845",
      origineImport: "previsionnel",
      clientId: "4ea28230-791d-5705-9f40-c0d13c719fdf",
      nom: "Dupont (2023-24)",
      statut: "cloture",
      dateDebut: "2023-11-01",
      dateFinPrevue: "2023-12-01",
      dateFin: "2023-12-01",
      budgetPrevisionnel: 2164.47,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 115, categorie divers.",
      adresse: null
    },
    {
      id: "7039af53-06c0-5042-8dc5-0e383a49ac96",
      origineImport: "previsionnel",
      clientId: "4483f8fd-2f95-5cb1-9bc3-41407eb04270",
      nom: "Morival (2023-24)",
      statut: "cloture",
      dateDebut: "2023-10-01",
      dateFinPrevue: "2023-11-01",
      dateFin: "2023-11-01",
      budgetPrevisionnel: 65272.47,
      description: "Import PREVISIONNEL.xlsx - onglet 2023-24, ligne 24, categorie maison.",
      adresse: null
    }
  ])
}
