mutation @transaction {
  chantiers009: chantier_upsertMany(data: [
    {
      id: "7af0d3b4-1776-5351-8db1-303ded93b339",
      clientId: "4cf828fd-51a0-5594-a4ff-7d7d2e9f4654",
      nom: "Laine Jamet (2021-22)",
      statut: "cloture",
      dateDebut: "2021-10-01",
      dateFinPrevue: "2021-11-01",
      dateFin: "2021-11-01",
      budgetPrevisionnel: 48991.13,
      description: "Import PREVISIONNEL.xlsx - onglet 2021-22, ligne 29, categorie non_classe.",
      adresse: null
    },
    {
      id: "8d15fa4e-e586-5a09-b9ad-b7f1991acdc0",
      clientId: "4506245d-64e0-5f52-b41b-59b1532353c8",
      nom: "Mairie de perrière 2 (2021-22)",
      statut: "cloture",
      dateDebut: "2021-10-01",
      dateFinPrevue: "2021-11-01",
      dateFin: "2021-11-01",
      budgetPrevisionnel: 9393.34,
      description: "Import PREVISIONNEL.xlsx - onglet 2021-22, ligne 30, categorie non_classe.",
      adresse: null
    },
    {
      id: "05e43ec0-9870-5376-9335-e8596f13b05f",
      clientId: "db2ce1d1-8b2f-5fdd-9e20-4388295072a2",
      nom: "Saussaye (2021-22)",
      statut: "cloture",
      dateDebut: "2021-10-01",
      dateFinPrevue: "2021-11-01",
      dateFin: "2021-11-01",
      budgetPrevisionnel: 64547,
      description: "Import PREVISIONNEL.xlsx - onglet 2021-22, ligne 34, categorie non_classe.",
      adresse: null
    },
    {
      id: "ec460718-a37c-5c44-baad-de76916e8737",
      clientId: "65573c0d-ad78-59f0-a2d2-0bd4bd0054e6",
      nom: "Hervieux (2021-22)",
      statut: "cloture",
      dateDebut: "2021-10-01",
      dateFinPrevue: "2021-11-01",
      dateFin: "2021-11-01",
      budgetPrevisionnel: 23000,
      description: "Import PREVISIONNEL.xlsx - onglet 2021-22, ligne 35, categorie non_classe.",
      adresse: null
    },
    {
      id: "41d34247-002a-59b3-bb3d-99057a699f1c",
      clientId: "90317170-bc7f-54f2-b585-68e02446d940",
      nom: "Claparede (2021-22)",
      statut: "cloture",
      dateDebut: "2021-10-01",
      dateFinPrevue: "2021-11-01",
      dateFin: "2021-11-01",
      budgetPrevisionnel: 22650.26,
      description: "Import PREVISIONNEL.xlsx - onglet 2021-22, ligne 37, categorie non_classe.",
      adresse: null
    },
    {
      id: "758c4f6a-3f9d-50ef-a94c-4e6e3cbb66c2",
      clientId: "615b36fc-c736-5f7b-9bf8-c0476587aa69",
      nom: "Jamin (2021-22)",
      statut: "cloture",
      dateDebut: "2021-10-01",
      dateFinPrevue: "2021-11-01",
      dateFin: "2021-11-01",
      budgetPrevisionnel: 31728,
      description: "Import PREVISIONNEL.xlsx - onglet 2021-22, ligne 41, categorie non_classe.",
      adresse: null
    },
    {
      id: "bf0080c5-bacf-501e-a715-e8154e998879",
      clientId: "2b4b1e97-ecd0-57cd-9385-913f5954b4e5",
      nom: "Amram (2021-22)",
      statut: "cloture",
      dateDebut: "2021-10-01",
      dateFinPrevue: "2021-11-01",
      dateFin: "2021-11-01",
      budgetPrevisionnel: 22500,
      description: "Import PREVISIONNEL.xlsx - onglet 2021-22, ligne 50, categorie non_classe.",
      adresse: null
    },
    {
      id: "1c078be6-b494-5bf4-ba03-ec85b0c98203",
      clientId: "8c680e3b-1217-59fb-8e66-bcf60003c604",
      nom: "Lecoeur (2021-22)",
      statut: "cloture",
      dateDebut: "2021-10-01",
      dateFinPrevue: "2021-11-01",
      dateFin: "2021-11-01",
      budgetPrevisionnel: 54260,
      description: "Import PREVISIONNEL.xlsx - onglet 2021-22, ligne 55, categorie non_classe.",
      adresse: null
    },
    {
      id: "6565290a-4bcc-5054-978c-dad61304f4e0",
      clientId: "5361eb1e-c81f-50b1-b490-ad7aa78a6535",
      nom: "Lefrancois (2021-22)",
      statut: "cloture",
      dateDebut: "2021-10-01",
      dateFinPrevue: "2021-11-01",
      dateFin: "2021-11-01",
      budgetPrevisionnel: 14244.88,
      description: "Import PREVISIONNEL.xlsx - onglet 2021-22, ligne 60, categorie non_classe.",
      adresse: null
    },
    {
      id: "27e65e9f-066c-5804-83e4-96d5d553a623",
      clientId: "36cefc54-f49f-54c3-8346-9d585b4e7069",
      nom: "Meuriot (2021-22)",
      statut: "cloture",
      dateDebut: "2021-10-01",
      dateFinPrevue: "2021-11-01",
      dateFin: "2021-11-01",
      budgetPrevisionnel: 92777,
      description: "Import PREVISIONNEL.xlsx - onglet 2021-22, ligne 61, categorie non_classe.",
      adresse: null
    },
    {
      id: "ec8524e6-dccc-51b3-a354-eacca1183f00",
      clientId: "e6e7f6ad-13ea-5769-af23-bf90446b5a86",
      nom: "Adb Treviers (2021-22)",
      statut: "cloture",
      dateDebut: "2021-10-01",
      dateFinPrevue: "2021-11-01",
      dateFin: "2021-11-01",
      budgetPrevisionnel: 149437,
      description: "Import PREVISIONNEL.xlsx - onglet 2021-22, ligne 72, categorie non_classe.",
      adresse: null
    },
    {
      id: "8d9fe417-c85c-5ba5-b7ee-701904688f9b",
      clientId: "666e814d-5d2c-5363-98e2-64fed35851a9",
      nom: "Zaghbouni (2021-22)",
      statut: "cloture",
      dateDebut: "2021-10-01",
      dateFinPrevue: "2021-11-01",
      dateFin: "2021-11-01",
      budgetPrevisionnel: 117072,
      description: "Import PREVISIONNEL.xlsx - onglet 2021-22, ligne 74, categorie non_classe.",
      adresse: null
    },
    {
      id: "50a00979-d762-5b7e-81e2-3c20a96198ef",
      clientId: "68c8c60b-e9a0-58ef-b908-a26294ff0d5a",
      nom: "Jager (2021-22)",
      statut: "cloture",
      dateDebut: "2021-10-01",
      dateFinPrevue: "2022-02-01",
      dateFin: "2022-02-01",
      budgetPrevisionnel: 67013.93,
      description: "Import PREVISIONNEL.xlsx - onglet 2021-22, ligne 82, categorie non_classe.",
      adresse: null
    },
    {
      id: "d1e2332d-37cf-5b6d-978e-aff8dd39d011",
      clientId: "5b46c239-8469-518f-ae4b-6f14b3b0ff84",
      nom: "Francois (2021-22)",
      statut: "cloture",
      dateDebut: "2021-10-01",
      dateFinPrevue: "2022-01-01",
      dateFin: "2022-01-01",
      budgetPrevisionnel: 39729,
      description: "Import PREVISIONNEL.xlsx - onglet 2021-22, ligne 84, categorie non_classe.",
      adresse: null
    },
    {
      id: "a35dfdf7-566e-5076-a653-10c5275dfa48",
      clientId: "3e2f4959-612f-549e-909c-72d85381f0ad",
      nom: "Duchenne (2021-22)",
      statut: "cloture",
      dateDebut: "2021-10-01",
      dateFinPrevue: "2022-02-01",
      dateFin: "2022-02-01",
      budgetPrevisionnel: 21285,
      description: "Import PREVISIONNEL.xlsx - onglet 2021-22, ligne 89, categorie non_classe.",
      adresse: null
    },
    {
      id: "f58314bd-1099-5b0b-9ccf-e108c87eb3d6",
      clientId: "f0c1a030-e3ee-5d64-9ffc-53a083430611",
      nom: "Chatelin (2021-22)",
      statut: "cloture",
      dateDebut: "2021-10-01",
      dateFinPrevue: "2022-03-01",
      dateFin: "2022-03-01",
      budgetPrevisionnel: 23737,
      description: "Import PREVISIONNEL.xlsx - onglet 2021-22, ligne 92, categorie non_classe.",
      adresse: null
    },
    {
      id: "7c6294f4-f8f8-56af-a53f-24342a24ee1a",
      clientId: "c099fdc8-1666-518f-990e-e08dc9c55925",
      nom: "Gerbault - Ibanescu (2021-22)",
      statut: "cloture",
      dateDebut: "2021-10-01",
      dateFinPrevue: "2022-03-01",
      dateFin: "2022-03-01",
      budgetPrevisionnel: 46081,
      description: "Import PREVISIONNEL.xlsx - onglet 2021-22, ligne 94, categorie non_classe.",
      adresse: null
    },
    {
      id: "3cb25405-7197-58d6-9dbf-0d6d57fee6dd",
      clientId: "581f81d8-428d-5a57-966e-079bebff1b9b",
      nom: "Lecleir (2021-22)",
      statut: "cloture",
      dateDebut: "2021-10-01",
      dateFinPrevue: "2021-11-01",
      dateFin: "2021-11-01",
      budgetPrevisionnel: 5962.67,
      description: "Import PREVISIONNEL.xlsx - onglet 2021-22, ligne 96, categorie non_classe.",
      adresse: null
    },
    {
      id: "bd1adada-2063-5a94-9449-e13ac601de18",
      clientId: "8cb258cc-165a-5957-96a2-3a45698322f9",
      nom: "Clet Caron (2021-22)",
      statut: "cloture",
      dateDebut: "2021-10-01",
      dateFinPrevue: "2022-01-01",
      dateFin: "2022-01-01",
      budgetPrevisionnel: 21247.69,
      description: "Import PREVISIONNEL.xlsx - onglet 2021-22, ligne 98, categorie non_classe.",
      adresse: null
    },
    {
      id: "298a6b1e-271d-54d7-8bb7-ae46e3688985",
      clientId: "1ff0e5ab-c97d-515a-a7c8-c9b3b087ac47",
      nom: "Guedon (2021-22)",
      statut: "cloture",
      dateDebut: "2021-10-01",
      dateFinPrevue: "2022-03-01",
      dateFin: "2022-03-01",
      budgetPrevisionnel: 41376,
      description: "Import PREVISIONNEL.xlsx - onglet 2021-22, ligne 102, categorie non_classe.",
      adresse: null
    },
    {
      id: "afd6133d-593c-5a3e-96ef-3b9ec9c92107",
      clientId: "ebfe7e0a-d277-567c-afa7-80b47c9246f7",
      nom: "GEZE extension (2021-22)",
      statut: "cloture",
      dateDebut: "2021-10-01",
      dateFinPrevue: "2021-11-01",
      dateFin: "2021-11-01",
      budgetPrevisionnel: -0.31,
      description: "Import PREVISIONNEL.xlsx - onglet 2021-22, ligne 111, categorie non_classe.",
      adresse: null
    },
    {
      id: "b1030741-20d6-53ea-9a05-861d8c873106",
      clientId: "68c8c60b-e9a0-58ef-b908-a26294ff0d5a",
      nom: "Jager (2020-21)",
      statut: "cloture",
      dateDebut: "2021-09-01",
      dateFinPrevue: "2021-10-01",
      dateFin: "2021-10-01",
      budgetPrevisionnel: 81301.93,
      description: "Import PREVISIONNEL.xlsx - onglet 2020-21, ligne 20, categorie non_classe.",
      adresse: null
    },
    {
      id: "48ffb842-ec4b-5ce5-be00-515504ec44e0",
      clientId: "5b46c239-8469-518f-ae4b-6f14b3b0ff84",
      nom: "Francois (2020-21)",
      statut: "cloture",
      dateDebut: "2021-09-01",
      dateFinPrevue: "2021-10-01",
      dateFin: "2021-10-01",
      budgetPrevisionnel: 52084,
      description: "Import PREVISIONNEL.xlsx - onglet 2020-21, ligne 22, categorie non_classe.",
      adresse: null
    },
    {
      id: "cd45e37e-4d14-5938-8bc3-0fc41fe39224",
      clientId: "3e2f4959-612f-549e-909c-72d85381f0ad",
      nom: "Duchenne (2020-21)",
      statut: "cloture",
      dateDebut: "2021-09-01",
      dateFinPrevue: "2021-10-01",
      dateFin: "2021-10-01",
      budgetPrevisionnel: 21204,
      description: "Import PREVISIONNEL.xlsx - onglet 2020-21, ligne 27, categorie non_classe.",
      adresse: null
    },
    {
      id: "9a273e92-eb25-552a-afa0-c3cee53780ab",
      clientId: "f0c1a030-e3ee-5d64-9ffc-53a083430611",
      nom: "Chatelin (2020-21)",
      statut: "cloture",
      dateDebut: "2021-09-01",
      dateFinPrevue: "2021-10-01",
      dateFin: "2021-10-01",
      budgetPrevisionnel: 31053,
      description: "Import PREVISIONNEL.xlsx - onglet 2020-21, ligne 32, categorie non_classe.",
      adresse: null
    },
    {
      id: "c912c48e-4fd5-55ad-ad1b-c62aac12d02c",
      clientId: "ac6665dd-c1d2-5915-a74c-9bfc68653f19",
      nom: "Huard (2020-21)",
      statut: "cloture",
      dateDebut: "2021-09-01",
      dateFinPrevue: "2021-10-01",
      dateFin: "2021-10-01",
      budgetPrevisionnel: 36011,
      description: "Import PREVISIONNEL.xlsx - onglet 2020-21, ligne 42, categorie non_classe.",
      adresse: null
    },
    {
      id: "910bffcd-65e3-5978-b279-0f2914003a27",
      clientId: "6d818252-52be-54c0-bc37-dda593b10301",
      nom: "FOUQUES mam bassene (2020-21)",
      statut: "cloture",
      dateDebut: "2021-08-01",
      dateFinPrevue: "2021-09-01",
      dateFin: "2021-09-01",
      budgetPrevisionnel: 4328,
      description: "Import PREVISIONNEL.xlsx - onglet 2020-21, ligne 30, categorie non_classe.",
      adresse: null
    },
    {
      id: "dac94081-1cd9-5f6c-8e6b-833a246687c0",
      clientId: "4af50642-1dd8-5c16-984d-339203432fb9",
      nom: "Lemoine (2020-21)",
      statut: "cloture",
      dateDebut: "2021-07-01",
      dateFinPrevue: "2021-09-01",
      dateFin: "2021-09-01",
      budgetPrevisionnel: 42665,
      description: "Import PREVISIONNEL.xlsx - onglet 2020-21, ligne 21, categorie non_classe.",
      adresse: null
    },
    {
      id: "51cdf6b7-107e-5fe6-bf07-c8c7c5fc33d5",
      clientId: "c099fdc8-1666-518f-990e-e08dc9c55925",
      nom: "Gerbault - Ibanescu (2020-21)",
      statut: "cloture",
      dateDebut: "2021-07-01",
      dateFinPrevue: "2021-10-01",
      dateFin: "2021-10-01",
      budgetPrevisionnel: 103994,
      description: "Import PREVISIONNEL.xlsx - onglet 2020-21, ligne 35, categorie non_classe.",
      adresse: null
    },
    {
      id: "b0323aa5-5fcf-5b53-ab7f-c0d7b0aa22c7",
      clientId: "78785387-2436-59d8-b8f5-1095d76e57c1",
      nom: "Cuvigny (2020-21)",
      statut: "cloture",
      dateDebut: "2021-06-01",
      dateFinPrevue: "2021-09-01",
      dateFin: "2021-09-01",
      budgetPrevisionnel: 18000,
      description: "Import PREVISIONNEL.xlsx - onglet 2020-21, ligne 23, categorie non_classe.",
      adresse: null
    },
    {
      id: "641fd23d-ac54-5cd8-8536-3ea588662376",
      clientId: "864d95a4-f088-5b8f-8b6b-b67c8aec9542",
      nom: "Bassiere (2020-21)",
      statut: "cloture",
      dateDebut: "2021-06-01",
      dateFinPrevue: "2021-09-01",
      dateFin: "2021-09-01",
      budgetPrevisionnel: 25682.67,
      description: "Import PREVISIONNEL.xlsx - onglet 2020-21, ligne 24, categorie non_classe.",
      adresse: null
    },
    {
      id: "a5d01b22-e3ea-5650-ab7d-0c6a45068e04",
      clientId: "a6858f4e-a6d9-5b62-b765-a18d84ddfdbd",
      nom: "Flipo portail (2020-21)",
      statut: "cloture",
      dateDebut: "2021-06-01",
      dateFinPrevue: "2021-07-01",
      dateFin: "2021-07-01",
      budgetPrevisionnel: 1156,
      description: "Import PREVISIONNEL.xlsx - onglet 2020-21, ligne 36, categorie non_classe.",
      adresse: null
    },
    {
      id: "dcdcea0e-5b6d-5a7f-aa58-e71b4104fad4",
      clientId: "581f81d8-428d-5a57-966e-079bebff1b9b",
      nom: "Lecleir (2020-21)",
      statut: "cloture",
      dateDebut: "2021-06-01",
      dateFinPrevue: "2021-08-01",
      dateFin: "2021-08-01",
      budgetPrevisionnel: 29905.67,
      description: "Import PREVISIONNEL.xlsx - onglet 2020-21, ligne 37, categorie non_classe.",
      adresse: null
    },
    {
      id: "c365a382-da0d-5dc3-8397-afd65dd39e01",
      clientId: "22ca2005-4e10-58e5-86e6-8a4b68d1aa32",
      nom: "Poret (2020-21)",
      statut: "cloture",
      dateDebut: "2021-05-01",
      dateFinPrevue: "2021-08-01",
      dateFin: "2021-08-01",
      budgetPrevisionnel: 107534.34,
      description: "Import PREVISIONNEL.xlsx - onglet 2020-21, ligne 38, categorie non_classe.",
      adresse: null
    },
    {
      id: "5c341691-335c-5415-9b01-0cb452404a5d",
      clientId: "b31e6072-27e4-5c6e-8248-267d60fdda30",
      nom: "Thire (2020-21)",
      statut: "cloture",
      dateDebut: "2021-05-01",
      dateFinPrevue: "2021-06-01",
      dateFin: "2021-06-01",
      budgetPrevisionnel: 30000,
      description: "Import PREVISIONNEL.xlsx - onglet 2020-21, ligne 51, categorie non_classe.",
      adresse: null
    },
    {
      id: "2a94a275-d78e-5961-810a-fca7841a9c3a",
      clientId: "78d1bd33-069f-574a-82c0-af1f1a26bea8",
      nom: "Exaequo (2020-21)",
      statut: "cloture",
      dateDebut: "2021-04-01",
      dateFinPrevue: "2021-05-01",
      dateFin: "2021-05-01",
      budgetPrevisionnel: 533.33,
      description: "Import PREVISIONNEL.xlsx - onglet 2020-21, ligne 25, categorie non_classe.",
      adresse: null
    },
    {
      id: "734ca69a-2b19-50da-b991-c22116c065f3",
      clientId: "0ba0b86c-da09-5901-bc7f-a741b8b21ffa",
      nom: "Prevost (2020-21)",
      statut: "cloture",
      dateDebut: "2021-04-01",
      dateFinPrevue: "2021-05-01",
      dateFin: "2021-05-01",
      budgetPrevisionnel: 1821,
      description: "Import PREVISIONNEL.xlsx - onglet 2020-21, ligne 26, categorie non_classe.",
      adresse: null
    },
    {
      id: "e61e6e2a-0a8c-5b80-98a2-57cb9729d0a7",
      clientId: "2e7bdc80-ef0f-56bf-8a77-eff64d2b3622",
      nom: "Raoult (2020-21)",
      statut: "cloture",
      dateDebut: "2021-04-01",
      dateFinPrevue: "2021-07-01",
      dateFin: "2021-07-01",
      budgetPrevisionnel: 6537,
      description: "Import PREVISIONNEL.xlsx - onglet 2020-21, ligne 28, categorie non_classe.",
      adresse: null
    },
    {
      id: "bc2ff2bb-7234-531c-8d81-34deec327601",
      clientId: "829c0cfc-1f18-5026-a8ec-7542d6c30e02",
      nom: "Bretagne (2020-21)",
      statut: "cloture",
      dateDebut: "2021-04-01",
      dateFinPrevue: "2021-08-01",
      dateFin: "2021-08-01",
      budgetPrevisionnel: 25597.21,
      description: "Import PREVISIONNEL.xlsx - onglet 2020-21, ligne 34, categorie non_classe.",
      adresse: null
    },
    {
      id: "c10f5b2c-2b45-593a-b0d0-5a390ccce58d",
      clientId: "8cb258cc-165a-5957-96a2-3a45698322f9",
      nom: "Clet Caron (2020-21)",
      statut: "cloture",
      dateDebut: "2021-04-01",
      dateFinPrevue: "2021-10-01",
      dateFin: "2021-10-01",
      budgetPrevisionnel: 176738.45,
      description: "Import PREVISIONNEL.xlsx - onglet 2020-21, ligne 39, categorie non_classe.",
      adresse: null
    },
    {
      id: "f4f2f40f-59fa-5123-993e-d4ab9f3e014e",
      clientId: "8522625e-f629-524d-b005-fe54bdbe7b1e",
      nom: "Bicart (2020-21)",
      statut: "cloture",
      dateDebut: "2021-04-01",
      dateFinPrevue: "2021-05-01",
      dateFin: "2021-05-01",
      budgetPrevisionnel: 7093,
      description: "Import PREVISIONNEL.xlsx - onglet 2020-21, ligne 40, categorie non_classe.",
      adresse: null
    },
    {
      id: "bf094597-e62e-58d2-bfcb-8717c323388e",
      clientId: "fb9d0811-9f4e-5fcf-929f-90dc04fc2cfb",
      nom: "Mairie Evrecy (2020-21)",
      statut: "cloture",
      dateDebut: "2021-04-01",
      dateFinPrevue: "2021-05-01",
      dateFin: "2021-05-01",
      budgetPrevisionnel: 8521,
      description: "Import PREVISIONNEL.xlsx - onglet 2020-21, ligne 41, categorie non_classe.",
      adresse: null
    },
    {
      id: "7a425d36-2e98-5337-8a8e-f25ae34487ee",
      clientId: "1ff0e5ab-c97d-515a-a7c8-c9b3b087ac47",
      nom: "Guedon (2020-21)",
      statut: "cloture",
      dateDebut: "2021-04-01",
      dateFinPrevue: "2021-08-01",
      dateFin: "2021-08-01",
      budgetPrevisionnel: 124336,
      description: "Import PREVISIONNEL.xlsx - onglet 2020-21, ligne 43, categorie non_classe.",
      adresse: null
    },
    {
      id: "fec28293-c273-566d-be00-29c60799c06c",
      clientId: "9f1357b8-242f-58c2-be62-919524250275",
      nom: "Bouillet (2020-21)",
      statut: "cloture",
      dateDebut: "2021-04-01",
      dateFinPrevue: "2021-05-01",
      dateFin: "2021-05-01",
      budgetPrevisionnel: 2925,
      description: "Import PREVISIONNEL.xlsx - onglet 2020-21, ligne 45, categorie non_classe.",
      adresse: null
    },
    {
      id: "8d2f528b-25eb-5c90-95fb-b856ad2232c9",
      clientId: "f205a359-f6a3-5239-8793-107b1f17bece",
      nom: "Dumat Matta (2020-21)",
      statut: "cloture",
      dateDebut: "2021-03-01",
      dateFinPrevue: "2021-05-01",
      dateFin: "2021-05-01",
      budgetPrevisionnel: 4018,
      description: "Import PREVISIONNEL.xlsx - onglet 2020-21, ligne 46, categorie non_classe.",
      adresse: null
    },
    {
      id: "b398f30b-1274-55a9-9840-dd4f86da44f2",
      clientId: "39281c5c-38c1-5269-a893-d2f132925ff1",
      nom: "Girard (2020-21)",
      statut: "cloture",
      dateDebut: "2021-03-01",
      dateFinPrevue: "2021-07-01",
      dateFin: "2021-07-01",
      budgetPrevisionnel: 59556.29,
      description: "Import PREVISIONNEL.xlsx - onglet 2020-21, ligne 47, categorie non_classe.",
      adresse: null
    },
    {
      id: "dc7a777d-b641-5357-a4d5-bf65d35d7d96",
      clientId: "cbe22469-53b6-5fef-bf23-bd02fafa48af",
      nom: "Rohrbach (2020-21)",
      statut: "cloture",
      dateDebut: "2021-03-01",
      dateFinPrevue: "2021-05-01",
      dateFin: "2021-05-01",
      budgetPrevisionnel: 1661,
      description: "Import PREVISIONNEL.xlsx - onglet 2020-21, ligne 48, categorie non_classe.",
      adresse: null
    },
    {
      id: "ade37293-8a88-572e-9835-ecc262b0fff7",
      clientId: "fa66c7a3-46ba-5afa-ad24-efc3901de275",
      nom: "Geslin (2020-21)",
      statut: "cloture",
      dateDebut: "2021-03-01",
      dateFinPrevue: "2021-06-01",
      dateFin: "2021-06-01",
      budgetPrevisionnel: 26119,
      description: "Import PREVISIONNEL.xlsx - onglet 2020-21, ligne 49, categorie non_classe.",
      adresse: null
    },
    {
      id: "b7d27bd4-a015-5ee3-8595-71c32b0d86cd",
      clientId: "f20808f8-0a90-5b00-866f-511a3c5f001b",
      nom: "Chaventre (2020-21)",
      statut: "cloture",
      dateDebut: "2021-03-01",
      dateFinPrevue: "2021-04-01",
      dateFin: "2021-04-01",
      budgetPrevisionnel: 1600,
      description: "Import PREVISIONNEL.xlsx - onglet 2020-21, ligne 50, categorie non_classe.",
      adresse: null
    },
    {
      id: "1eabf1c3-434c-5b39-ad25-1237bce4bb2e",
      clientId: "04cd0c16-f405-5948-91a7-d9f0b12dd025",
      nom: "GEZE existant (2020-21)",
      statut: "cloture",
      dateDebut: "2021-03-01",
      dateFinPrevue: "2021-06-01",
      dateFin: "2021-06-01",
      budgetPrevisionnel: 16560.34,
      description: "Import PREVISIONNEL.xlsx - onglet 2020-21, ligne 53, categorie non_classe.",
      adresse: null
    }
  ])
}
