mutation @transaction {
  chantiers011: chantier_upsertMany(data: [
    {
      id: "c860d8ba-78e6-5a56-93e7-9f7bddef6a02",
      clientId: "4f10e1f5-ecc8-5d01-acc2-a2c861a5cccf",
      nom: "CAUCE via joris cenier (2019-20)",
      statut: "cloture",
      dateDebut: "2020-07-01",
      dateFinPrevue: "2020-08-01",
      dateFin: "2020-08-01",
      budgetPrevisionnel: 20274,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 28, categorie non_classe.",
      adresse: null
    },
    {
      id: "e3eb9c9e-b5e8-5fb1-aefd-653bfe1ac2ae",
      clientId: "17c0d9e8-21ac-5a7e-95f3-1ae2b236b993",
      nom: "Atilla (2019-20)",
      statut: "cloture",
      dateDebut: "2020-07-01",
      dateFinPrevue: "2020-08-01",
      dateFin: "2020-08-01",
      budgetPrevisionnel: 255,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 46, categorie non_classe.",
      adresse: null
    },
    {
      id: "25aec469-11c1-5104-a99e-50391992c19a",
      clientId: "1afe9772-7e2a-5868-a5f3-ef73ab7a366e",
      nom: "Hamel (2019-20)",
      statut: "cloture",
      dateDebut: "2020-07-01",
      dateFinPrevue: "2020-08-01",
      dateFin: "2020-08-01",
      budgetPrevisionnel: 5023,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 47, categorie non_classe.",
      adresse: null
    },
    {
      id: "5e5d9c66-f2b2-55e8-bf8b-8c11aec4b933",
      clientId: "e0821946-ce1e-523b-a79b-151c4affcb55",
      nom: "Agren (2019-20)",
      statut: "cloture",
      dateDebut: "2020-07-01",
      dateFinPrevue: "2020-08-01",
      dateFin: "2020-08-01",
      budgetPrevisionnel: 330,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 51, categorie non_classe.",
      adresse: null
    },
    {
      id: "b3ffde95-7795-5216-b2b6-8d6fcd28a34f",
      clientId: "93cc4a4e-dcb4-5788-9d06-4cd1c0afbc0a",
      nom: "Sinigaglia (2019-20)",
      statut: "cloture",
      dateDebut: "2020-06-01",
      dateFinPrevue: "2020-09-01",
      dateFin: "2020-09-01",
      budgetPrevisionnel: 20059.27,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 37, categorie non_classe.",
      adresse: null
    },
    {
      id: "0ea844e9-3413-5979-a158-5714c9768cab",
      clientId: "666e814d-5d2c-5363-98e2-64fed35851a9",
      nom: "Zaghbouni (2019-20)",
      statut: "cloture",
      dateDebut: "2020-06-01",
      dateFinPrevue: "2020-08-01",
      dateFin: "2020-08-01",
      budgetPrevisionnel: 4003,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 48, categorie non_classe.",
      adresse: null
    },
    {
      id: "ecec5032-0c45-50d4-ae48-d14f948a6b68",
      clientId: "2d3b1401-239a-5a48-994b-045cff26a352",
      nom: "Darde (2019-20)",
      statut: "cloture",
      dateDebut: "2020-05-01",
      dateFinPrevue: "2020-06-01",
      dateFin: "2020-06-01",
      budgetPrevisionnel: 4357,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 29, categorie non_classe.",
      adresse: null
    },
    {
      id: "d2718fce-0345-527b-a789-4f37675b13f4",
      clientId: "558515b3-f228-5575-bc17-bbd52c4eb888",
      nom: "Coyer (2019-20)",
      statut: "cloture",
      dateDebut: "2020-05-01",
      dateFinPrevue: "2020-09-01",
      dateFin: "2020-09-01",
      budgetPrevisionnel: 32375,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 34, categorie non_classe.",
      adresse: null
    },
    {
      id: "8cf30d3e-51e7-57d7-81d8-8f93ef689ba7",
      clientId: "5ca97729-f3c3-5c00-bcb0-89f5c6d7536b",
      nom: "Maincent (2019-20)",
      statut: "cloture",
      dateDebut: "2020-05-01",
      dateFinPrevue: "2020-09-01",
      dateFin: "2020-09-01",
      budgetPrevisionnel: 28887,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 36, categorie non_classe.",
      adresse: null
    },
    {
      id: "18bfb68d-c975-5d90-9ee1-3e5731363f6d",
      clientId: "2e7bdc80-ef0f-56bf-8a77-eff64d2b3622",
      nom: "Raoult (2019-20)",
      statut: "cloture",
      dateDebut: "2020-05-01",
      dateFinPrevue: "2020-09-01",
      dateFin: "2020-09-01",
      budgetPrevisionnel: 108035,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 38, categorie non_classe.",
      adresse: null
    },
    {
      id: "38e6ed35-cd92-57ab-a8f2-80ef8f00bb23",
      clientId: "40cf37c4-f776-56f5-b367-5956e453f9c1",
      nom: "Philippe (2019-20)",
      statut: "cloture",
      dateDebut: "2020-05-01",
      dateFinPrevue: "2020-07-01",
      dateFin: "2020-07-01",
      budgetPrevisionnel: 4050,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 53, categorie non_classe.",
      adresse: null
    },
    {
      id: "f2055518-0515-5ad7-af0a-dbd14a81bec6",
      clientId: "9d706537-9649-5c42-adad-b152794369f4",
      nom: "Potet (2019-20)",
      statut: "cloture",
      dateDebut: "2020-04-01",
      dateFinPrevue: "2020-07-01",
      dateFin: "2020-07-01",
      budgetPrevisionnel: 52582.92,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 49, categorie non_classe.",
      adresse: null
    },
    {
      id: "8b34a4f6-e3a1-53f8-ba46-1a5b2815ff4f",
      clientId: "2d8f792d-92d8-5d33-8e8e-0a4a4f22b396",
      nom: "Gosset (2019-20)",
      statut: "cloture",
      dateDebut: "2020-04-01",
      dateFinPrevue: "2020-07-01",
      dateFin: "2020-07-01",
      budgetPrevisionnel: 18311.17,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 54, categorie non_classe.",
      adresse: null
    },
    {
      id: "0e01443b-f15b-561f-ba06-9bf962954abb",
      clientId: "86fba5e6-69b7-57e4-930f-dd1dab5a3894",
      nom: "Guimond (2019-20)",
      statut: "cloture",
      dateDebut: "2020-04-01",
      dateFinPrevue: "2020-06-01",
      dateFin: "2020-06-01",
      budgetPrevisionnel: 8850,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 57, categorie non_classe.",
      adresse: null
    },
    {
      id: "649f7ee4-7b15-5d79-abeb-206d18cdfd12",
      clientId: "17c0d9e8-21ac-5a7e-95f3-1ae2b236b993",
      nom: "Atilla (2019-20)",
      statut: "cloture",
      dateDebut: "2020-04-01",
      dateFinPrevue: "2020-06-01",
      dateFin: "2020-06-01",
      budgetPrevisionnel: 6000,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 59, categorie non_classe.",
      adresse: null
    },
    {
      id: "66618e6d-b625-5ba2-958b-8d85b728c952",
      clientId: "6463b527-a9e9-55f2-9c17-5bffb1e1493c",
      nom: "Maillard (2019-20)",
      statut: "cloture",
      dateDebut: "2020-04-01",
      dateFinPrevue: "2020-05-01",
      dateFin: "2020-05-01",
      budgetPrevisionnel: 6000,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 60, categorie non_classe.",
      adresse: null
    },
    {
      id: "5f47fb32-80b0-5715-8638-60084eec1343",
      clientId: "1e7caba9-1b98-52ed-8da8-19238aacb517",
      nom: "Chao (2019-20)",
      statut: "cloture",
      dateDebut: "2020-04-01",
      dateFinPrevue: "2020-05-01",
      dateFin: "2020-05-01",
      budgetPrevisionnel: 344,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 61, categorie non_classe.",
      adresse: null
    },
    {
      id: "5166a9e4-88ea-52d9-a330-3dc9f5d58bcf",
      clientId: "65b78976-ed9f-5963-a4a1-b81709a68fa8",
      nom: "Rf Flipo (2019-20)",
      statut: "cloture",
      dateDebut: "2020-03-01",
      dateFinPrevue: "2020-05-01",
      dateFin: "2020-05-01",
      budgetPrevisionnel: 12911,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 23, categorie non_classe.",
      adresse: null
    },
    {
      id: "512f6793-3c31-5d1a-bb68-e1abbbdc1024",
      clientId: "559103be-420c-5e27-af70-397e3e06e10a",
      nom: "Dubreul (2019-20)",
      statut: "cloture",
      dateDebut: "2020-03-01",
      dateFinPrevue: "2020-07-01",
      dateFin: "2020-07-01",
      budgetPrevisionnel: 27954,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 50, categorie non_classe.",
      adresse: null
    },
    {
      id: "5beceeee-b049-5691-98f8-30fecc9005fd",
      clientId: "17c17945-0f54-5427-a2a0-922fed2cbfe7",
      nom: "Prevel (2019-20)",
      statut: "cloture",
      dateDebut: "2020-03-01",
      dateFinPrevue: "2020-07-01",
      dateFin: "2020-07-01",
      budgetPrevisionnel: 37119,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 52, categorie non_classe.",
      adresse: null
    },
    {
      id: "eca3ff20-4408-5217-9b3c-8614e4300adc",
      clientId: "7fd75901-b6af-5481-915b-55acdc82f146",
      nom: "Le Masson (2019-20)",
      statut: "cloture",
      dateDebut: "2020-03-01",
      dateFinPrevue: "2020-07-01",
      dateFin: "2020-07-01",
      budgetPrevisionnel: 16094,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 55, categorie non_classe.",
      adresse: null
    },
    {
      id: "5a117c55-ee23-5caf-a795-8ec7d58df52b",
      clientId: "1dc0d6d8-c2b3-572f-9b95-84c119bcde3b",
      nom: "Cabourg (2019-20)",
      statut: "cloture",
      dateDebut: "2020-03-01",
      dateFinPrevue: "2020-05-01",
      dateFin: "2020-05-01",
      budgetPrevisionnel: 5757,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 58, categorie non_classe.",
      adresse: null
    },
    {
      id: "4774ba53-c3c5-5f86-a6a5-3d6ff34831b9",
      clientId: "41351551-17f6-53ce-884d-7cfa323c8460",
      nom: "Vaucher (2019-20)",
      statut: "cloture",
      dateDebut: "2020-03-01",
      dateFinPrevue: "2020-05-01",
      dateFin: "2020-05-01",
      budgetPrevisionnel: 20557,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 62, categorie non_classe.",
      adresse: null
    },
    {
      id: "142f6820-8f84-51a5-a854-e0c623cb4f12",
      clientId: "88bf6248-0679-5496-a50f-8c26f4b535be",
      nom: "Benoist (2019-20)",
      statut: "cloture",
      dateDebut: "2020-02-01",
      dateFinPrevue: "2020-03-01",
      dateFin: "2020-03-01",
      budgetPrevisionnel: 11253,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 65, categorie non_classe.",
      adresse: null
    },
    {
      id: "0d06867b-e7f5-5715-9b01-600264ebdd16",
      clientId: "44265dca-dbc9-5fdc-98e5-f413f278dbcb",
      nom: "Manche (2019-20)",
      statut: "cloture",
      dateDebut: "2020-01-01",
      dateFinPrevue: "2020-02-01",
      dateFin: "2020-02-01",
      budgetPrevisionnel: 1783,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 70, categorie non_classe.",
      adresse: null
    },
    {
      id: "e4ac9a3e-a0d2-516a-b93f-207c7aee8d7e",
      clientId: "4948dd00-24f2-5d90-acaf-e4f231b3c7c5",
      nom: "Leveque (2019-20)",
      statut: "cloture",
      dateDebut: "2019-12-01",
      dateFinPrevue: "2020-04-01",
      dateFin: "2020-04-01",
      budgetPrevisionnel: 56711.6,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 26, categorie non_classe.",
      adresse: null
    },
    {
      id: "2d0c0bf0-3108-548d-99a0-ebbb2be17f5f",
      clientId: "92d6f784-cd70-54e2-acf5-fbc823a4bda8",
      nom: "Hulin (2019-20)",
      statut: "cloture",
      dateDebut: "2019-12-01",
      dateFinPrevue: "2020-03-01",
      dateFin: "2020-03-01",
      budgetPrevisionnel: 7631,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 63, categorie non_classe.",
      adresse: null
    },
    {
      id: "ac5df740-f507-5a86-b470-9679f3a7e734",
      clientId: "1c2cb019-48f6-514e-b20d-de354f6a5334",
      nom: "Desfeux (2019-20)",
      statut: "cloture",
      dateDebut: "2019-12-01",
      dateFinPrevue: "2020-01-01",
      dateFin: "2020-01-01",
      budgetPrevisionnel: 3887,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 73, categorie non_classe.",
      adresse: null
    },
    {
      id: "8c45f756-6da1-5917-a7ac-dca526056b8d",
      clientId: "bb0105fe-17de-5156-b4c3-ef4d2fba3317",
      nom: "Cadieu Noury (2019-20)",
      statut: "cloture",
      dateDebut: "2019-11-01",
      dateFinPrevue: "2020-07-01",
      dateFin: "2020-07-01",
      budgetPrevisionnel: 87107.63,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 35, categorie non_classe.",
      adresse: null
    },
    {
      id: "de107b90-0a57-533b-ae1f-67388ff561b2",
      clientId: "dc1333ba-f82b-5519-968a-a9769e7be0c3",
      nom: "Tesson (2019-20)",
      statut: "cloture",
      dateDebut: "2019-11-01",
      dateFinPrevue: "2020-05-01",
      dateFin: "2020-05-01",
      budgetPrevisionnel: 73304,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 39, categorie non_classe.",
      adresse: null
    },
    {
      id: "6dfc1aa7-f6bd-5e74-a1a7-412e8e2b1890",
      clientId: "2b1e6722-8a61-5001-a617-e9196f47a9d1",
      nom: "Lozach Mary (2019-20)",
      statut: "cloture",
      dateDebut: "2019-11-01",
      dateFinPrevue: "2020-03-01",
      dateFin: "2020-03-01",
      budgetPrevisionnel: 28444.86,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 64, categorie non_classe.",
      adresse: null
    },
    {
      id: "b0beaaa6-a787-5aed-9e80-2bb8a6adbdc2",
      clientId: "e37fea02-64f0-597b-a3ed-52fa8cfe42a4",
      nom: "Kite Surf (2019-20)",
      statut: "cloture",
      dateDebut: "2019-11-01",
      dateFinPrevue: "2020-02-01",
      dateFin: "2020-02-01",
      budgetPrevisionnel: 60272,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 67, categorie non_classe.",
      adresse: null
    },
    {
      id: "9c993ec4-395a-5308-ad01-668b3ca9810c",
      clientId: "0271f657-a4c2-5d9f-9983-5be50f8d0832",
      nom: "Vergriete (2019-20)",
      statut: "cloture",
      dateDebut: "2019-11-01",
      dateFinPrevue: "2020-02-01",
      dateFin: "2020-02-01",
      budgetPrevisionnel: 36749,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 68, categorie non_classe.",
      adresse: null
    },
    {
      id: "eff14031-cbce-5c31-b395-7ec3f48f412d",
      clientId: "cbe22469-53b6-5fef-bf23-bd02fafa48af",
      nom: "Rohrbach (2019-20)",
      statut: "cloture",
      dateDebut: "2019-11-01",
      dateFinPrevue: "2020-02-01",
      dateFin: "2020-02-01",
      budgetPrevisionnel: 38516,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 69, categorie non_classe.",
      adresse: null
    },
    {
      id: "1b9f3006-ce92-586c-ab73-ee53f3e3fb15",
      clientId: "8e480e86-d9eb-59e3-88fb-3d167241483d",
      nom: "DUPONT CHALESLE iso ext (2019-20)",
      statut: "cloture",
      dateDebut: "2019-11-01",
      dateFinPrevue: "2020-01-01",
      dateFin: "2020-01-01",
      budgetPrevisionnel: 27209,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 71, categorie non_classe.",
      adresse: null
    },
    {
      id: "d5a7cc58-cd54-50bc-b464-9f8f7887abfa",
      clientId: "de095f46-6e3c-5e8d-9a1f-023e6cc7075d",
      nom: "Delamare (2019-20)",
      statut: "cloture",
      dateDebut: "2019-11-01",
      dateFinPrevue: "2019-12-01",
      dateFin: "2019-12-01",
      budgetPrevisionnel: 4299,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 76, categorie non_classe.",
      adresse: null
    },
    {
      id: "1531ca19-b177-5f33-8fb8-9cbf2d03117d",
      clientId: "10da6d7d-e908-51fb-9664-311c42dbf2bc",
      nom: "Sci Prj (2019-20)",
      statut: "cloture",
      dateDebut: "2019-11-01",
      dateFinPrevue: "2019-12-01",
      dateFin: "2019-12-01",
      budgetPrevisionnel: 5165,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 77, categorie non_classe.",
      adresse: null
    },
    {
      id: "c0351aba-1afb-504a-91af-cad090c400b7",
      clientId: "da10e920-e1fe-5d46-ab6b-b9a068bc70ed",
      nom: "Gernault - Ibanescu (2019-20)",
      statut: "cloture",
      dateDebut: "2019-10-01",
      dateFinPrevue: "2019-11-01",
      dateFin: "2019-11-01",
      budgetPrevisionnel: 97245,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 6, categorie non_classe.",
      adresse: null
    },
    {
      id: "034f6c11-c5f0-5570-968b-97b9d7fe333f",
      clientId: "d1be87b6-38f1-53a9-a8cd-1fa532ae55bb",
      nom: "Schiel (2019-20)",
      statut: "cloture",
      dateDebut: "2019-10-01",
      dateFinPrevue: "2019-11-01",
      dateFin: "2019-11-01",
      budgetPrevisionnel: 137101,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 7, categorie non_classe.",
      adresse: null
    },
    {
      id: "5decdcb3-ec0f-543f-b450-f408fbc36971",
      clientId: "ebfe7e0a-d277-567c-afa7-80b47c9246f7",
      nom: "Geze (2019-20)",
      statut: "cloture",
      dateDebut: "2019-10-01",
      dateFinPrevue: "2019-11-01",
      dateFin: "2019-11-01",
      budgetPrevisionnel: 46977,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 8, categorie non_classe.",
      adresse: null
    },
    {
      id: "76be4308-3386-50f3-8d97-5afbfbb70386",
      clientId: "b31e6072-27e4-5c6e-8248-267d60fdda30",
      nom: "Thire (2019-20)",
      statut: "cloture",
      dateDebut: "2019-10-01",
      dateFinPrevue: "2019-11-01",
      dateFin: "2019-11-01",
      budgetPrevisionnel: 45339,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 9, categorie non_classe.",
      adresse: null
    },
    {
      id: "55c1950c-d75e-51ee-a0cb-f85d411df4bb",
      clientId: "e17e6892-832c-55cd-9b0d-204cd57bfc01",
      nom: "Leroullier (2019-20)",
      statut: "cloture",
      dateDebut: "2019-10-01",
      dateFinPrevue: "2019-11-01",
      dateFin: "2019-11-01",
      budgetPrevisionnel: 43205,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 10, categorie non_classe.",
      adresse: null
    },
    {
      id: "2b05102f-1ef7-5457-8ea1-fed43e727d62",
      clientId: "fb1c35d0-b0d5-5eef-9469-b04014fc7a48",
      nom: "Chesnel (2019-20)",
      statut: "cloture",
      dateDebut: "2019-10-01",
      dateFinPrevue: "2019-11-01",
      dateFin: "2019-11-01",
      budgetPrevisionnel: 23403,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 11, categorie non_classe.",
      adresse: null
    },
    {
      id: "d6f3d9ef-82e0-542b-a929-9319a27492dd",
      clientId: "6b765cdb-ffaf-533b-860c-ca0db40f8673",
      nom: "Rf Roussel (2019-20)",
      statut: "cloture",
      dateDebut: "2019-10-01",
      dateFinPrevue: "2019-11-01",
      dateFin: "2019-11-01",
      budgetPrevisionnel: 51345,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 12, categorie non_classe.",
      adresse: null
    },
    {
      id: "d0852c6b-0c14-56be-a85a-91686f51bd83",
      clientId: "68c8c60b-e9a0-58ef-b908-a26294ff0d5a",
      nom: "Jager (2019-20)",
      statut: "cloture",
      dateDebut: "2019-10-01",
      dateFinPrevue: "2019-11-01",
      dateFin: "2019-11-01",
      budgetPrevisionnel: 70682,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 13, categorie non_classe.",
      adresse: null
    },
    {
      id: "598de80f-2d13-5838-a271-02742615acf9",
      clientId: "92d6f784-cd70-54e2-acf5-fbc823a4bda8",
      nom: "Hulin (2019-20)",
      statut: "cloture",
      dateDebut: "2019-10-01",
      dateFinPrevue: "2019-11-01",
      dateFin: "2019-11-01",
      budgetPrevisionnel: 35372.24,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 14, categorie non_classe.",
      adresse: null
    },
    {
      id: "edcf6e42-5e19-5a36-b462-111275ffc9e8",
      clientId: "9def8216-ceda-5492-9dd3-8891d3a0f574",
      nom: "Darcillon (2019-20)",
      statut: "cloture",
      dateDebut: "2019-10-01",
      dateFinPrevue: "2019-11-01",
      dateFin: "2019-11-01",
      budgetPrevisionnel: 68020,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 15, categorie non_classe.",
      adresse: null
    },
    {
      id: "9b46461c-30a8-570e-8e25-3419d4511b15",
      clientId: "4ffb3be0-b7b2-5a40-915e-8d52873c5809",
      nom: "Lalloz (2019-20)",
      statut: "cloture",
      dateDebut: "2019-10-01",
      dateFinPrevue: "2019-11-01",
      dateFin: "2019-11-01",
      budgetPrevisionnel: 4865.8,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 16, categorie non_classe.",
      adresse: null
    },
    {
      id: "9437f15f-663e-5d5b-a9a3-fe22f8a03705",
      clientId: "8c846b99-322c-51d4-816b-d46dac3b83f9",
      nom: "Froger (2019-20)",
      statut: "cloture",
      dateDebut: "2019-10-01",
      dateFinPrevue: "2019-11-01",
      dateFin: "2019-11-01",
      budgetPrevisionnel: 1913,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 17, categorie non_classe.",
      adresse: null
    },
    {
      id: "49a9b074-1215-5dec-b3f7-cb6757eae671",
      clientId: "baecd01d-38f0-5d3e-a4c7-6409518e8564",
      nom: "Rouillard (2019-20)",
      statut: "cloture",
      dateDebut: "2019-10-01",
      dateFinPrevue: "2019-11-01",
      dateFin: "2019-11-01",
      budgetPrevisionnel: 11993.73,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 18, categorie non_classe.",
      adresse: null
    }
  ])
}
