mutation @transaction {
  chantiers012: chantier_upsertMany(data: [
    {
      id: "6a439fca-d93c-5bf4-89bc-b2e0d5bbf3eb",
      origineImport: "previsionnel",
      clientId: "76a561ca-6060-525c-b3bf-54bdb3b9e7fc",
      nom: "Bicard (2019-20)",
      statut: "cloture",
      dateDebut: "2019-10-01",
      dateFinPrevue: "2019-11-01",
      dateFin: "2019-11-01",
      budgetPrevisionnel: 13428,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 19, categorie non_classe.",
      adresse: null
    },
    {
      id: "ae87d730-1398-59df-81c5-5cf543cde51a",
      origineImport: "previsionnel",
      clientId: "41f179ab-e338-5bc5-877a-c1b83b5b03ac",
      nom: "Boeuve (2019-20)",
      statut: "cloture",
      dateDebut: "2019-10-01",
      dateFinPrevue: "2019-11-01",
      dateFin: "2019-11-01",
      budgetPrevisionnel: 22297,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 20, categorie non_classe.",
      adresse: null
    },
    {
      id: "88140c09-7cf9-5567-a198-f0e98306fd66",
      origineImport: "previsionnel",
      clientId: "a65f7c59-5102-5c98-b420-75793e8aeeea",
      nom: "Germain (2019-20)",
      statut: "cloture",
      dateDebut: "2019-10-01",
      dateFinPrevue: "2019-11-01",
      dateFin: "2019-11-01",
      budgetPrevisionnel: 2019,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 21, categorie non_classe.",
      adresse: null
    },
    {
      id: "9f17ccac-69b6-55d2-978d-956d514b7ec8",
      origineImport: "previsionnel",
      clientId: "77bed385-9ad7-5cc8-9ec1-e991b420029f",
      nom: "Marie (2019-20)",
      statut: "cloture",
      dateDebut: "2019-10-01",
      dateFinPrevue: "2020-04-01",
      dateFin: "2020-04-01",
      budgetPrevisionnel: 48348,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 56, categorie non_classe.",
      adresse: null
    },
    {
      id: "4ac44b89-c2ae-54f6-b560-b6b72ca1db0c",
      origineImport: "previsionnel",
      clientId: "4b8dc882-7db0-5df2-91bc-ca5bfe663fa7",
      nom: "Anquetil (2019-20)",
      statut: "cloture",
      dateDebut: "2019-10-01",
      dateFinPrevue: "2019-12-01",
      dateFin: "2019-12-01",
      budgetPrevisionnel: 11957,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 66, categorie non_classe.",
      adresse: null
    },
    {
      id: "897de70b-073b-5233-8660-70d0e6c24a04",
      origineImport: "previsionnel",
      clientId: "13edb9df-a731-5917-9790-1c32484a0cca",
      nom: "Breteau (2019-20)",
      statut: "cloture",
      dateDebut: "2019-10-01",
      dateFinPrevue: "2019-12-01",
      dateFin: "2019-12-01",
      budgetPrevisionnel: 13034,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 72, categorie non_classe.",
      adresse: null
    },
    {
      id: "0d72ba2a-be7e-560e-a5b7-0cc6c937bb21",
      origineImport: "previsionnel",
      clientId: "0b969251-2aa0-5b12-81be-9b6a2928e5de",
      nom: "Dupont Chalesle (2019-20)",
      statut: "cloture",
      dateDebut: "2019-10-01",
      dateFinPrevue: "2019-12-01",
      dateFin: "2019-12-01",
      budgetPrevisionnel: 19649,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 74, categorie non_classe.",
      adresse: null
    },
    {
      id: "6f46d707-cd93-50d6-8e5b-56c006f0ecf8",
      origineImport: "previsionnel",
      clientId: "9bd9f9e3-3f7c-55a8-8838-0a3e4ae22fac",
      nom: "Loberger (2019-20)",
      statut: "cloture",
      dateDebut: "2019-10-01",
      dateFinPrevue: "2019-12-01",
      dateFin: "2019-12-01",
      budgetPrevisionnel: 4190,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 75, categorie non_classe.",
      adresse: null
    },
    {
      id: "3e51de19-e9d3-5559-84f9-3ad2b5e4de93",
      origineImport: "previsionnel",
      clientId: "4e100c13-bcd7-5abf-aea1-7669ace1287f",
      nom: "Letourneur (2019-20)",
      statut: "cloture",
      dateDebut: "2019-10-01",
      dateFinPrevue: "2019-11-01",
      dateFin: "2019-11-01",
      budgetPrevisionnel: 556,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 78, categorie non_classe.",
      adresse: null
    },
    {
      id: "fa90d8c2-0385-5006-a2f1-bf2a8332cb3c",
      origineImport: "previsionnel",
      clientId: "b99ef3a0-82fd-5a7e-b607-b277b82e5917",
      nom: "Colore Caen (2019-20)",
      statut: "cloture",
      dateDebut: "2019-10-01",
      dateFinPrevue: "2019-11-01",
      dateFin: "2019-11-01",
      budgetPrevisionnel: 500,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 79, categorie non_classe.",
      adresse: null
    },
    {
      id: "65f601b0-afe8-5afa-ac84-f94da766756c",
      origineImport: "previsionnel",
      clientId: "27d890b9-ec3f-5714-bf0b-970bf9f6b48f",
      nom: "Parisotto (2019-20)",
      statut: "cloture",
      dateDebut: "2019-10-01",
      dateFinPrevue: "2019-11-01",
      dateFin: "2019-11-01",
      budgetPrevisionnel: 1990,
      description: "Import PREVISIONNEL.xlsx - onglet 2019-20, ligne 80, categorie non_classe.",
      adresse: null
    },
    {
      id: "94ceef00-0a74-517d-b4df-25bda9652b3e",
      origineImport: "previsionnel",
      clientId: "14a4d407-a57b-5c0b-848c-b442692d9af6",
      nom: "Spie batignol (2018-19)",
      statut: "cloture",
      dateDebut: "2019-09-01",
      dateFinPrevue: "2019-10-01",
      dateFin: "2019-10-01",
      budgetPrevisionnel: 3077,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 70, categorie non_classe.",
      adresse: null
    },
    {
      id: "5e7bb9a2-39ab-5508-9210-318a48dec939",
      origineImport: "previsionnel",
      clientId: "dc1333ba-f82b-5519-968a-a9769e7be0c3",
      nom: "Tesson (2018-19)",
      statut: "cloture",
      dateDebut: "2019-09-01",
      dateFinPrevue: "2019-10-01",
      dateFin: "2019-10-01",
      budgetPrevisionnel: 118578,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 71, categorie non_classe.",
      adresse: null
    },
    {
      id: "608395da-f7f0-5f1c-88bc-19aabff5cfa8",
      origineImport: "previsionnel",
      clientId: "0271f657-a4c2-5d9f-9983-5be50f8d0832",
      nom: "Vergriete (2018-19)",
      statut: "cloture",
      dateDebut: "2019-08-01",
      dateFinPrevue: "2019-09-01",
      dateFin: "2019-09-01",
      budgetPrevisionnel: 50956,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 33, categorie non_classe.",
      adresse: null
    },
    {
      id: "874b931d-2bbc-5866-b070-71577dd0b669",
      origineImport: "previsionnel",
      clientId: "77bed385-9ad7-5cc8-9ec1-e991b420029f",
      nom: "Marie (2018-19)",
      statut: "cloture",
      dateDebut: "2019-08-01",
      dateFinPrevue: "2019-10-01",
      dateFin: "2019-10-01",
      budgetPrevisionnel: 81382,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 34, categorie non_classe.",
      adresse: null
    },
    {
      id: "3552feb6-e715-56a7-883c-8531527ffbf8",
      origineImport: "previsionnel",
      clientId: "2b1e6722-8a61-5001-a617-e9196f47a9d1",
      nom: "Lozach Mary (2018-19)",
      statut: "cloture",
      dateDebut: "2019-08-01",
      dateFinPrevue: "2019-10-01",
      dateFin: "2019-10-01",
      budgetPrevisionnel: 48438,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 48, categorie non_classe.",
      adresse: null
    },
    {
      id: "57c5ef08-4581-5934-a5ac-d5804dfd9658",
      origineImport: "previsionnel",
      clientId: "9bd9f9e3-3f7c-55a8-8838-0a3e4ae22fac",
      nom: "Loberger (2018-19)",
      statut: "cloture",
      dateDebut: "2019-08-01",
      dateFinPrevue: "2019-10-01",
      dateFin: "2019-10-01",
      budgetPrevisionnel: 11536,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 50, categorie non_classe.",
      adresse: null
    },
    {
      id: "53c85175-1e58-5a33-a4c3-d7e83835e472",
      origineImport: "previsionnel",
      clientId: "13edb9df-a731-5917-9790-1c32484a0cca",
      nom: "Breteau (2018-19)",
      statut: "cloture",
      dateDebut: "2019-08-01",
      dateFinPrevue: "2019-10-01",
      dateFin: "2019-10-01",
      budgetPrevisionnel: 36066,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 69, categorie non_classe.",
      adresse: null
    },
    {
      id: "a090df71-dbc2-5a23-952e-a52ceb04d55d",
      origineImport: "previsionnel",
      clientId: "47a9a245-904d-50ee-9cfd-7423a2c5c37f",
      nom: "De Jean (2018-19)",
      statut: "cloture",
      dateDebut: "2019-07-01",
      dateFinPrevue: "2019-08-01",
      dateFin: "2019-08-01",
      budgetPrevisionnel: 1749,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 64, categorie non_classe.",
      adresse: null
    },
    {
      id: "8c9cd6a2-c144-57ad-9c67-9869f20e2c31",
      origineImport: "previsionnel",
      clientId: "9d5ae71b-e091-5b76-8e6a-38f998353bf4",
      nom: "Nogent (2018-19)",
      statut: "cloture",
      dateDebut: "2019-06-01",
      dateFinPrevue: "2019-08-01",
      dateFin: "2019-08-01",
      budgetPrevisionnel: 19583,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 43, categorie non_classe.",
      adresse: null
    },
    {
      id: "0b0540b3-6393-52a1-bcd3-6f5a5a9d23ca",
      origineImport: "previsionnel",
      clientId: "0b969251-2aa0-5b12-81be-9b6a2928e5de",
      nom: "Dupont Chalesle (2018-19)",
      statut: "cloture",
      dateDebut: "2019-06-01",
      dateFinPrevue: "2019-09-01",
      dateFin: "2019-09-01",
      budgetPrevisionnel: 72581,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 45, categorie non_classe.",
      adresse: null
    },
    {
      id: "cf29a2d5-a710-50ae-b011-bb4d8bab1b06",
      origineImport: "previsionnel",
      clientId: "91039e29-5160-5d2e-acd0-ebfbeffdb140",
      nom: "Le Louarn (2018-19)",
      statut: "cloture",
      dateDebut: "2019-06-01",
      dateFinPrevue: "2019-08-01",
      dateFin: "2019-08-01",
      budgetPrevisionnel: 43632,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 52, categorie non_classe.",
      adresse: null
    },
    {
      id: "933a6062-90a2-5b9a-8850-7c9911117e94",
      origineImport: "previsionnel",
      clientId: "65f3413e-f4d2-50ff-b452-b3e39597a137",
      nom: "Lock Quest (2018-19)",
      statut: "cloture",
      dateDebut: "2019-06-01",
      dateFinPrevue: "2019-07-01",
      dateFin: "2019-07-01",
      budgetPrevisionnel: 21652,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 63, categorie non_classe.",
      adresse: null
    },
    {
      id: "85400c6b-b962-543f-baab-f42544489f2f",
      origineImport: "previsionnel",
      clientId: "44265dca-dbc9-5fdc-98e5-f413f278dbcb",
      nom: "Manche (2018-19)",
      statut: "cloture",
      dateDebut: "2019-05-01",
      dateFinPrevue: "2019-08-01",
      dateFin: "2019-08-01",
      budgetPrevisionnel: 62896,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 27, categorie non_classe.",
      adresse: null
    },
    {
      id: "8ffb714e-212c-5de4-82ea-1daab212131f",
      origineImport: "previsionnel",
      clientId: "2d3b1401-239a-5a48-994b-045cff26a352",
      nom: "Darde (2018-19)",
      statut: "cloture",
      dateDebut: "2019-05-01",
      dateFinPrevue: "2019-08-01",
      dateFin: "2019-08-01",
      budgetPrevisionnel: 31830,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 44, categorie non_classe.",
      adresse: null
    },
    {
      id: "242efb43-8631-5ae5-8e4e-160918f97b16",
      origineImport: "previsionnel",
      clientId: "43e881a7-241d-5f3b-a414-30db82f51f55",
      nom: "Agelia (2018-19)",
      statut: "cloture",
      dateDebut: "2019-05-01",
      dateFinPrevue: "2019-06-01",
      dateFin: "2019-06-01",
      budgetPrevisionnel: 3211,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 57, categorie non_classe.",
      adresse: null
    },
    {
      id: "b84ccfba-0a00-5d95-a843-209866ab4bfc",
      origineImport: "previsionnel",
      clientId: "6fcbad3a-0316-5e31-a7a3-49cc15098c74",
      nom: "Rf ablin (2018-19)",
      statut: "cloture",
      dateDebut: "2019-05-01",
      dateFinPrevue: "2019-06-01",
      dateFin: "2019-06-01",
      budgetPrevisionnel: 491,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 60, categorie non_classe.",
      adresse: null
    },
    {
      id: "de7e6289-ea2d-5a6e-bfe5-94b5a34cab96",
      origineImport: "previsionnel",
      clientId: "1aee52a8-1c42-558e-9e30-d006886ec3c7",
      nom: "Girre (2018-19)",
      statut: "cloture",
      dateDebut: "2019-04-01",
      dateFinPrevue: "2019-05-01",
      dateFin: "2019-05-01",
      budgetPrevisionnel: 13327,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 46, categorie non_classe.",
      adresse: null
    },
    {
      id: "18790310-1b98-5c53-9ca3-887e88002200",
      origineImport: "previsionnel",
      clientId: "a8201396-8e94-5d60-99a6-ac76e363e34c",
      nom: "Sofinab (2018-19)",
      statut: "cloture",
      dateDebut: "2019-04-01",
      dateFinPrevue: "2019-05-01",
      dateFin: "2019-05-01",
      budgetPrevisionnel: 29041,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 51, categorie non_classe.",
      adresse: null
    },
    {
      id: "1948ede9-5044-51b8-9c25-d75b401f3d7d",
      origineImport: "previsionnel",
      clientId: "8bac2d43-da26-50e9-aaf2-6478553852c9",
      nom: "Billet (2018-19)",
      statut: "cloture",
      dateDebut: "2019-04-01",
      dateFinPrevue: "2019-06-01",
      dateFin: "2019-06-01",
      budgetPrevisionnel: 15440,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 53, categorie non_classe.",
      adresse: null
    },
    {
      id: "d01c53cc-a1b7-5b7f-9764-7ae2057d2c80",
      origineImport: "previsionnel",
      clientId: "93cc4a4e-dcb4-5788-9d06-4cd1c0afbc0a",
      nom: "Sinigaglia (2018-19)",
      statut: "cloture",
      dateDebut: "2019-04-01",
      dateFinPrevue: "2019-05-01",
      dateFin: "2019-05-01",
      budgetPrevisionnel: 27156,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 54, categorie non_classe.",
      adresse: null
    },
    {
      id: "412c5558-2b14-59a8-86cf-057962fdc79b",
      origineImport: "previsionnel",
      clientId: "202cee28-c62a-5b2a-886f-82825cd3b24b",
      nom: "Marabetti (2018-19)",
      statut: "cloture",
      dateDebut: "2019-04-01",
      dateFinPrevue: "2019-06-01",
      dateFin: "2019-06-01",
      budgetPrevisionnel: 30150,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 56, categorie non_classe.",
      adresse: null
    },
    {
      id: "9691bab6-2cce-5aee-a604-fee6c2ddf4c6",
      origineImport: "previsionnel",
      clientId: "5ed7f322-572b-5786-810a-45d06c43b691",
      nom: "Peltier (2018-19)",
      statut: "cloture",
      dateDebut: "2019-03-01",
      dateFinPrevue: "2019-04-01",
      dateFin: "2019-04-01",
      budgetPrevisionnel: 7082,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 6, categorie non_classe.",
      adresse: null
    },
    {
      id: "00532a5b-35d3-58ff-865d-011285640512",
      origineImport: "previsionnel",
      clientId: "ddb230b3-da94-52d8-ac72-b460a5557869",
      nom: "Fourey (2018-19)",
      statut: "cloture",
      dateDebut: "2019-03-01",
      dateFinPrevue: "2019-04-01",
      dateFin: "2019-04-01",
      budgetPrevisionnel: 3963,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 23, categorie non_classe.",
      adresse: null
    },
    {
      id: "3b7454ed-1f52-5c96-8d15-7040fe067c0a",
      origineImport: "previsionnel",
      clientId: "96c1302d-cd6e-5220-a342-5b531c8700ee",
      nom: "Flaguais (2018-19)",
      statut: "cloture",
      dateDebut: "2019-03-01",
      dateFinPrevue: "2019-06-01",
      dateFin: "2019-06-01",
      budgetPrevisionnel: 42611,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 39, categorie non_classe.",
      adresse: null
    },
    {
      id: "d217bb64-78f6-5702-9aa6-1f9b9f791da0",
      origineImport: "previsionnel",
      clientId: "8cd03b19-1258-510d-8280-d23d861ca178",
      nom: "Bouet (2018-19)",
      statut: "cloture",
      dateDebut: "2019-02-01",
      dateFinPrevue: "2019-03-01",
      dateFin: "2019-03-01",
      budgetPrevisionnel: 5336,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 40, categorie non_classe.",
      adresse: null
    },
    {
      id: "9c78bb77-77e8-5b4d-9b24-f2060f054e41",
      origineImport: "previsionnel",
      clientId: "30c9c63b-0bfd-5944-82ef-db57e5ec87c1",
      nom: "Joly (2018-19)",
      statut: "cloture",
      dateDebut: "2019-02-01",
      dateFinPrevue: "2019-03-01",
      dateFin: "2019-03-01",
      budgetPrevisionnel: 1438,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 42, categorie non_classe.",
      adresse: null
    },
    {
      id: "4d44e7e3-57b2-5db0-bf52-d63c38f68e99",
      origineImport: "previsionnel",
      clientId: "39638c0c-15a0-5bdf-854a-093582175244",
      nom: "Ferard (2018-19)",
      statut: "cloture",
      dateDebut: "2019-01-01",
      dateFinPrevue: "2019-04-01",
      dateFin: "2019-04-01",
      budgetPrevisionnel: 52246,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 16, categorie non_classe.",
      adresse: null
    },
    {
      id: "02c171eb-8beb-516e-a565-635b3d4c2310",
      origineImport: "previsionnel",
      clientId: "8587a504-3379-547a-b3a8-72b422819d1b",
      nom: "Papillon (2018-19)",
      statut: "cloture",
      dateDebut: "2019-01-01",
      dateFinPrevue: "2019-03-01",
      dateFin: "2019-03-01",
      budgetPrevisionnel: 16756,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 25, categorie non_classe.",
      adresse: null
    },
    {
      id: "dde3eca3-e42f-5373-9e04-d797573b3bdd",
      origineImport: "previsionnel",
      clientId: "a882dbfa-0c4e-581e-b845-258be79d3015",
      nom: "Lopez (2018-19)",
      statut: "cloture",
      dateDebut: "2019-01-01",
      dateFinPrevue: "2019-02-01",
      dateFin: "2019-02-01",
      budgetPrevisionnel: 4221,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 26, categorie non_classe.",
      adresse: null
    },
    {
      id: "1439d931-8193-5f69-9940-ac3b510df42a",
      origineImport: "previsionnel",
      clientId: "f0e10c7d-987d-53cc-a6ce-b11af154eedd",
      nom: "Lastelle (2018-19)",
      statut: "cloture",
      dateDebut: "2019-01-01",
      dateFinPrevue: "2019-03-01",
      dateFin: "2019-03-01",
      budgetPrevisionnel: 29492,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 32, categorie non_classe.",
      adresse: null
    },
    {
      id: "e581cc38-8fea-5c7a-9158-9f1135eb7020",
      origineImport: "previsionnel",
      clientId: "337bea63-9f45-5e6b-a26e-443d275d0a80",
      nom: "Quemener (2018-19)",
      statut: "cloture",
      dateDebut: "2018-12-01",
      dateFinPrevue: "2019-02-01",
      dateFin: "2019-02-01",
      budgetPrevisionnel: 25132,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 8, categorie non_classe.",
      adresse: null
    },
    {
      id: "da530481-97cd-587d-bd84-6b9c017514cf",
      origineImport: "previsionnel",
      clientId: "cd07fcaa-c6d3-5579-b451-d2de2c7f7a9f",
      nom: "Guibout (2018-19)",
      statut: "cloture",
      dateDebut: "2018-12-01",
      dateFinPrevue: "2019-05-01",
      dateFin: "2019-05-01",
      budgetPrevisionnel: 76932,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 10, categorie non_classe.",
      adresse: null
    },
    {
      id: "deabe919-2c29-53d2-9b9b-72230d1d9577",
      origineImport: "previsionnel",
      clientId: "be6c935a-0223-5358-a96d-6ec71813023b",
      nom: "Gabriel (2018-19)",
      statut: "cloture",
      dateDebut: "2018-12-01",
      dateFinPrevue: "2019-02-01",
      dateFin: "2019-02-01",
      budgetPrevisionnel: 11184,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 11, categorie non_classe.",
      adresse: null
    },
    {
      id: "19fbc716-8422-52ac-b933-1a3d2960608d",
      origineImport: "previsionnel",
      clientId: "a65f7c59-5102-5c98-b420-75793e8aeeea",
      nom: "Germain (2018-19)",
      statut: "cloture",
      dateDebut: "2018-12-01",
      dateFinPrevue: "2019-07-01",
      dateFin: "2019-07-01",
      budgetPrevisionnel: 136516,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 12, categorie non_classe.",
      adresse: null
    },
    {
      id: "965728af-ce8c-598c-ba65-c6888c77274c",
      origineImport: "previsionnel",
      clientId: "1a7936d8-eadd-5a5b-9ce4-90b8d05cc899",
      nom: "Sci Des Mottets (2018-19)",
      statut: "cloture",
      dateDebut: "2018-12-01",
      dateFinPrevue: "2019-02-01",
      dateFin: "2019-02-01",
      budgetPrevisionnel: 10544,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 18, categorie non_classe.",
      adresse: null
    },
    {
      id: "007be611-d6d2-5ca7-93a3-5f6ef030fc0a",
      origineImport: "previsionnel",
      clientId: "873b5e0b-2c45-5564-bc46-4527d324d725",
      nom: "Estorges (2018-19)",
      statut: "cloture",
      dateDebut: "2018-12-01",
      dateFinPrevue: "2019-01-01",
      dateFin: "2019-01-01",
      budgetPrevisionnel: 1337,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 31, categorie non_classe.",
      adresse: null
    },
    {
      id: "cda04b52-7475-55b3-98f2-48a365a6c095",
      origineImport: "previsionnel",
      clientId: "89a9dcab-b9b2-55e0-abab-cf17801f94c5",
      nom: "MORLET blonville sur mer (2018-19)",
      statut: "cloture",
      dateDebut: "2018-11-01",
      dateFinPrevue: "2019-02-01",
      dateFin: "2019-02-01",
      budgetPrevisionnel: 47888.89,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 7, categorie non_classe.",
      adresse: null
    },
    {
      id: "3abb5d42-c1fa-53a3-8093-f2f74eba5c98",
      origineImport: "previsionnel",
      clientId: "e8760822-2896-506a-9518-a9d42326cdec",
      nom: "Talmar (2018-19)",
      statut: "cloture",
      dateDebut: "2018-11-01",
      dateFinPrevue: "2018-12-01",
      dateFin: "2018-12-01",
      budgetPrevisionnel: 6420,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 22, categorie non_classe.",
      adresse: null
    },
    {
      id: "ae862dad-e842-5adb-97b3-f889de93f483",
      origineImport: "previsionnel",
      clientId: "97390eb4-448c-53dd-a8a8-e70906af733e",
      nom: "Morotti (2018-19)",
      statut: "cloture",
      dateDebut: "2018-11-01",
      dateFinPrevue: "2018-12-01",
      dateFin: "2018-12-01",
      budgetPrevisionnel: 8451,
      description: "Import PREVISIONNEL.xlsx - onglet 2018-19, ligne 28, categorie non_classe.",
      adresse: null
    }
  ])
}
