mutation @transaction {
  lines004: previsionnelLine_upsertMany(data: [
    {
      id: "a694439e-6ee9-5bd6-beb5-ce3fc65e26a8",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "0638add7-8137-52f5-8ecc-c85c4a51c6e1",
      chantierId: "d949bef8-6bdb-510f-ac77-ab689fd2a477",
      sourceSheet: "2015-16",
      sourceRow: 39,
      rawName: "RF HGP",
      clientKey: "rf-hgp",
      clientName: "Rf Hgp",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 4375,
      plannedTotal: 4375,
      realizedTotal: 4375,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "9662fbc1-e12a-5f79-a9eb-1608da0e4ce7",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "004c736f-4ecb-5cc2-8faa-ceb97b8cffa4",
      chantierId: "5e83cfc1-e075-5c0e-8609-bd97146d8d83",
      sourceSheet: "2015-16",
      sourceRow: 40,
      rawName: "SARL ESNAULT LES MARINAS",
      clientKey: "sarl-esnault-les-marinas",
      clientName: "Sarl Esnault Les Marinas",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 47975,
      plannedTotal: 47974,
      realizedTotal: 47974,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "af563890-c4fd-5590-99d6-87ef2fc6ccb9",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "03c0084b-ef1f-5b61-85e4-4fe40f0a985c",
      chantierId: "373f20ad-f44b-51bb-bccf-34de64743fff",
      sourceSheet: "2015-16",
      sourceRow: 41,
      rawName: "DAUMESNIL",
      clientKey: "daumesnil",
      clientName: "Daumesnil",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 23622,
      plannedTotal: 23622,
      realizedTotal: 23622,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "901cf7bc-e7c4-5d37-acd8-e51f6939029a",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "7b441928-cdee-55e8-9388-e9067c1aee73",
      chantierId: "6438a682-29eb-55bf-bacc-cf94dcfb94ad",
      sourceSheet: "2015-16",
      sourceRow: 42,
      rawName: "CORTEQUISSE ext",
      clientKey: "cortequisse-ext",
      clientName: "CORTEQUISSE ext",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 25230,
      plannedTotal: 25230,
      realizedTotal: 5664,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "cdf16862-2e28-5317-af1e-7582ae8fd995",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "b2638664-d2b3-551d-bd43-67384b4d5b7a",
      chantierId: "877ef83c-4d4e-57fb-835c-f3c2a143a845",
      sourceSheet: "2015-16",
      sourceRow: 43,
      rawName: "JORIS GIRARD",
      clientKey: "joris-girard",
      clientName: "Joris Girard",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 5360,
      plannedTotal: 5360,
      realizedTotal: 5360,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "ee5683b1-21db-58f2-b9af-eb8dc07959cf",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "7920e1da-b019-575f-8fae-ef8d7d61ea16",
      chantierId: "76cf6223-c7ae-52fb-bee3-42c86abef416",
      sourceSheet: "2015-16",
      sourceRow: 44,
      rawName: "SAITER",
      clientKey: "saiter",
      clientName: "Saiter",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 4524,
      plannedTotal: 4524,
      realizedTotal: 4524,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "40b95992-01b9-554d-8b8b-c68addc2f861",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "38264fb2-6003-5591-9a3f-56b7ddd27b8e",
      chantierId: "9bd4361c-aa4e-5aaa-9de4-77d892a85577",
      sourceSheet: "2015-16",
      sourceRow: 45,
      rawName: "BUNEL terrasse",
      clientKey: "bunel-terrasse",
      clientName: "BUNEL terrasse",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 2570,
      plannedTotal: 2570,
      realizedTotal: 2570,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "1a787327-2a35-51a2-8111-3d32722c141b",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "178a8051-9086-55f0-be75-e1e86a637e1d",
      chantierId: "bba58610-d611-5a59-ad19-658205e77643",
      sourceSheet: "2015-16",
      sourceRow: 46,
      rawName: "REANULT 2B peinture",
      clientKey: "reanult-2b-peinture",
      clientName: "REANULT 2B peinture",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 2900,
      plannedTotal: 2900,
      realizedTotal: 2900,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "9ff4548d-e79c-574c-b16e-b81aa2a65492",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "27aeb192-980b-5eb1-b1c4-b065fcce2be1",
      chantierId: "773f4489-27b4-5673-82b0-1d4e2a1302b0",
      sourceSheet: "2015-16",
      sourceRow: 47,
      rawName: "DUVAL à moult",
      clientKey: "duval-a-moult",
      clientName: "DUVAL à moult",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 25000,
      plannedTotal: 25000,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "8e874f78-2813-593f-b281-1f9ba5e530d9",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "8922a72b-704c-56eb-99e4-74aa9b417788",
      chantierId: "432ee26c-3a6b-5bb5-aadb-296130de208c",
      sourceSheet: "2015-16",
      sourceRow: 48,
      rawName: "RF CORNILLE",
      clientKey: "rf-cornille",
      clientName: "Rf Cornille",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 8871,
      plannedTotal: 8871,
      realizedTotal: 8871,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "9ded71da-e32b-564a-8d1d-59c7f892e00c",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "ad6a2a15-afdc-52e7-9a38-e9b0ff40f1db",
      chantierId: "66f65d13-0a77-5fcf-a239-6aca25ddebaf",
      sourceSheet: "2015-16",
      sourceRow: 49,
      rawName: "DUBOIS CHAIGNET",
      clientKey: "dubois-chaignet",
      clientName: "Dubois Chaignet",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 2625,
      plannedTotal: 2625,
      realizedTotal: 2625,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "27939187-c8a3-52eb-9170-936dab92edd0",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "30bcb9be-0495-5fc7-91ed-1cae6b6ab4c3",
      chantierId: "fdd171db-d2d6-507b-99cd-a5ef30cb02e0",
      sourceSheet: "2015-16",
      sourceRow: 50,
      rawName: "RF LOHARD",
      clientKey: "rf-lohard",
      clientName: "Rf Lohard",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 6717,
      plannedTotal: 6717,
      realizedTotal: 6717,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "9ef25d96-012c-566d-9483-b976288f8f69",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "fd7ec355-1a0b-5a5a-999a-9e84e3992a4f",
      chantierId: "927af25d-1ebf-59b8-9da0-1729116f6853",
      sourceSheet: "2015-16",
      sourceRow: 51,
      rawName: "RF MANGION",
      clientKey: "rf-mangion",
      clientName: "Rf Mangion",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 6830,
      plannedTotal: 6830,
      realizedTotal: 6830,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "cea88f74-ac6f-5a27-84d4-4d9902ad521d",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "caa17254-5332-59dc-9551-41d54f362bdd",
      chantierId: "bf978584-eba4-5168-984c-6bf257199b5c",
      sourceSheet: "2015-16",
      sourceRow: 52,
      rawName: "RF RICHARD",
      clientKey: "rf-richard",
      clientName: "Rf Richard",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 5146,
      plannedTotal: 5146,
      realizedTotal: 5146,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "25cb845e-0322-53bc-9e03-ab8601b07892",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "2b3f493d-dbdb-5259-b4c9-bd23486040c8",
      chantierId: "8fb427b2-f91e-5f8a-a3c5-e5058775ad5d",
      sourceSheet: "2015-16",
      sourceRow: 53,
      rawName: "LEBOUCHER ext",
      clientKey: "leboucher-ext",
      clientName: "LEBOUCHER ext",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 10976,
      plannedTotal: 10979,
      realizedTotal: 10976,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "65e612c7-67f1-58d4-8992-57d79241f6a0",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "e928794b-9243-57aa-ae01-9c28eadbcf5c",
      chantierId: "f477f874-79bb-588c-861a-6a2fd787bd6b",
      sourceSheet: "2015-16",
      sourceRow: 54,
      rawName: "ROSELIER",
      clientKey: "roselier",
      clientName: "Roselier",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 14259,
      plannedTotal: 14279,
      realizedTotal: 9910,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "91abaa4c-a470-5bf8-9298-0474f6c31565",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "5d2d3b82-a599-58bd-9abb-e280b1ea2938",
      chantierId: "4d533eee-3012-50e8-8d61-9836f5068e07",
      sourceSheet: "2015-16",
      sourceRow: 55,
      rawName: "BILLE francois",
      clientKey: "bille-francois",
      clientName: "BILLE francois",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 5756,
      plannedTotal: 5756,
      realizedTotal: 5756,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "98677761-d515-5476-bd0e-1f2c34f6bf7f",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "4b4a9f76-6211-58a5-a3aa-982595b7cbd2",
      chantierId: "a799a3d2-ddb2-5962-8824-940b2dc58853",
      sourceSheet: "2015-16",
      sourceRow: 56,
      rawName: "BOUILLARD",
      clientKey: "bouillard",
      clientName: "Bouillard",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 13155,
      plannedTotal: 11058,
      realizedTotal: 11058,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "f3fbc3c3-3f5a-5760-9c14-12115d5bbae1",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "b9a95caa-9ede-5d1d-96e7-8a556cd266e8",
      chantierId: "815e7f5a-af7d-55c3-94b5-fd7286f5ee52",
      sourceSheet: "2015-16",
      sourceRow: 57,
      rawName: "DE SOUSA",
      clientKey: "de-sousa",
      clientName: "De Sousa",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 9005,
      plannedTotal: 2253,
      realizedTotal: 2253,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "867726e7-cb6e-5897-b38b-f2f57828c49f",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "cb423553-357a-5de9-bf1e-b663a9547a5b",
      chantierId: "c47766b4-e317-5eb7-97cd-e21d6e58c191",
      sourceSheet: "2015-16",
      sourceRow: 58,
      rawName: "TANGUY",
      clientKey: "tanguy",
      clientName: "Tanguy",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 3015,
      plannedTotal: 3015,
      realizedTotal: 3015,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "9d1d6df6-9ed2-5eb0-9739-0e577a61cfa6",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "0824a314-3602-5ffd-9241-0eb3c8a22b50",
      chantierId: "2288f374-a8d8-54b3-91b9-5fa5fecb3c16",
      sourceSheet: "2015-16",
      sourceRow: 59,
      rawName: "L'audacieuse",
      clientKey: "l-audacieuse",
      clientName: "L'audacieuse",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 2467,
      plannedTotal: 2467,
      realizedTotal: 2467,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "6bff09b6-a1a1-5ff4-a889-859288921ab5",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "8cead5de-dd96-5840-88dc-18adedefb288",
      chantierId: "3e82f018-4305-5980-a2a0-0a11870954d3",
      sourceSheet: "2015-16",
      sourceRow: 60,
      rawName: "corbion",
      clientKey: "corbion",
      clientName: "Corbion",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 4518,
      plannedTotal: 4518,
      realizedTotal: 4518,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "dc260abf-4d72-5296-b94a-883f5428170d",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "b816c25f-3734-5df9-939e-cb3803a2ba4e",
      chantierId: "ff9be48c-4892-531b-a6d4-5cc91568d505",
      sourceSheet: "2015-16",
      sourceRow: 61,
      rawName: "BACON",
      clientKey: "bacon",
      clientName: "Bacon",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 19636,
      plannedTotal: 5000,
      realizedTotal: 5000,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "386fb6f0-9c31-5a96-9edf-c2b6368e4177",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "88436532-ded3-5f85-a030-8357fa2356a8",
      chantierId: "4e9346d8-af04-5494-8925-8cfb8336247f",
      sourceSheet: "2015-16",
      sourceRow: 62,
      rawName: "lotton",
      clientKey: "lotton",
      clientName: "Lotton",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 4509,
      plannedTotal: 4509,
      realizedTotal: 4509,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "dca3befb-4cab-5395-9088-f49626bfcd30",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "a470802a-4281-5c13-9e28-9c1200f6006e",
      chantierId: "79710362-a1a8-5316-a934-64566600b2ad",
      sourceSheet: "2015-16",
      sourceRow: 63,
      rawName: "SAMSON",
      clientKey: "samson",
      clientName: "Samson",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 9596,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "dd23af4d-8b41-5a33-ba72-f56471f55bbb",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "f55d2c78-2d47-51af-9d04-0f249633f471",
      chantierId: "ef604cb1-d2f3-541b-adf8-3079930175f0",
      sourceSheet: "2015-16",
      sourceRow: 64,
      rawName: "GASTON samuel",
      clientKey: "gaston-samuel",
      clientName: "GASTON samuel",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 7288,
      plannedTotal: 7287,
      realizedTotal: 7287,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "807cefe6-3656-5677-95ae-8983f4cc4e29",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "b2371668-639e-5418-a786-2f69d63d967f",
      chantierId: "a5ecb743-7d25-5f66-a200-fee77b1c8e80",
      sourceSheet: "2015-16",
      sourceRow: 65,
      rawName: "SOCHON",
      clientKey: "sochon",
      clientName: "Sochon",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 12340,
      plannedTotal: 12339,
      realizedTotal: 12339,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "15267e1d-5f10-579e-81c8-f0287bedb66e",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "47b14f0e-8eaa-55c3-9e70-ea0591a008c4",
      chantierId: "a22077d6-680c-5f88-8d9d-16cff457834e",
      sourceSheet: "2015-16",
      sourceRow: 66,
      rawName: "CHAUVEL",
      clientKey: "chauvel",
      clientName: "Chauvel",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 28500,
      plannedTotal: 28498,
      realizedTotal: 28442,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "4c1ef0c8-d344-5722-8a28-e8ae6d825554",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "c94a038a-f6d7-53ab-b368-1cd16330fcf0",
      chantierId: "c3a415e3-70a9-50a6-b55e-7f18f74ad230",
      sourceSheet: "2015-16",
      sourceRow: 67,
      rawName: "LEMANISSIER",
      clientKey: "lemanissier",
      clientName: "Lemanissier",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 10874,
      plannedTotal: 2278,
      realizedTotal: 2278,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "9879b46f-9d6a-5d96-8eb9-d18f16a97a2e",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "8f3a7947-5076-5a3a-87bc-68e75d308577",
      chantierId: "1a83c839-87e3-5e5d-b08f-a1a23249affc",
      sourceSheet: "2015-16",
      sourceRow: 68,
      rawName: "LEYEUCH",
      clientKey: "leyeuch",
      clientName: "Leyeuch",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 2878,
      plannedTotal: 2878,
      realizedTotal: 2878,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "f2beb9b6-09a9-52d0-a4bc-500be2ba0469",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "6607d4d7-233a-5b52-bd5b-79db61560e72",
      chantierId: "874967cb-ed7c-5bb1-bc6f-f8191f330b36",
      sourceSheet: "2015-16",
      sourceRow: 69,
      rawName: "GOUESLARD",
      clientKey: "goueslard",
      clientName: "Goueslard",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 7492,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "26516877-2b42-548d-bfdf-c26835330983",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "906aae55-c071-550e-a2a8-1a5f2e9f3077",
      chantierId: "24fc406e-066a-51b1-a2bc-4c3ec7128612",
      sourceSheet: "2015-16",
      sourceRow: 70,
      rawName: "rf SORTON",
      clientKey: "rf-sorton",
      clientName: "Rf SORTON",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 8334,
      plannedTotal: 8000,
      realizedTotal: 8000,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "169ffe5e-f095-5662-853c-5ebe2d321c01",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "dc068f7a-2b37-559f-8701-699d8a04fafb",
      chantierId: "221f83cc-8ecf-5013-844e-82c5a7726de8",
      sourceSheet: "2015-16",
      sourceRow: 71,
      rawName: "rf tardif",
      clientKey: "rf-tardif",
      clientName: "Rf tardif",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 7347,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "ca3602c1-1027-5e7e-960e-4eb5a8fa3e3d",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "2c5f1163-d2da-5318-b814-03318eb41b2c",
      chantierId: "8efeb03e-8118-5080-9e56-80deca53b6d9",
      sourceSheet: "2015-16",
      sourceRow: 72,
      rawName: "jouannot",
      clientKey: "jouannot",
      clientName: "Jouannot",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 7331,
      plannedTotal: 3802.8,
      realizedTotal: 3803,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "2846cf09-b4b1-5360-ac02-4e00198e1de8",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "f505f120-c09d-5d5a-9a7c-97a36ac13748",
      chantierId: "170ce6dc-877e-5b5d-9e6c-fa289096c5d8",
      sourceSheet: "2015-16",
      sourceRow: 73,
      rawName: "stab",
      clientKey: "stab",
      clientName: "Stab",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 2950,
      plannedTotal: 2950,
      realizedTotal: 2250,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "5eded134-6658-5b67-b6b6-8ef01e3ff37a",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "647a5d0a-190b-5f8a-a773-3f8221958d10",
      chantierId: "c5af077b-bdec-5fea-bfed-77c09c369da1",
      sourceSheet: "2015-16",
      sourceRow: 74,
      rawName: "guilloux",
      clientKey: "guilloux",
      clientName: "Guilloux",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 2980,
      plannedTotal: 3830,
      realizedTotal: 3830,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "6a9f3d5c-62fb-569e-92f2-2bd7bec7955e",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "d84cabe1-6ab6-5b91-8ce1-a60e8ce3e7aa",
      chantierId: "05119bc7-3abf-5f00-80f6-5764ff38c493",
      sourceSheet: "2015-16",
      sourceRow: 75,
      rawName: "rf sabatier",
      clientKey: "rf-sabatier",
      clientName: "Rf sabatier",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 9882,
      plannedTotal: 9882,
      realizedTotal: 9967,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "3ff7511e-7756-533b-a289-f85a20bd8ed5",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "8b226ef3-a9d9-5baf-bd84-c491711070e4",
      chantierId: "4e8671f0-9dbb-52f0-b821-ea8aeb255669",
      sourceSheet: "2015-16",
      sourceRow: 76,
      rawName: "rf russ",
      clientKey: "rf-russ",
      clientName: "Rf russ",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 7987,
      plannedTotal: 7987,
      realizedTotal: 7987,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "08545f4c-d44a-58e5-892f-5b13be9fdab2",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "97bdebb9-e591-559f-b6da-9e6f45e65291",
      chantierId: "01f91311-4f18-5b0f-85bb-7e22ea16968e",
      sourceSheet: "2015-16",
      sourceRow: 77,
      rawName: "sarl ecs bretteville",
      clientKey: "sarl-ecs-bretteville",
      clientName: "Sarl ecs bretteville",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 15500,
      plannedTotal: 15500,
      realizedTotal: 7540,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "bc4118d4-7050-5d7f-8bf1-bb0e7a03b0b2",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "17745acf-af83-52d9-919a-8c2fca805436",
      chantierId: "71bf3564-ee4e-5062-be2f-e50eb0257032",
      sourceSheet: "2015-16",
      sourceRow: 78,
      rawName: "GODIN",
      clientKey: "godin",
      clientName: "Godin",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 1521,
      plannedTotal: 1521,
      realizedTotal: 1521,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "5c9c5e51-9edd-5139-b3d1-be524ce78e0b",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "54cec068-a1a4-519b-8bf4-9a21f5069b5f",
      chantierId: "24447235-60e5-5809-bd43-10edc11260df",
      sourceSheet: "2015-16",
      sourceRow: 79,
      rawName: "fossey",
      clientKey: "fossey",
      clientName: "Fossey",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 550,
      plannedTotal: 550,
      realizedTotal: 550,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "05b0501b-23bb-5bdc-8ce5-407afaa85862",
      exerciseId: "8e1890be-b944-5602-b61c-65edeb496b36",
      clientId: "8764c36a-d9f1-52db-ae1e-3680fda290e9",
      chantierId: "479a6404-e445-5aae-95e8-9021b9b5be8f",
      sourceSheet: "2015-16",
      sourceRow: 80,
      rawName: "jegou",
      clientKey: "jegou",
      clientName: "Jegou",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 510,
      plannedTotal: 510,
      realizedTotal: 510,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "9583fb10-3f73-5048-a9bb-d8ccddd4fc64",
      exerciseId: "6ee923a6-4d3b-5253-82bf-0159efa72a1a",
      clientId: "15d51942-1bf6-5836-93a4-894f64874d3c",
      chantierId: "ff355e8d-83ba-54a8-895a-b93da1a4939f",
      sourceSheet: "2016-17",
      sourceRow: 6,
      rawName: "pasquet menuiseries",
      clientKey: "pasquet-menuiseries",
      clientName: "Pasquet menuiseries",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 0,
      plannedTotal: 1811,
      realizedTotal: 1811,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "c802f8fb-dcc6-532c-90b0-2e230f29daf6",
      exerciseId: "6ee923a6-4d3b-5253-82bf-0159efa72a1a",
      clientId: "4e100c13-bcd7-5abf-aea1-7669ace1287f",
      chantierId: "83c8d4a6-a3bf-52c2-9b06-9a1e0cbe9b70",
      sourceSheet: "2016-17",
      sourceRow: 7,
      rawName: "letourneur",
      clientKey: "letourneur",
      clientName: "Letourneur",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 57015,
      plannedTotal: 35000,
      realizedTotal: 39915,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "c568c6ba-2338-5765-b1c3-fb75f640631f",
      exerciseId: "6ee923a6-4d3b-5253-82bf-0159efa72a1a",
      clientId: "36103707-1e82-5e44-88d3-1bb97e331971",
      chantierId: "dda2774d-e087-5c78-b76b-2b06dbb394c3",
      sourceSheet: "2016-17",
      sourceRow: 8,
      rawName: "college sacre cœur",
      clientKey: "college-sacre-c-ur",
      clientName: "College sacre cœur",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 76016,
      plannedTotal: 38000,
      realizedTotal: 36816,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "1f273396-102a-549a-ab98-029753f96204",
      exerciseId: "6ee923a6-4d3b-5253-82bf-0159efa72a1a",
      clientId: "a9683211-8ab3-5f54-ad8c-b916354af2ab",
      chantierId: "346a047f-34a2-537d-9c5d-a88741df83b5",
      sourceSheet: "2016-17",
      sourceRow: 9,
      rawName: "suard",
      clientKey: "suard",
      clientName: "Suard",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 16928,
      plannedTotal: 16928,
      realizedTotal: 16928,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "72cef4ec-8ae4-596a-b2a4-fcde796ed6a1",
      exerciseId: "6ee923a6-4d3b-5253-82bf-0159efa72a1a",
      clientId: "a704a702-4837-5d29-9f16-0923e7fd0575",
      chantierId: "d65cf946-c5f9-5c4f-914c-8ac39e6460e5",
      sourceSheet: "2016-17",
      sourceRow: 10,
      rawName: "marie nadine",
      clientKey: "marie-nadine",
      clientName: "Marie nadine",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 19445,
      plannedTotal: 17360,
      realizedTotal: 19443,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "ddf3af65-d843-561d-baf9-6908b4974784",
      exerciseId: "6ee923a6-4d3b-5253-82bf-0159efa72a1a",
      clientId: "71293e97-873f-532c-91b2-b9b1daed0d47",
      chantierId: "799a4c20-68aa-5f18-8f23-f33892b00cae",
      sourceSheet: "2016-17",
      sourceRow: 11,
      rawName: "delahayes",
      clientKey: "delahayes",
      clientName: "Delahayes",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 12193,
      plannedTotal: 12193,
      realizedTotal: 12193,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "e86c84df-87ba-5eeb-9985-136fdf64e92b",
      exerciseId: "6ee923a6-4d3b-5253-82bf-0159efa72a1a",
      clientId: "50ffe008-3729-5864-a31a-570e676beec9",
      chantierId: "77822d69-a49f-5657-9c9d-06b0dcdf4952",
      sourceSheet: "2016-17",
      sourceRow: 12,
      rawName: "poulain",
      clientKey: "poulain",
      clientName: "Poulain",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 30680,
      plannedTotal: 30684,
      realizedTotal: 30684,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "729f37ed-f7eb-56bf-9fa4-13944db4b726",
      exerciseId: "6ee923a6-4d3b-5253-82bf-0159efa72a1a",
      clientId: "27825179-16b6-5d45-854f-d03a7e174701",
      chantierId: "0948e886-a65b-514b-bb03-2e0f15a1a34b",
      sourceSheet: "2016-17",
      sourceRow: 13,
      rawName: "cointo",
      clientKey: "cointo",
      clientName: "Cointo",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 0,
      caContrat: 3893,
      plannedTotal: 3893,
      realizedTotal: 3893,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    }
  ])
}
