mutation @transaction {
  lines006: previsionnelLine_upsertMany(data: [
    {
      id: "175bba0d-9cf9-5990-b077-aef884876b12",
      exerciseId: "ef167b0f-b2f5-57cf-ba66-bef48a5a8892",
      clientId: "df8161e2-bf64-51dd-8077-4955216aadb6",
      chantierId: "f174c085-e248-519a-abe5-7a7ddc7c0110",
      sourceSheet: "2017-18",
      sourceRow: 37,
      rawName: "Rousseau",
      clientKey: "rousseau",
      clientName: "Rousseau",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 44277,
      caContrat: 44277,
      plannedTotal: 44276.52,
      realizedTotal: 41391.28,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "73345f94-c093-52e8-9d3b-a501c43d07ee",
      exerciseId: "ef167b0f-b2f5-57cf-ba66-bef48a5a8892",
      clientId: "2bbd101f-c21a-54f3-9aaf-b3efa649934e",
      chantierId: "13065896-5fac-537c-8cf0-edf28de4c06c",
      sourceSheet: "2017-18",
      sourceRow: 38,
      rawName: "thomann",
      clientKey: "thomann",
      clientName: "Thomann",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 4085,
      caContrat: 4085,
      plannedTotal: 4085,
      realizedTotal: 4085,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "20536d10-8301-57d3-bb7c-22493314f11e",
      exerciseId: "ef167b0f-b2f5-57cf-ba66-bef48a5a8892",
      clientId: "be6c935a-0223-5358-a96d-6ec71813023b",
      chantierId: "c02cc6e9-6b37-5446-add6-89fc18e2ca9a",
      sourceSheet: "2017-18",
      sourceRow: 39,
      rawName: "Gabriel",
      clientKey: "gabriel",
      clientName: "Gabriel",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 65791.68,
      caContrat: 65791.68,
      plannedTotal: 53381.46,
      realizedTotal: 33484.94,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "7c4c2c59-e426-5538-b767-52361d1cc2dc",
      exerciseId: "ef167b0f-b2f5-57cf-ba66-bef48a5a8892",
      clientId: "7d336cfd-7d32-5485-9c6a-9f85bf233c44",
      chantierId: "56ea9fe7-d5bf-5a9b-9c48-2e4b563d8e61",
      sourceSheet: "2017-18",
      sourceRow: 40,
      rawName: "ccs international",
      clientKey: "ccs-international",
      clientName: "Ccs international",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 8232,
      caContrat: 8232,
      plannedTotal: 8232,
      realizedTotal: 8232,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "604c6ef4-c23f-5dac-9ba4-c664dc466c5a",
      exerciseId: "ef167b0f-b2f5-57cf-ba66-bef48a5a8892",
      clientId: "aabf3793-b510-5813-adaf-8d702ca3e9b5",
      chantierId: "7b824d67-e1f1-534d-a8c3-ffc72a5cc7cb",
      sourceSheet: "2017-18",
      sourceRow: 41,
      rawName: "lequitte",
      clientKey: "lequitte",
      clientName: "Lequitte",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 790.4,
      caContrat: 790.4,
      plannedTotal: 790,
      realizedTotal: 790,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "82685de6-fcd9-58b5-88be-b150c2ef13e0",
      exerciseId: "ef167b0f-b2f5-57cf-ba66-bef48a5a8892",
      clientId: "5291a45f-d407-52b6-92da-3cb961726cd1",
      chantierId: "27966312-f2a1-52b8-9270-369c22c8f4da",
      sourceSheet: "2017-18",
      sourceRow: 42,
      rawName: "pelloin",
      clientKey: "pelloin",
      clientName: "Pelloin",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 6038,
      caContrat: 6038,
      plannedTotal: 6038.66,
      realizedTotal: 6039.06,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "0dfb20da-370b-533a-bcb2-d6bea0d774f4",
      exerciseId: "ef167b0f-b2f5-57cf-ba66-bef48a5a8892",
      clientId: "a5b5d6e4-0dd2-550c-84ce-76d3f20bf0a1",
      chantierId: "e4b4ef0d-4635-5e99-af90-c4057ad29793",
      sourceSheet: "2017-18",
      sourceRow: 43,
      rawName: "mealet",
      clientKey: "mealet",
      clientName: "Mealet",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 4299,
      caContrat: 4299,
      plannedTotal: 4299,
      realizedTotal: 4299,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "9603e63e-dc54-5227-a904-c45c12e0fbb6",
      exerciseId: "ef167b0f-b2f5-57cf-ba66-bef48a5a8892",
      clientId: "18193188-c883-5883-99a0-fe1850f43120",
      chantierId: "23281466-d684-5800-8c62-0e9096649a75",
      sourceSheet: "2017-18",
      sourceRow: 44,
      rawName: "camping",
      clientKey: "camping",
      clientName: "Camping",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 7135.16,
      caContrat: 7135.16,
      plannedTotal: 7135.16,
      realizedTotal: 7135,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "63ba95ba-a0d5-5220-86ef-e7ac3592e093",
      exerciseId: "ef167b0f-b2f5-57cf-ba66-bef48a5a8892",
      clientId: "2e33ddf3-3ee9-57d8-89e2-eaf64878f28d",
      chantierId: "ab5b2f9a-9cd7-50e5-8239-ff7557b5716d",
      sourceSheet: "2017-18",
      sourceRow: 45,
      rawName: "sci fill st sylvain",
      clientKey: "sci-fill-st-sylvain",
      clientName: "Sci fill st sylvain",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 34606,
      caContrat: 34606,
      plannedTotal: 34606.27,
      realizedTotal: 18801,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "d31b3370-8d09-5b7d-8e09-006ee6c35946",
      exerciseId: "ef167b0f-b2f5-57cf-ba66-bef48a5a8892",
      clientId: "fb3bc8e5-f056-5d4c-9cc4-b47785e3d9c9",
      chantierId: "1457ee42-726d-55e8-af83-9e8577cf95f8",
      sourceSheet: "2017-18",
      sourceRow: 46,
      rawName: "euromatec",
      clientKey: "euromatec",
      clientName: "Euromatec",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 1266.4,
      caContrat: 1266,
      plannedTotal: 1266,
      realizedTotal: 1266,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "c70f8ebe-961d-51fe-af28-34ff55f96cb3",
      exerciseId: "ef167b0f-b2f5-57cf-ba66-bef48a5a8892",
      clientId: "e180fe28-8c74-5f51-975e-57e5f9edb9e3",
      chantierId: "55c639be-e8f6-56d6-869f-a7c5ed982c5f",
      sourceSheet: "2017-18",
      sourceRow: 47,
      rawName: "ledorze",
      clientKey: "ledorze",
      clientName: "Ledorze",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 14681.81,
      caContrat: 14681.81,
      plannedTotal: 7978.52,
      realizedTotal: 7978.98,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "f854b8d5-be72-5a4c-86f0-8c56d36106b5",
      exerciseId: "ef167b0f-b2f5-57cf-ba66-bef48a5a8892",
      clientId: "4682ebd1-a863-5f7b-aab5-0c791d3415fa",
      chantierId: "ca90d989-9d74-5c23-8d63-5c24e144dff3",
      sourceSheet: "2017-18",
      sourceRow: 48,
      rawName: "lecomte",
      clientKey: "lecomte",
      clientName: "Lecomte",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 13725,
      caContrat: 13725,
      plannedTotal: 13725,
      realizedTotal: 13725,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "3bc12c51-536d-5d7f-b4c7-118e1bb5ad4c",
      exerciseId: "ef167b0f-b2f5-57cf-ba66-bef48a5a8892",
      clientId: "c15030ca-4c32-5a0a-9411-04bed1713678",
      chantierId: "e3451bba-c6ba-5239-bd80-2e61227dab47",
      sourceSheet: "2017-18",
      sourceRow: 49,
      rawName: "bresson",
      clientKey: "bresson",
      clientName: "Bresson",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 17881,
      caContrat: 17881,
      plannedTotal: 17881,
      realizedTotal: 17881,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "0dac1f29-2ee3-592d-8a8d-883afeaacfa9",
      exerciseId: "ef167b0f-b2f5-57cf-ba66-bef48a5a8892",
      clientId: "89a9dcab-b9b2-55e0-abab-cf17801f94c5",
      chantierId: "2df3242d-ced3-52a6-ac91-93bec3804b71",
      sourceSheet: "2017-18",
      sourceRow: 50,
      rawName: "MORLET blonville sur mer",
      clientKey: "morlet-blonville-sur-mer",
      clientName: "MORLET blonville sur mer",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 79536.61,
      caContrat: 79536,
      plannedTotal: 32678,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "5794067d-4c08-5191-b9f6-22f405ee8ae4",
      exerciseId: "ef167b0f-b2f5-57cf-ba66-bef48a5a8892",
      clientId: "35796466-74cf-5644-8df6-101a9b274fa8",
      chantierId: "4402ea46-f05c-5640-9e55-b42282915fb0",
      sourceSheet: "2017-18",
      sourceRow: 51,
      rawName: "bihel sbtp",
      clientKey: "bihel-sbtp",
      clientName: "Bihel sbtp",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 1285,
      caContrat: 1285,
      plannedTotal: 1285,
      realizedTotal: 1285,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "70a5d05c-9eca-5030-abdd-3a2c8d1c8344",
      exerciseId: "ef167b0f-b2f5-57cf-ba66-bef48a5a8892",
      clientId: "873b5e0b-2c45-5564-bc46-4527d324d725",
      chantierId: "d2040d7a-91f5-5e34-a20f-98ce407c732a",
      sourceSheet: "2017-18",
      sourceRow: 52,
      rawName: "estorges",
      clientKey: "estorges",
      clientName: "Estorges",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 16070,
      caContrat: 16070.35,
      plannedTotal: 16070,
      realizedTotal: 12810,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "77cfb8d6-1a1f-56bf-af2f-42e10fb95490",
      exerciseId: "ef167b0f-b2f5-57cf-ba66-bef48a5a8892",
      clientId: "41f5b7b7-901d-5d9b-9d22-c55a592d4f0d",
      chantierId: "e3f81bed-e1d4-53cc-88ab-b4e560600077",
      sourceSheet: "2017-18",
      sourceRow: 53,
      rawName: "rf plancher",
      clientKey: "rf-plancher",
      clientName: "Rf plancher",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 1200,
      caContrat: 1200,
      plannedTotal: 1200,
      realizedTotal: 1200,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "3b0e77f2-1338-598c-9f81-61edb4b8e1f0",
      exerciseId: "ef167b0f-b2f5-57cf-ba66-bef48a5a8892",
      clientId: "a8c02ab3-d662-5392-8c1e-7bc82b020c2f",
      chantierId: "84afc0f8-c596-59ef-8e7c-ee9d6061d676",
      sourceSheet: "2017-18",
      sourceRow: 54,
      rawName: "josse",
      clientKey: "josse",
      clientName: "Josse",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 291,
      caContrat: 291,
      plannedTotal: 291,
      realizedTotal: 291,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "86c49786-e3b9-5180-81e5-effd87429e0d",
      exerciseId: "ef167b0f-b2f5-57cf-ba66-bef48a5a8892",
      clientId: "a65f7c59-5102-5c98-b420-75793e8aeeea",
      chantierId: "eb92c3d8-fcab-54a9-a795-232f241529b5",
      sourceSheet: "2017-18",
      sourceRow: 55,
      rawName: "Germain",
      clientKey: "germain",
      clientName: "Germain",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 107313,
      caContrat: 107313,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "973421de-25dd-5347-9fc3-f82a2f20342e",
      exerciseId: "ef167b0f-b2f5-57cf-ba66-bef48a5a8892",
      clientId: "97390eb4-448c-53dd-a8a8-e70906af733e",
      chantierId: "ccc0adef-ffa8-5d50-b112-71ee80935752",
      sourceSheet: "2017-18",
      sourceRow: 56,
      rawName: "Morotti",
      clientKey: "morotti",
      clientName: "Morotti",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 12732.3,
      caContrat: 12732.3,
      plannedTotal: 12732,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "717cbc63-e7da-5d8c-915b-843575860059",
      exerciseId: "ef167b0f-b2f5-57cf-ba66-bef48a5a8892",
      clientId: "e803033c-d85d-5cee-bde5-ca7903b50ec0",
      chantierId: "7716a47e-ef63-51dc-b828-d9b31971b9ea",
      sourceSheet: "2017-18",
      sourceRow: 57,
      rawName: "martin",
      clientKey: "martin",
      clientName: "Martin",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 3441,
      caContrat: 3441,
      plannedTotal: 3441,
      realizedTotal: 3441,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "c7bc586e-569e-5cb8-b4f7-74e44f2f1411",
      exerciseId: "ef167b0f-b2f5-57cf-ba66-bef48a5a8892",
      clientId: "cf7a39dc-a169-53b3-8c73-e6b3f600f1f0",
      chantierId: "2f67689e-cd3c-5138-9097-868de9d3a590",
      sourceSheet: "2017-18",
      sourceRow: 58,
      rawName: "taillepied",
      clientKey: "taillepied",
      clientName: "Taillepied",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 8169,
      caContrat: 8169,
      plannedTotal: 8169,
      realizedTotal: 8169,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "066c355d-2f62-50c7-8f9c-f6c16dfb9522",
      exerciseId: "ef167b0f-b2f5-57cf-ba66-bef48a5a8892",
      clientId: "71c2e40a-04a2-5f13-b050-62bb30e29319",
      chantierId: "1ca6c6af-4657-51eb-822b-009fb1fad27c",
      sourceSheet: "2017-18",
      sourceRow: 59,
      rawName: "naceur",
      clientKey: "naceur",
      clientName: "Naceur",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 2676,
      caContrat: 2676,
      plannedTotal: 2676,
      realizedTotal: 2676,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "27dce055-5c7b-596e-9332-53d0b1a93e7c",
      exerciseId: "ef167b0f-b2f5-57cf-ba66-bef48a5a8892",
      clientId: "337bea63-9f45-5e6b-a26e-443d275d0a80",
      chantierId: "f6279857-7681-5c72-a36b-a3b64f0411e0",
      sourceSheet: "2017-18",
      sourceRow: 60,
      rawName: "QUEMENER",
      clientKey: "quemener",
      clientName: "Quemener",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 44671,
      caContrat: 44671,
      plannedTotal: 20392.24,
      realizedTotal: 5332,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "0a4fcc02-c5bb-5977-b2ed-be9817d6dd8e",
      exerciseId: "ef167b0f-b2f5-57cf-ba66-bef48a5a8892",
      clientId: "a97b5561-46c3-5960-9d47-34928abeaf84",
      chantierId: "9106f878-a89b-5597-996b-2663e99dfe7c",
      sourceSheet: "2017-18",
      sourceRow: 61,
      rawName: "vandermersch",
      clientKey: "vandermersch",
      clientName: "Vandermersch",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 3191,
      caContrat: 3191.95,
      plannedTotal: 3192,
      realizedTotal: 3192,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "3d96728d-de27-5cea-ab1d-ef145bdf923b",
      exerciseId: "ef167b0f-b2f5-57cf-ba66-bef48a5a8892",
      clientId: "87315d76-3382-5e21-8451-17bb74ae0bef",
      chantierId: "dc803fa3-e5d4-536a-a94b-f5c5d48f26f7",
      sourceSheet: "2017-18",
      sourceRow: 62,
      rawName: "GOULAIN",
      clientKey: "goulain",
      clientName: "Goulain",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 10448,
      caContrat: 10448,
      plannedTotal: 5000,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "94221a8d-604d-5e2b-b34a-0d8b4b131fae",
      exerciseId: "ef167b0f-b2f5-57cf-ba66-bef48a5a8892",
      clientId: "31289dad-22eb-5dd4-8a36-b57d8d811a6d",
      chantierId: "f7d9b146-28c7-580b-b496-448786744d62",
      sourceSheet: "2017-18",
      sourceRow: 63,
      rawName: "AMCM",
      clientKey: "amcm",
      clientName: "Amcm",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 480,
      caContrat: 480,
      plannedTotal: 480,
      realizedTotal: 480,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "0f2e1897-d321-52a8-9808-67fc01efe103",
      exerciseId: "52b3fb59-b13a-5050-a8d5-712bed5d7111",
      clientId: "5ed7f322-572b-5786-810a-45d06c43b691",
      chantierId: "9691bab6-2cce-5aee-a604-fee6c2ddf4c6",
      sourceSheet: "2018-19",
      sourceRow: 6,
      rawName: "PELTIER",
      clientKey: "peltier",
      clientName: "Peltier",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 7082,
      caContrat: 7082,
      plannedTotal: 7562,
      realizedTotal: 7562,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "676923dc-4fdb-5580-a5a3-f1de35f7053d",
      exerciseId: "52b3fb59-b13a-5050-a8d5-712bed5d7111",
      clientId: "89a9dcab-b9b2-55e0-abab-cf17801f94c5",
      chantierId: "cda04b52-7475-55b3-98f2-48a365a6c095",
      sourceSheet: "2018-19",
      sourceRow: 7,
      rawName: "MORLET blonville sur mer",
      clientKey: "morlet-blonville-sur-mer",
      clientName: "MORLET blonville sur mer",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 47888.89,
      caContrat: 47889,
      plannedTotal: 47856.89,
      realizedTotal: 47857,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "556d3365-23ea-581b-b367-6edd3af2d05c",
      exerciseId: "52b3fb59-b13a-5050-a8d5-712bed5d7111",
      clientId: "337bea63-9f45-5e6b-a26e-443d275d0a80",
      chantierId: "e581cc38-8fea-5c7a-9158-9f1135eb7020",
      sourceSheet: "2018-19",
      sourceRow: 8,
      rawName: "QUEMENER",
      clientKey: "quemener",
      clientName: "Quemener",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 25132,
      caContrat: 25132,
      plannedTotal: 25132,
      realizedTotal: 25132,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "08f553f3-5449-591e-a03d-3851f10980bc",
      exerciseId: "52b3fb59-b13a-5050-a8d5-712bed5d7111",
      clientId: "87315d76-3382-5e21-8451-17bb74ae0bef",
      chantierId: "097687b0-5bb4-5f74-b281-42bdf2a6b821",
      sourceSheet: "2018-19",
      sourceRow: 9,
      rawName: "GOULAIN",
      clientKey: "goulain",
      clientName: "Goulain",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 15973,
      caContrat: 15973,
      plannedTotal: 13731,
      realizedTotal: 13731,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "8227c131-5e77-5c06-a540-55fe66ea4223",
      exerciseId: "52b3fb59-b13a-5050-a8d5-712bed5d7111",
      clientId: "cd07fcaa-c6d3-5579-b451-d2de2c7f7a9f",
      chantierId: "da530481-97cd-587d-bd84-6b9c017514cf",
      sourceSheet: "2018-19",
      sourceRow: 10,
      rawName: "GUIBOUT",
      clientKey: "guibout",
      clientName: "Guibout",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 76932,
      caContrat: 76932,
      plannedTotal: 74049,
      realizedTotal: 74049,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "5712643c-e36e-5526-8b06-dab39cf3cfac",
      exerciseId: "52b3fb59-b13a-5050-a8d5-712bed5d7111",
      clientId: "be6c935a-0223-5358-a96d-6ec71813023b",
      chantierId: "deabe919-2c29-53d2-9b9b-72230d1d9577",
      sourceSheet: "2018-19",
      sourceRow: 11,
      rawName: "GABRIEL",
      clientKey: "gabriel",
      clientName: "Gabriel",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 11184,
      caContrat: 11184,
      plannedTotal: 12001.47,
      realizedTotal: 12001,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "d45f572c-2299-55d8-9803-58d2f5082102",
      exerciseId: "52b3fb59-b13a-5050-a8d5-712bed5d7111",
      clientId: "a65f7c59-5102-5c98-b420-75793e8aeeea",
      chantierId: "19fbc716-8422-52ac-b933-1a3d2960608d",
      sourceSheet: "2018-19",
      sourceRow: 12,
      rawName: "GERMAIN",
      clientKey: "germain",
      clientName: "Germain",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 136516,
      caContrat: 136516,
      plannedTotal: 136516.4,
      realizedTotal: 136516,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "c0d7119e-639c-591e-bfd3-1bf9a9bfdcc6",
      exerciseId: "52b3fb59-b13a-5050-a8d5-712bed5d7111",
      clientId: "e180fe28-8c74-5f51-975e-57e5f9edb9e3",
      chantierId: "4a75b0bb-470f-5101-8835-e5425c447b13",
      sourceSheet: "2018-19",
      sourceRow: 13,
      rawName: "LEDORZE",
      clientKey: "ledorze",
      clientName: "Ledorze",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 9088.29,
      caContrat: 9088,
      plannedTotal: 9088,
      realizedTotal: 9088,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "e090e690-26d5-5a66-8114-36d1b30c3a72",
      exerciseId: "52b3fb59-b13a-5050-a8d5-712bed5d7111",
      clientId: "b234d215-fb30-5f41-9666-057ff8a767f3",
      chantierId: "bb01f1d0-bca1-50c2-ba85-2b61e0871a1c",
      sourceSheet: "2018-19",
      sourceRow: 14,
      rawName: "SCI IFL",
      clientKey: "sci-ifl",
      clientName: "Sci Ifl",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 4967,
      caContrat: 4967,
      plannedTotal: 4967,
      realizedTotal: 4967,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "ec5429c4-0d57-5b96-a0c2-ced84a1ac9e7",
      exerciseId: "52b3fb59-b13a-5050-a8d5-712bed5d7111",
      clientId: "b1843c66-02ca-5bf0-85d0-acc9cd9db651",
      chantierId: "74e0c930-7b04-525f-ad70-f41557cbe258",
      sourceSheet: "2018-19",
      sourceRow: 15,
      rawName: "SARL LA FOURNEE",
      clientKey: "sarl-la-fournee",
      clientName: "Sarl La Fournee",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 7697,
      caContrat: 0,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "152e7a2e-cf37-5b23-996a-cada3f7cab9f",
      exerciseId: "52b3fb59-b13a-5050-a8d5-712bed5d7111",
      clientId: "39638c0c-15a0-5bdf-854a-093582175244",
      chantierId: "4d44e7e3-57b2-5db0-bf52-d63c38f68e99",
      sourceSheet: "2018-19",
      sourceRow: 16,
      rawName: "FERARD",
      clientKey: "ferard",
      clientName: "Ferard",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 52246,
      caContrat: 52246,
      plannedTotal: 46041,
      realizedTotal: 46041,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "3e691bca-45d2-5993-900c-33c11d553cef",
      exerciseId: "52b3fb59-b13a-5050-a8d5-712bed5d7111",
      clientId: "1a7936d8-eadd-5a5b-9ce4-90b8d05cc899",
      chantierId: "965728af-ce8c-598c-ba65-c6888c77274c",
      sourceSheet: "2018-19",
      sourceRow: 18,
      rawName: "SCI DES MOTTETS",
      clientKey: "sci-des-mottets",
      clientName: "Sci Des Mottets",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 10544,
      caContrat: 10544,
      plannedTotal: 10543.91,
      realizedTotal: 10544,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "a885cb4b-88d5-505e-ad6c-b4df529379e7",
      exerciseId: "52b3fb59-b13a-5050-a8d5-712bed5d7111",
      clientId: "b50f8932-7be6-5a8b-827c-b90da396ee63",
      chantierId: "08a0b70c-0ec4-5ab6-a144-caa7552bd370",
      sourceSheet: "2018-19",
      sourceRow: 19,
      rawName: "MOREL",
      clientKey: "morel",
      clientName: "Morel",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 128702,
      caContrat: 0,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "7667d6f0-9e19-5666-96c8-a92433be4c07",
      exerciseId: "52b3fb59-b13a-5050-a8d5-712bed5d7111",
      clientId: "e8760822-2896-506a-9518-a9d42326cdec",
      chantierId: "3abb5d42-c1fa-53a3-8093-f2f74eba5c98",
      sourceSheet: "2018-19",
      sourceRow: 22,
      rawName: "TALMAR",
      clientKey: "talmar",
      clientName: "Talmar",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 6420,
      caContrat: 6420,
      plannedTotal: 6420,
      realizedTotal: 6420,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "6cecd14b-c651-5660-90f4-137df4b61543",
      exerciseId: "52b3fb59-b13a-5050-a8d5-712bed5d7111",
      clientId: "ddb230b3-da94-52d8-ac72-b460a5557869",
      chantierId: "00532a5b-35d3-58ff-865d-011285640512",
      sourceSheet: "2018-19",
      sourceRow: 23,
      rawName: "FOUREY",
      clientKey: "fourey",
      clientName: "Fourey",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 3963,
      caContrat: 3963,
      plannedTotal: 3963,
      realizedTotal: 3963,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "581762e6-c2d4-5997-8f28-1ef3a3415ea0",
      exerciseId: "52b3fb59-b13a-5050-a8d5-712bed5d7111",
      clientId: "2c11829c-82b8-5b5a-95d3-21b5e1c02b0d",
      chantierId: "13a83e8b-5942-526d-88cf-811c30a47a96",
      sourceSheet: "2018-19",
      sourceRow: 24,
      rawName: "CHAMPION",
      clientKey: "champion",
      clientName: "Champion",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 1620,
      caContrat: 1620,
      plannedTotal: 2662,
      realizedTotal: 2662,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "59d6ecd8-258f-5f54-9ed1-cd33c9e3768a",
      exerciseId: "52b3fb59-b13a-5050-a8d5-712bed5d7111",
      clientId: "8587a504-3379-547a-b3a8-72b422819d1b",
      chantierId: "02c171eb-8beb-516e-a565-635b3d4c2310",
      sourceSheet: "2018-19",
      sourceRow: 25,
      rawName: "PAPILLON",
      clientKey: "papillon",
      clientName: "Papillon",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 16756,
      caContrat: 16756,
      plannedTotal: 16755.54,
      realizedTotal: 16756,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "2e654ed7-84a4-51e7-9369-01d1529eef6b",
      exerciseId: "52b3fb59-b13a-5050-a8d5-712bed5d7111",
      clientId: "a882dbfa-0c4e-581e-b845-258be79d3015",
      chantierId: "dde3eca3-e42f-5373-9e04-d797573b3bdd",
      sourceSheet: "2018-19",
      sourceRow: 26,
      rawName: "LOPEZ",
      clientKey: "lopez",
      clientName: "Lopez",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 4221,
      caContrat: 4221,
      plannedTotal: 4221,
      realizedTotal: 4221,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "bd6ae980-3970-5e44-ad80-41ae0ffe79ec",
      exerciseId: "52b3fb59-b13a-5050-a8d5-712bed5d7111",
      clientId: "44265dca-dbc9-5fdc-98e5-f413f278dbcb",
      chantierId: "85400c6b-b962-543f-baab-f42544489f2f",
      sourceSheet: "2018-19",
      sourceRow: 27,
      rawName: "MANCHE",
      clientKey: "manche",
      clientName: "Manche",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 62896,
      caContrat: 62896,
      plannedTotal: 61113,
      realizedTotal: 61113,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "7a1ffc42-4fbc-565d-b9b5-57f392d531e4",
      exerciseId: "52b3fb59-b13a-5050-a8d5-712bed5d7111",
      clientId: "97390eb4-448c-53dd-a8a8-e70906af733e",
      chantierId: "ae862dad-e842-5adb-97b3-f889de93f483",
      sourceSheet: "2018-19",
      sourceRow: 28,
      rawName: "MOROTTI",
      clientKey: "morotti",
      clientName: "Morotti",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 8451,
      caContrat: 8451,
      plannedTotal: 8451,
      realizedTotal: 8451,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "e7fee9da-4d6a-53e0-9cc3-3e05c2b5b460",
      exerciseId: "52b3fb59-b13a-5050-a8d5-712bed5d7111",
      clientId: "672b04b8-4d2d-526a-bfaa-328d055635b9",
      chantierId: "a8b9d3a8-9f3b-5fd0-a835-c7d84b2e5f14",
      sourceSheet: "2018-19",
      sourceRow: 29,
      rawName: "DEFLIN",
      clientKey: "deflin",
      clientName: "Deflin",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 1372.46,
      caContrat: 1372.46,
      plannedTotal: 1372,
      realizedTotal: 1372,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "e840de80-997d-5f13-a92a-19cb11dade40",
      exerciseId: "52b3fb59-b13a-5050-a8d5-712bed5d7111",
      clientId: "873b5e0b-2c45-5564-bc46-4527d324d725",
      chantierId: "007be611-d6d2-5ca7-93a3-5f6ef030fc0a",
      sourceSheet: "2018-19",
      sourceRow: 31,
      rawName: "ESTORGES",
      clientKey: "estorges",
      clientName: "Estorges",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 1337,
      caContrat: 1337,
      plannedTotal: 1337,
      realizedTotal: 1337,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "d7b79b87-191a-5e83-a5f5-f8d331a2a548",
      exerciseId: "52b3fb59-b13a-5050-a8d5-712bed5d7111",
      clientId: "f0e10c7d-987d-53cc-a6ce-b11af154eedd",
      chantierId: "1439d931-8193-5f69-9940-ac3b510df42a",
      sourceSheet: "2018-19",
      sourceRow: 32,
      rawName: "LASTELLE",
      clientKey: "lastelle",
      clientName: "Lastelle",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 29492,
      caContrat: 29492,
      plannedTotal: 29492,
      realizedTotal: 29492,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    }
  ])
}
