mutation @transaction {
  lines009: previsionnelLine_upsertMany(data: [
    {
      id: "1fee5cb0-9ad6-5740-ba72-969683c73490",
      exerciseId: "b5ed4097-8e47-5ba3-9af3-ad8898eca4e1",
      clientId: "cbe22469-53b6-5fef-bf23-bd02fafa48af",
      chantierId: "eff14031-cbce-5c31-b395-7ec3f48f412d",
      sourceSheet: "2019-20",
      sourceRow: 69,
      rawName: "ROHRBACH",
      clientKey: "rohrbach",
      clientName: "Rohrbach",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 38516,
      caContrat: 38516,
      plannedTotal: 38525.58,
      realizedTotal: 38526,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "722c829a-e159-500e-b491-a92be4c7a892",
      exerciseId: "b5ed4097-8e47-5ba3-9af3-ad8898eca4e1",
      clientId: "44265dca-dbc9-5fdc-98e5-f413f278dbcb",
      chantierId: "0d06867b-e7f5-5715-9b01-600264ebdd16",
      sourceSheet: "2019-20",
      sourceRow: 70,
      rawName: "MANCHE",
      clientKey: "manche",
      clientName: "Manche",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 1783,
      caContrat: 1783,
      plannedTotal: 1781.5,
      realizedTotal: 1781.5,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "dfb870d1-da0c-515d-b908-04039d8e5adb",
      exerciseId: "b5ed4097-8e47-5ba3-9af3-ad8898eca4e1",
      clientId: "8e480e86-d9eb-59e3-88fb-3d167241483d",
      chantierId: "1b9f3006-ce92-586c-ab73-ee53f3e3fb15",
      sourceSheet: "2019-20",
      sourceRow: 71,
      rawName: "DUPONT CHALESLE iso ext",
      clientKey: "dupont-chalesle-iso-ext",
      clientName: "DUPONT CHALESLE iso ext",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 27209,
      caContrat: 27209,
      plannedTotal: 27209,
      realizedTotal: 27209,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "d9169c1f-7225-5813-8c1f-ef48dd12d819",
      exerciseId: "b5ed4097-8e47-5ba3-9af3-ad8898eca4e1",
      clientId: "13edb9df-a731-5917-9790-1c32484a0cca",
      chantierId: "897de70b-073b-5233-8660-70d0e6c24a04",
      sourceSheet: "2019-20",
      sourceRow: 72,
      rawName: "BRETEAU",
      clientKey: "breteau",
      clientName: "Breteau",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 13034,
      caContrat: 13034,
      plannedTotal: 13034,
      realizedTotal: 13034,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "3c5c942f-09ac-5c41-b912-59e6ae783623",
      exerciseId: "b5ed4097-8e47-5ba3-9af3-ad8898eca4e1",
      clientId: "1c2cb019-48f6-514e-b20d-de354f6a5334",
      chantierId: "ac5df740-f507-5a86-b470-9679f3a7e734",
      sourceSheet: "2019-20",
      sourceRow: 73,
      rawName: "DESFEUX",
      clientKey: "desfeux",
      clientName: "Desfeux",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 3887,
      caContrat: 3887,
      plannedTotal: 3887,
      realizedTotal: 3887,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "e87fc3ed-89ed-5e73-a6e6-50227750c975",
      exerciseId: "b5ed4097-8e47-5ba3-9af3-ad8898eca4e1",
      clientId: "0b969251-2aa0-5b12-81be-9b6a2928e5de",
      chantierId: "0d72ba2a-be7e-560e-a5b7-0cc6c937bb21",
      sourceSheet: "2019-20",
      sourceRow: 74,
      rawName: "DUPONT CHALESLE",
      clientKey: "dupont-chalesle",
      clientName: "Dupont Chalesle",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 19649,
      caContrat: 19649,
      plannedTotal: 19647,
      realizedTotal: 19647.37,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "5aa6ddd2-2a4a-5e5d-af70-dcab695a7f6f",
      exerciseId: "b5ed4097-8e47-5ba3-9af3-ad8898eca4e1",
      clientId: "9bd9f9e3-3f7c-55a8-8838-0a3e4ae22fac",
      chantierId: "6f46d707-cd93-50d6-8e5b-56c006f0ecf8",
      sourceSheet: "2019-20",
      sourceRow: 75,
      rawName: "LOBERGER",
      clientKey: "loberger",
      clientName: "Loberger",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 4190,
      caContrat: 4190,
      plannedTotal: 4190,
      realizedTotal: 4189.52,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "3738a924-f45b-5c11-9b41-95e6aa601814",
      exerciseId: "b5ed4097-8e47-5ba3-9af3-ad8898eca4e1",
      clientId: "de095f46-6e3c-5e8d-9a1f-023e6cc7075d",
      chantierId: "d5a7cc58-cd54-50bc-b464-9f8f7887abfa",
      sourceSheet: "2019-20",
      sourceRow: 76,
      rawName: "DELAMARE",
      clientKey: "delamare",
      clientName: "Delamare",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 4299,
      caContrat: 4299,
      plannedTotal: 4299,
      realizedTotal: 4299,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "eebe226d-5685-5973-bd9b-3ced9e740a65",
      exerciseId: "b5ed4097-8e47-5ba3-9af3-ad8898eca4e1",
      clientId: "10da6d7d-e908-51fb-9664-311c42dbf2bc",
      chantierId: "1531ca19-b177-5f33-8fb8-9cbf2d03117d",
      sourceSheet: "2019-20",
      sourceRow: 77,
      rawName: "SCI PRJ",
      clientKey: "sci-prj",
      clientName: "Sci Prj",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 5165,
      caContrat: 5165,
      plannedTotal: 5165,
      realizedTotal: 5165,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "f9fde6bc-bb67-528d-856e-2bcca68b2aec",
      exerciseId: "b5ed4097-8e47-5ba3-9af3-ad8898eca4e1",
      clientId: "4e100c13-bcd7-5abf-aea1-7669ace1287f",
      chantierId: "3e51de19-e9d3-5559-84f9-3ad2b5e4de93",
      sourceSheet: "2019-20",
      sourceRow: 78,
      rawName: "LETOURNEUR",
      clientKey: "letourneur",
      clientName: "Letourneur",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 556,
      caContrat: 556,
      plannedTotal: 556,
      realizedTotal: 556,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "dab65ae2-a8af-58fb-9606-5ca1666f5665",
      exerciseId: "b5ed4097-8e47-5ba3-9af3-ad8898eca4e1",
      clientId: "b99ef3a0-82fd-5a7e-b607-b277b82e5917",
      chantierId: "fa90d8c2-0385-5006-a2f1-bf2a8332cb3c",
      sourceSheet: "2019-20",
      sourceRow: 79,
      rawName: "COLORE CAEN",
      clientKey: "colore-caen",
      clientName: "Colore Caen",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 500,
      caContrat: 500,
      plannedTotal: 500,
      realizedTotal: 500,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "a155f5a6-4acb-5e75-9479-ab3203c88655",
      exerciseId: "b5ed4097-8e47-5ba3-9af3-ad8898eca4e1",
      clientId: "27d890b9-ec3f-5714-bf0b-970bf9f6b48f",
      chantierId: "65f601b0-afe8-5afa-ac84-f94da766756c",
      sourceSheet: "2019-20",
      sourceRow: 80,
      rawName: "PARISOTTO",
      clientKey: "parisotto",
      clientName: "Parisotto",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 1990,
      caContrat: 1990,
      plannedTotal: 1990,
      realizedTotal: 1990.11,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "43addb44-a93c-5d9d-9c32-470e1df73263",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "c5fcf5d7-8c14-52b5-940a-7179eb069061",
      chantierId: "0ea09e1b-fc76-5cd5-aa1f-dd277b9c806d",
      sourceSheet: "2020-21",
      sourceRow: 16,
      rawName: "MARTINS",
      clientKey: "martins",
      clientName: "Martins",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 23433.53,
      caContrat: 23433.53,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "baf4d4ba-1c7d-5cf8-a471-bf7cfe230f77",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "f85f117a-d17d-57da-8752-89e8ed62383b",
      chantierId: "356a9aea-fc53-532c-b9ee-aca35b4b2cad",
      sourceSheet: "2020-21",
      sourceRow: 17,
      rawName: "Mairie de MOULT",
      clientKey: "mairie-de-moult",
      clientName: "Mairie de MOULT",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 22356.5,
      caContrat: 22357,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "3e8b6bb4-5837-553a-8f35-689cbf89de49",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "aac56d8f-57b5-5d28-a5fb-4662e5b1be76",
      chantierId: "81efb9db-5831-5a3e-9523-acc2fadec0bb",
      sourceSheet: "2020-21",
      sourceRow: 18,
      rawName: "CROCHARD",
      clientKey: "crochard",
      clientName: "Crochard",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 20600,
      caContrat: 20600,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "56ce76b0-29d9-5393-9071-52e9664c1b5c",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "8edec256-efd6-559c-b649-801a9c101b47",
      chantierId: "66364af4-9c4e-52fb-969e-a9e910cc1597",
      sourceSheet: "2020-21",
      sourceRow: 19,
      rawName: "HERBLOT",
      clientKey: "herblot",
      clientName: "Herblot",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 61500,
      caContrat: 61500,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "16e94b98-6b9f-5b35-835a-a20d15eec9c6",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "68c8c60b-e9a0-58ef-b908-a26294ff0d5a",
      chantierId: "b1030741-20d6-53ea-9a05-861d8c873106",
      sourceSheet: "2020-21",
      sourceRow: 20,
      rawName: "JAGER",
      clientKey: "jager",
      clientName: "Jager",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 81301.93,
      caContrat: 81301.93,
      plannedTotal: 14288,
      realizedTotal: 14288.15,
      invoicedTotal: 14288.15,
      invoiceSentTotal: 14288.15
    },
    {
      id: "deb0bba6-03d4-5e05-b615-67151b254a55",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "4af50642-1dd8-5c16-984d-339203432fb9",
      chantierId: "dac94081-1cd9-5f6c-8e6b-833a246687c0",
      sourceSheet: "2020-21",
      sourceRow: 21,
      rawName: "LEMOINE",
      clientKey: "lemoine",
      clientName: "Lemoine",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 42665,
      caContrat: 42665,
      plannedTotal: 42665,
      realizedTotal: 42665,
      invoicedTotal: 42665,
      invoiceSentTotal: 42665
    },
    {
      id: "fe4a9606-3cf2-5a18-82a2-f621e6eeb7ac",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "5b46c239-8469-518f-ae4b-6f14b3b0ff84",
      chantierId: "48ffb842-ec4b-5ce5-be00-515504ec44e0",
      sourceSheet: "2020-21",
      sourceRow: 22,
      rawName: "FRANCOIS",
      clientKey: "francois",
      clientName: "Francois",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 52084,
      caContrat: 52084,
      plannedTotal: 12355,
      realizedTotal: 12354.85,
      invoicedTotal: 12354.85,
      invoiceSentTotal: 12354.85
    },
    {
      id: "5de7c2d2-3bc8-593a-a13b-0958995572fb",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "78785387-2436-59d8-b8f5-1095d76e57c1",
      chantierId: "b0323aa5-5fcf-5b53-ab7f-c0d7b0aa22c7",
      sourceSheet: "2020-21",
      sourceRow: 23,
      rawName: "CUVIGNY",
      clientKey: "cuvigny",
      clientName: "Cuvigny",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 18000,
      caContrat: 18000,
      plannedTotal: 18000,
      realizedTotal: 18000,
      invoicedTotal: 18000,
      invoiceSentTotal: 18000
    },
    {
      id: "e9db9f02-ee44-5e36-ad4b-509d389c397c",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "864d95a4-f088-5b8f-8b6b-b67c8aec9542",
      chantierId: "641fd23d-ac54-5cd8-8536-3ea588662376",
      sourceSheet: "2020-21",
      sourceRow: 24,
      rawName: "BASSIERE",
      clientKey: "bassiere",
      clientName: "Bassiere",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 25682.67,
      caContrat: 25682.67,
      plannedTotal: 25682.67,
      realizedTotal: 25682.67,
      invoicedTotal: 25682.67,
      invoiceSentTotal: 25682.67
    },
    {
      id: "c7e6ea0b-d8d4-5985-aa90-1688c8558fa6",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "78d1bd33-069f-574a-82c0-af1f1a26bea8",
      chantierId: "2a94a275-d78e-5961-810a-fca7841a9c3a",
      sourceSheet: "2020-21",
      sourceRow: 25,
      rawName: "EXAEQUO",
      clientKey: "exaequo",
      clientName: "Exaequo",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 533.33,
      caContrat: 533.33,
      plannedTotal: 533.33,
      realizedTotal: 533.33,
      invoicedTotal: 533.33,
      invoiceSentTotal: 533.33
    },
    {
      id: "d1f97f41-c5cc-5472-bb97-3bfbe398137f",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "0ba0b86c-da09-5901-bc7f-a741b8b21ffa",
      chantierId: "734ca69a-2b19-50da-b991-c22116c065f3",
      sourceSheet: "2020-21",
      sourceRow: 26,
      rawName: "PREVOST",
      clientKey: "prevost",
      clientName: "Prevost",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 1821,
      caContrat: 1821,
      plannedTotal: 1821,
      realizedTotal: 1821.21,
      invoicedTotal: 1821.21,
      invoiceSentTotal: 1821.21
    },
    {
      id: "cdb480d6-214b-5c42-af5c-d74df0c218ea",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "3e2f4959-612f-549e-909c-72d85381f0ad",
      chantierId: "cd45e37e-4d14-5938-8bc3-0fc41fe39224",
      sourceSheet: "2020-21",
      sourceRow: 27,
      rawName: "DUCHENNE",
      clientKey: "duchenne",
      clientName: "Duchenne",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 21204,
      caContrat: 21204,
      plannedTotal: 4550,
      realizedTotal: 4550.16,
      invoicedTotal: 4550.16,
      invoiceSentTotal: 4550.16
    },
    {
      id: "f51516c2-e431-545a-8ec0-5612fa53a0dc",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "2e7bdc80-ef0f-56bf-8a77-eff64d2b3622",
      chantierId: "e61e6e2a-0a8c-5b80-98a2-57cb9729d0a7",
      sourceSheet: "2020-21",
      sourceRow: 28,
      rawName: "RAOULT",
      clientKey: "raoult",
      clientName: "Raoult",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 6537,
      caContrat: 6537,
      plannedTotal: 6537,
      realizedTotal: 6537,
      invoicedTotal: 6537,
      invoiceSentTotal: 6537
    },
    {
      id: "c8974e9e-73e9-5988-9a58-38aeedcce8f3",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "0c184b00-276e-5412-830f-d074e09ef653",
      chantierId: "d86205c4-b47a-5775-b91b-75762ff37b63",
      sourceSheet: "2020-21",
      sourceRow: 29,
      rawName: "VIVIER",
      clientKey: "vivier",
      clientName: "Vivier",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 9276,
      caContrat: 9276,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "812daef6-f9b5-5aa6-aacd-075ac86fddc1",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "6d818252-52be-54c0-bc37-dda593b10301",
      chantierId: "910bffcd-65e3-5978-b279-0f2914003a27",
      sourceSheet: "2020-21",
      sourceRow: 30,
      rawName: "FOUQUES mam bassene",
      clientKey: "fouques-mam-bassene",
      clientName: "FOUQUES mam bassene",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 4328,
      caContrat: 4328,
      plannedTotal: 4328,
      realizedTotal: 4328,
      invoicedTotal: 4328,
      invoiceSentTotal: 4328
    },
    {
      id: "e202bc15-a075-5d37-aacd-badfee3b181a",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "dc5b9248-925c-5171-86ff-26344d1a64c6",
      chantierId: "84833ac2-e830-527a-8c45-d162d9a3ba11",
      sourceSheet: "2020-21",
      sourceRow: 31,
      rawName: "ARCHE DES BEBES",
      clientKey: "arche-des-bebes",
      clientName: "Arche Des Bebes",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 220000,
      caContrat: 220000,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "7a10bbc2-c7eb-578c-8278-fac15aaadf41",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "f0c1a030-e3ee-5d64-9ffc-53a083430611",
      chantierId: "9a273e92-eb25-552a-afa0-c3cee53780ab",
      sourceSheet: "2020-21",
      sourceRow: 32,
      rawName: "CHATELIN",
      clientKey: "chatelin",
      clientName: "Chatelin",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 31053,
      caContrat: 31053,
      plannedTotal: 7316,
      realizedTotal: 7316.17,
      invoicedTotal: 7316.17,
      invoiceSentTotal: 7316.17
    },
    {
      id: "ee2cb6ba-376a-5bb5-b1be-8b76c936e5f5",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "f6dc4c21-3f6e-5a06-8a26-1670aa63d97f",
      chantierId: "cdc54611-c4e2-5739-ac79-cbed7c0ae2fd",
      sourceSheet: "2020-21",
      sourceRow: 33,
      rawName: "MONTFOURNY",
      clientKey: "montfourny",
      clientName: "Montfourny",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 113900,
      caContrat: 113900,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "dad281ca-7a88-55c9-9673-b67a767179e2",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "829c0cfc-1f18-5026-a8ec-7542d6c30e02",
      chantierId: "bc2ff2bb-7234-531c-8d81-34deec327601",
      sourceSheet: "2020-21",
      sourceRow: 34,
      rawName: "BRETAGNE",
      clientKey: "bretagne",
      clientName: "Bretagne",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 25597.21,
      caContrat: 25597,
      plannedTotal: 25597,
      realizedTotal: 25597.36,
      invoicedTotal: 25597.36,
      invoiceSentTotal: 25597.36
    },
    {
      id: "2a68e9fa-7e63-5270-a3ee-e51dbcdc9987",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "c099fdc8-1666-518f-990e-e08dc9c55925",
      chantierId: "51cdf6b7-107e-5fe6-bf07-c8c7c5fc33d5",
      sourceSheet: "2020-21",
      sourceRow: 35,
      rawName: "GERBAULT - IBANESCU",
      clientKey: "gerbault-ibanescu",
      clientName: "Gerbault - Ibanescu",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 103994,
      caContrat: 103994,
      plannedTotal: 54794,
      realizedTotal: 54793.82,
      invoicedTotal: 54793.82,
      invoiceSentTotal: 54793.82
    },
    {
      id: "8a92c914-36f4-57cd-8c68-bc4822877979",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "a6858f4e-a6d9-5b62-b765-a18d84ddfdbd",
      chantierId: "a5d01b22-e3ea-5650-ab7d-0c6a45068e04",
      sourceSheet: "2020-21",
      sourceRow: 36,
      rawName: "flipo portail",
      clientKey: "flipo-portail",
      clientName: "Flipo portail",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 1156,
      caContrat: 1156,
      plannedTotal: 1156,
      realizedTotal: 1156,
      invoicedTotal: 1156,
      invoiceSentTotal: 1156
    },
    {
      id: "cc4aefde-a36d-5f76-8003-9e89270786e7",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "581f81d8-428d-5a57-966e-079bebff1b9b",
      chantierId: "dcdcea0e-5b6d-5a7f-aa58-e71b4104fad4",
      sourceSheet: "2020-21",
      sourceRow: 37,
      rawName: "LECLEIR",
      clientKey: "lecleir",
      clientName: "Lecleir",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 29905.67,
      caContrat: 29905.67,
      plannedTotal: 23943,
      realizedTotal: 23943.45,
      invoicedTotal: 23943.45,
      invoiceSentTotal: 23943.45
    },
    {
      id: "d9d7231b-c95c-5c20-a3ab-029927869747",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "22ca2005-4e10-58e5-86e6-8a4b68d1aa32",
      chantierId: "c365a382-da0d-5dc3-8397-afd65dd39e01",
      sourceSheet: "2020-21",
      sourceRow: 38,
      rawName: "PORET",
      clientKey: "poret",
      clientName: "Poret",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 107534.34,
      caContrat: 107534.34,
      plannedTotal: 107534.34,
      realizedTotal: 107535.05,
      invoicedTotal: 107535.05,
      invoiceSentTotal: 107535.05
    },
    {
      id: "3fa0efdb-c0c7-53f8-a159-bc41e913af47",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "8cb258cc-165a-5957-96a2-3a45698322f9",
      chantierId: "c10f5b2c-2b45-593a-b0d0-5a390ccce58d",
      sourceSheet: "2020-21",
      sourceRow: 39,
      rawName: "CLET CARON",
      clientKey: "clet-caron",
      clientName: "Clet Caron",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 176738.45,
      caContrat: 176738,
      plannedTotal: 155790.7,
      realizedTotal: 155790.75,
      invoicedTotal: 155790.75,
      invoiceSentTotal: 155790.75
    },
    {
      id: "8e99468f-8c75-5d75-83e1-2e665c4a169f",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "8522625e-f629-524d-b005-fe54bdbe7b1e",
      chantierId: "f4f2f40f-59fa-5123-993e-d4ab9f3e014e",
      sourceSheet: "2020-21",
      sourceRow: 40,
      rawName: "BICART",
      clientKey: "bicart",
      clientName: "Bicart",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 7093,
      caContrat: 7093,
      plannedTotal: 7093,
      realizedTotal: 7092.9,
      invoicedTotal: 7092.9,
      invoiceSentTotal: 7092.9
    },
    {
      id: "f4b44fa7-bee3-5757-8430-398f24bb5c0c",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "fb9d0811-9f4e-5fcf-929f-90dc04fc2cfb",
      chantierId: "bf094597-e62e-58d2-bfcb-8717c323388e",
      sourceSheet: "2020-21",
      sourceRow: 41,
      rawName: "MAIRIE EVRECY",
      clientKey: "mairie-evrecy",
      clientName: "Mairie Evrecy",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 8521,
      caContrat: 8521,
      plannedTotal: 8521,
      realizedTotal: 8521.3,
      invoicedTotal: 8521.3,
      invoiceSentTotal: 8521.3
    },
    {
      id: "2962fede-e73d-59a3-91fc-1feeae02a62f",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "ac6665dd-c1d2-5915-a74c-9bfc68653f19",
      chantierId: "c912c48e-4fd5-55ad-ad1b-c62aac12d02c",
      sourceSheet: "2020-21",
      sourceRow: 42,
      rawName: "HUARD",
      clientKey: "huard",
      clientName: "Huard",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 36011,
      caContrat: 36011,
      plannedTotal: 5122,
      realizedTotal: 5121.79,
      invoicedTotal: 5121.79,
      invoiceSentTotal: 5121.79
    },
    {
      id: "35d15d5f-4cf9-58e2-b754-cab72ae4a2c3",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "1ff0e5ab-c97d-515a-a7c8-c9b3b087ac47",
      chantierId: "7a425d36-2e98-5337-8a8e-f25ae34487ee",
      sourceSheet: "2020-21",
      sourceRow: 43,
      rawName: "GUEDON",
      clientKey: "guedon",
      clientName: "Guedon",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 124336,
      caContrat: 124336,
      plannedTotal: 76047.31,
      realizedTotal: 76047.9,
      invoicedTotal: 76047.9,
      invoiceSentTotal: 76047.9
    },
    {
      id: "ca299c1c-288f-56f9-8983-0e6cca252c39",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "8c846b99-322c-51d4-816b-d46dac3b83f9",
      chantierId: "40914217-57a5-5549-83bd-a2b8a19ec20c",
      sourceSheet: "2020-21",
      sourceRow: 44,
      rawName: "FROGER",
      clientKey: "froger",
      clientName: "Froger",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 1913.88,
      caContrat: 1913.88,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "1e7d2f9e-60e9-51e3-9cb9-b992f6853ac2",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "9f1357b8-242f-58c2-be62-919524250275",
      chantierId: "fec28293-c273-566d-be00-29c60799c06c",
      sourceSheet: "2020-21",
      sourceRow: 45,
      rawName: "BOUILLET",
      clientKey: "bouillet",
      clientName: "Bouillet",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 2925,
      caContrat: 2925,
      plannedTotal: 2925,
      realizedTotal: 2925,
      invoicedTotal: 2925,
      invoiceSentTotal: 2925
    },
    {
      id: "293172d1-e6d6-5428-be46-9917b75e3bb8",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "f205a359-f6a3-5239-8793-107b1f17bece",
      chantierId: "8d2f528b-25eb-5c90-95fb-b856ad2232c9",
      sourceSheet: "2020-21",
      sourceRow: 46,
      rawName: "DUMAT MATTA",
      clientKey: "dumat-matta",
      clientName: "Dumat Matta",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 4018,
      caContrat: 4018,
      plannedTotal: 4018,
      realizedTotal: 4018,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "1e5b51d7-182e-5b3a-8a18-81768b5272a9",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "39281c5c-38c1-5269-a893-d2f132925ff1",
      chantierId: "b398f30b-1274-55a9-9840-dd4f86da44f2",
      sourceSheet: "2020-21",
      sourceRow: 47,
      rawName: "GIRARD",
      clientKey: "girard",
      clientName: "Girard",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 59556.29,
      caContrat: 59556,
      plannedTotal: 49515.25,
      realizedTotal: 49511.95,
      invoicedTotal: 15977.81,
      invoiceSentTotal: 15977.81
    },
    {
      id: "702c5ac0-a71f-51cd-a00b-241b3d69860d",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "cbe22469-53b6-5fef-bf23-bd02fafa48af",
      chantierId: "dc7a777d-b641-5357-a4d5-bf65d35d7d96",
      sourceSheet: "2020-21",
      sourceRow: 48,
      rawName: "ROHRBACH",
      clientKey: "rohrbach",
      clientName: "Rohrbach",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 1661,
      caContrat: 1661,
      plannedTotal: 1661,
      realizedTotal: 1660.99,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "dfc86d70-0cb6-56aa-8a39-828121aaa062",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "fa66c7a3-46ba-5afa-ad24-efc3901de275",
      chantierId: "ade37293-8a88-572e-9835-ecc262b0fff7",
      sourceSheet: "2020-21",
      sourceRow: 49,
      rawName: "GESLIN",
      clientKey: "geslin",
      clientName: "Geslin",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 26119,
      caContrat: 26119,
      plannedTotal: 26119,
      realizedTotal: 26118.38,
      invoicedTotal: 21617,
      invoiceSentTotal: 21617
    },
    {
      id: "ce444774-2d83-5c14-ac78-1c01d2081a4b",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "f20808f8-0a90-5b00-866f-511a3c5f001b",
      chantierId: "b7d27bd4-a015-5ee3-8595-71c32b0d86cd",
      sourceSheet: "2020-21",
      sourceRow: 50,
      rawName: "CHAVENTRE",
      clientKey: "chaventre",
      clientName: "Chaventre",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 1600,
      caContrat: 1600,
      plannedTotal: 1600,
      realizedTotal: 1600,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "d2ae8e4e-1ff4-57a3-8725-a20336a407dc",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "b31e6072-27e4-5c6e-8248-267d60fdda30",
      chantierId: "5c341691-335c-5415-9b01-0cb452404a5d",
      sourceSheet: "2020-21",
      sourceRow: 51,
      rawName: "THIRE",
      clientKey: "thire",
      clientName: "Thire",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 30000,
      caContrat: 30000,
      plannedTotal: 30000,
      realizedTotal: 30000,
      invoicedTotal: 30000,
      invoiceSentTotal: 30000
    },
    {
      id: "15bc504e-64da-53be-8bf8-1933f6145e62",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "ebfe7e0a-d277-567c-afa7-80b47c9246f7",
      chantierId: "270c9093-cc19-5dca-a420-d1eefd1a7f9b",
      sourceSheet: "2020-21",
      sourceRow: 52,
      rawName: "GEZE extension",
      clientKey: "geze",
      clientName: "GEZE extension",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 23871.78,
      caContrat: 23871.78,
      plannedTotal: 23872.09,
      realizedTotal: 23872,
      invoicedTotal: 5130.24,
      invoiceSentTotal: 5130.24
    },
    {
      id: "010e3bd1-611a-54ce-ada0-c5a2b13dcbd7",
      exerciseId: "5c5018bd-ebd3-57bf-88f4-24b3609ad311",
      clientId: "04cd0c16-f405-5948-91a7-d9f0b12dd025",
      chantierId: "1eabf1c3-434c-5b39-ad25-1237bce4bb2e",
      sourceSheet: "2020-21",
      sourceRow: 53,
      rawName: "GEZE existant",
      clientKey: "geze-existant",
      clientName: "GEZE existant",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 16560.34,
      caContrat: 16560,
      plannedTotal: 16560,
      realizedTotal: 16560.72,
      invoicedTotal: 11757.27,
      invoiceSentTotal: 11757.27
    }
  ])
}
