mutation @transaction {
  lines012: previsionnelLine_upsertMany(data: [
    {
      id: "7974ea96-e958-575f-8e03-2986d9a85949",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "d7cc93c6-38bf-5ea2-80fe-fbcadf67a0fb",
      chantierId: "c8ada0f2-16fb-57a6-b9c1-597ed59dccfc",
      sourceSheet: "2022-23",
      sourceRow: 25,
      rawName: "KLEBANER",
      clientKey: "klebaner",
      clientName: "Klebaner",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 7249,
      caContrat: 7249,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "b3886b31-4280-5742-9707-4a5633fac010",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "79ea0631-ae56-58cc-9a86-405125df7a5a",
      chantierId: "0c8458dc-0611-57f7-a115-55651afb3d53",
      sourceSheet: "2022-23",
      sourceRow: 26,
      rawName: "ALLEMAGNE",
      clientKey: "allemagne",
      clientName: "Allemagne",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 55082,
      caContrat: 55082,
      plannedTotal: 4897.36,
      realizedTotal: 4897.36,
      invoicedTotal: 4897.36,
      invoiceSentTotal: 4897.36
    },
    {
      id: "d59cbaf5-4dfb-5121-8ae6-a33f1829cd12",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "cb0e4e53-deb2-5f82-af84-24cecdc2dec5",
      chantierId: "6dbbfdd9-c221-548e-9fe7-bf05a3d56943",
      sourceSheet: "2022-23",
      sourceRow: 27,
      rawName: "VITAL SPORT IFS",
      clientKey: "vital-sport-ifs",
      clientName: "Vital Sport Ifs",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 5832,
      caContrat: 5832,
      plannedTotal: 5832,
      realizedTotal: 5831.78,
      invoicedTotal: 5831.78,
      invoiceSentTotal: 5831.78
    },
    {
      id: "de0fee92-35d7-5b46-95cf-18cc487d4a17",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "8172091c-eba8-54da-a1ce-931cc792a482",
      chantierId: "0f2a2ca4-a73c-5313-a002-9114abd757c6",
      sourceSheet: "2022-23",
      sourceRow: 28,
      rawName: "DELENTECOMMELCHAL",
      clientKey: "delentecommelchal",
      clientName: "Delentecommelchal",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 16680.13,
      caContrat: 16680.13,
      plannedTotal: 11870,
      realizedTotal: 11869.69,
      invoicedTotal: 11869.69,
      invoiceSentTotal: 11869.69
    },
    {
      id: "d00c00e7-cdae-5ea4-89fa-be4f50b71aa1",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "eb3c8122-2fd0-5b57-9109-5b771ec92520",
      chantierId: "12b288ae-8a5e-50ea-9c6e-683ad5a5b9bb",
      sourceSheet: "2022-23",
      sourceRow: 29,
      rawName: "SCI NOMELANI",
      clientKey: "sci-nomelani",
      clientName: "Sci Nomelani",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 42678,
      caContrat: 42678,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "63e5612c-b382-526a-a754-736988bf69d3",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "588d6fe4-737b-5867-9e83-d49187920c45",
      chantierId: "328326a2-e356-5725-a37b-ccbe58fd5bc1",
      sourceSheet: "2022-23",
      sourceRow: 30,
      rawName: "HARDOIN",
      clientKey: "hardoin",
      clientName: "Hardoin",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 37950,
      caContrat: 37573.71,
      plannedTotal: 13397,
      realizedTotal: 13397.49,
      invoicedTotal: 13397.49,
      invoiceSentTotal: 13397.49
    },
    {
      id: "553a25f0-b7cb-52bf-afee-8cf6b472adbf",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "b90c4718-3efb-5a67-a955-ebcc38dc9a44",
      chantierId: "c96382f9-9f79-5e08-8d27-236629c61e2f",
      sourceSheet: "2022-23",
      sourceRow: 31,
      rawName: "FERRARO",
      clientKey: "ferraro",
      clientName: "Ferraro",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 909.09,
      caContrat: 909,
      plannedTotal: 909,
      realizedTotal: 909.09,
      invoicedTotal: 909.09,
      invoiceSentTotal: 909.09
    },
    {
      id: "afa8eb1c-bdb7-5ed3-a676-813da8c595ff",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "373fe214-147f-5fbe-8dd2-1bcd063a6f7f",
      chantierId: "b68e5ba3-e44f-5e73-9b4b-dce442e773e9",
      sourceSheet: "2022-23",
      sourceRow: 32,
      rawName: "POCHAT",
      clientKey: "pochat",
      clientName: "Pochat",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 67172.28,
      caContrat: 67172.28,
      plannedTotal: 27064,
      realizedTotal: 27063.87,
      invoicedTotal: 27063.87,
      invoiceSentTotal: 27063.87
    },
    {
      id: "9f92ec4c-05ec-5db4-9e57-5e8fce4ec58a",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "f28f3fef-d8e1-5f5a-8757-bdc0ee0e6a43",
      chantierId: "43e3f8f8-edf7-56db-a3f1-c2f388623a6b",
      sourceSheet: "2022-23",
      sourceRow: 33,
      rawName: "DELORME",
      clientKey: "delorme",
      clientName: "Delorme",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 9758.56,
      caContrat: 9759,
      plannedTotal: 7172,
      realizedTotal: 7172.09,
      invoicedTotal: 7172.09,
      invoiceSentTotal: 7172.09
    },
    {
      id: "a24eae88-8782-53b8-ba93-68c0045e3d69",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "6c00a436-2c8d-55c4-9775-427e54418d08",
      chantierId: "857bc7f0-749a-5e12-9de9-6520cb8f9d40",
      sourceSheet: "2022-23",
      sourceRow: 34,
      rawName: "PERIOT",
      clientKey: "periot",
      clientName: "Periot",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 111277.97,
      caContrat: 111278,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "71ba39ed-aa5d-522b-8ed8-cf0733bd2417",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "3a9f655f-fed3-5b96-98e3-2548e05d074d",
      chantierId: "e971830d-1c1b-5998-8716-476e37c929e3",
      sourceSheet: "2022-23",
      sourceRow: 35,
      rawName: "GAUGUIN",
      clientKey: "gauguin",
      clientName: "Gauguin",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 52511,
      caContrat: 52511,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "0af659e1-2909-5145-9f5a-a097a118245a",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "b50a77e0-d46f-52e4-b233-fe4650d406da",
      chantierId: "f6f9e24e-e6aa-5055-929e-d9754e79c286",
      sourceSheet: "2022-23",
      sourceRow: 36,
      rawName: "DUFOUR",
      clientKey: "dufour",
      clientName: "Dufour",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 54245.46,
      caContrat: 51622,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "71443aac-2d87-5677-a7a3-a6e0cba91305",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "d34aff0b-6321-5e8b-9f9d-48f9737f7080",
      chantierId: "408797c8-a344-5474-a1f6-dd8b278e2b1f",
      sourceSheet: "2022-23",
      sourceRow: 37,
      rawName: "BILLOIN HEUGUEBART",
      clientKey: "billoin-heuguebart",
      clientName: "Billoin Heuguebart",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 106000,
      caContrat: 106000,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "1883d2ce-39a8-5ba3-8691-abda311c92e2",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "5d4845d0-cddb-5696-86d4-95d3ff9b902d",
      chantierId: "ecc53281-02de-56b5-8d32-e595d3c3d5b5",
      sourceSheet: "2022-23",
      sourceRow: 38,
      rawName: "SAVARY",
      clientKey: "savary",
      clientName: "Savary",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 59982,
      caContrat: 66485.7,
      plannedTotal: 63109.18,
      realizedTotal: 63108.79,
      invoicedTotal: 63108.79,
      invoiceSentTotal: 63108.79
    },
    {
      id: "e6a8081a-89d1-510d-a695-2f39a93dc044",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "1f1625eb-18e3-518d-a3b6-29709b7d7101",
      chantierId: "17b336c8-0ccb-574b-869d-c9f6ef25ec67",
      sourceSheet: "2022-23",
      sourceRow: 40,
      rawName: "SAISON",
      clientKey: "saison",
      clientName: "Saison",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 29033,
      caContrat: 29033,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "35d8de72-1064-59ca-9b17-41a7b1cb36e7",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "290b5b05-2e37-5ddc-902d-509250b0d0ed",
      chantierId: "632ecc9d-b6fb-5edc-84e8-6c8169bfb24e",
      sourceSheet: "2022-23",
      sourceRow: 41,
      rawName: "STENOU",
      clientKey: "stenou",
      clientName: "Stenou",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 30543,
      caContrat: 30543,
      plannedTotal: 15572.19,
      realizedTotal: 15572.19,
      invoicedTotal: 15572.19,
      invoiceSentTotal: 15572.19
    },
    {
      id: "665405a2-3426-559b-a4a4-6984e5a4870a",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "6f852fde-70c3-5db6-9f9d-c0acb9ac3803",
      chantierId: "983eda9d-fec3-5321-aa28-b8794e4f38e6",
      sourceSheet: "2022-23",
      sourceRow: 42,
      rawName: "LE TANNEUR",
      clientKey: "le-tanneur",
      clientName: "Le Tanneur",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 46206,
      caContrat: 46206,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "7241af8b-ed56-55b6-954b-72250553a6cf",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "7d3a2a5e-0182-5e63-b83b-d4f0ffa32ddd",
      chantierId: "4023c69a-2557-5ad2-95c5-6886e832bb82",
      sourceSheet: "2022-23",
      sourceRow: 43,
      rawName: "HENRY",
      clientKey: "henry",
      clientName: "Henry",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 221865,
      caContrat: 221865,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "59ee4a81-374a-5a0f-b0e4-32bbba35339c",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "8c846b99-322c-51d4-816b-d46dac3b83f9",
      chantierId: "3063754f-b9d2-5f69-aa47-cf1b5c0730db",
      sourceSheet: "2022-23",
      sourceRow: 44,
      rawName: "FROGER",
      clientKey: "froger",
      clientName: "Froger",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 6411,
      caContrat: 6411,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "a3513eb0-ebc6-551d-8e69-daeca761546e",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "a169bb47-3b58-5553-a6f3-6195e88985e2",
      chantierId: "959b879a-a89b-5d01-af3e-6262526bed82",
      sourceSheet: "2022-23",
      sourceRow: 45,
      rawName: "mairie de combray",
      clientKey: "mairie-de-combray",
      clientName: "Mairie de combray",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 3126,
      caContrat: 3126,
      plannedTotal: 3126,
      realizedTotal: 3126.26,
      invoicedTotal: 3126.26,
      invoiceSentTotal: 3126.26
    },
    {
      id: "6ba6ff1e-ee5f-5b5f-b9f4-ddd0cb4f2084",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "3fd89cf4-90a6-52ab-8723-287a82ad6c9e",
      chantierId: "d655e80e-4c78-500c-948e-11c5836644c0",
      sourceSheet: "2022-23",
      sourceRow: 47,
      rawName: "FERRE",
      clientKey: "ferre",
      clientName: "Ferre",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 3388,
      caContrat: 3388,
      plannedTotal: 3388,
      realizedTotal: 3388,
      invoicedTotal: 3388,
      invoiceSentTotal: 3388
    },
    {
      id: "0b37ae35-c3d5-5f50-9c79-a4f7ab43b907",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "1f4debf8-dee7-51c9-b995-aebb0818253f",
      chantierId: "83959763-8be4-5d63-857e-b0eaace556a3",
      sourceSheet: "2022-23",
      sourceRow: 48,
      rawName: "SCHACHER",
      clientKey: "schacher",
      clientName: "Schacher",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 547.27,
      caContrat: 547,
      plannedTotal: 547,
      realizedTotal: 547.27,
      invoicedTotal: 547.27,
      invoiceSentTotal: 547.27
    },
    {
      id: "c940dcf8-2fcd-5432-b81e-786c42a3dd7f",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "b816c25f-3734-5df9-939e-cb3803a2ba4e",
      chantierId: "6aa91401-3328-5886-8d3a-095be4fc7861",
      sourceSheet: "2022-23",
      sourceRow: 49,
      rawName: "BACON",
      clientKey: "bacon",
      clientName: "Bacon",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 20181.75,
      caContrat: 20181.75,
      plannedTotal: 20181.75,
      realizedTotal: 20181.65,
      invoicedTotal: 20181.65,
      invoiceSentTotal: 20181.65
    },
    {
      id: "cc9d4fec-fac3-54b9-b54f-c53edee947bd",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "f0bda559-0347-5329-8ad0-ff9290c99125",
      chantierId: "84a3d0a1-892f-59a0-86ce-5b1195c6d3bb",
      sourceSheet: "2022-23",
      sourceRow: 50,
      rawName: "GRANGE",
      clientKey: "grange",
      clientName: "Grange",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 138027,
      caContrat: 138027,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "22a2d345-2f81-56c4-94e8-5823ac49907c",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "8ad958ab-e84e-53b1-9fd4-452671f41b5a",
      chantierId: "69d2b898-3b86-51e2-af7d-06d77b1677d1",
      sourceSheet: "2022-23",
      sourceRow: 51,
      rawName: "RENAUDE",
      clientKey: "renaude",
      clientName: "Renaude",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 83178,
      caContrat: 83178,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "11775c8c-eb17-5706-aea8-715ca1d33085",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "86005441-8584-5832-acde-82c07d8b8a95",
      chantierId: "0f7f302e-96c6-55c2-9ffa-e8cfcc2ccec3",
      sourceSheet: "2022-23",
      sourceRow: 52,
      rawName: "BERGARD",
      clientKey: "bergard",
      clientName: "Bergard",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 196601,
      caContrat: 196601,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "77b3de46-4c55-5083-88bd-ca68977974bc",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "a470802a-4281-5c13-9e28-9c1200f6006e",
      chantierId: "6fba67f2-d30b-5f7d-8deb-ba04e4198514",
      sourceSheet: "2022-23",
      sourceRow: 53,
      rawName: "SAMSON",
      clientKey: "samson",
      clientName: "Samson",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 163185.65,
      caContrat: 163185.65,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "0a2d9ea5-2271-5db8-a2fc-e1adb63f6816",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "15745471-48c9-57c1-9c40-ea2963aea6e8",
      chantierId: "0b1c9dda-d497-5d3a-bf82-b5433d917df5",
      sourceSheet: "2022-23",
      sourceRow: 54,
      rawName: "ARNOULT LEMOINE",
      clientKey: "arnoult-lemoine",
      clientName: "Arnoult Lemoine",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 170733,
      caContrat: 170733,
      plannedTotal: 13930,
      realizedTotal: 13929.53,
      invoicedTotal: 13929.53,
      invoiceSentTotal: 13929.53
    },
    {
      id: "8c1ef0ff-3ce4-5981-9b1c-24f38128396e",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "9f24fcf4-0adf-5507-88d2-4dfc890fc9c8",
      chantierId: "e5c9edc4-3103-5b5e-b2b8-30af22c2b354",
      sourceSheet: "2022-23",
      sourceRow: 55,
      rawName: "LIAUTAUD",
      clientKey: "liautaud",
      clientName: "Liautaud",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 178242,
      caContrat: 173311.86,
      plannedTotal: 144966.26,
      realizedTotal: 144965.64,
      invoicedTotal: 144965.64,
      invoiceSentTotal: 144965.64
    },
    {
      id: "3ba51768-3579-5167-a017-49bff1f9dc6c",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "8beb1a95-4bef-59e0-9a6f-c740152f71c6",
      chantierId: "3e14b98d-bb75-54bb-a7f6-4859c4507d03",
      sourceSheet: "2022-23",
      sourceRow: 56,
      rawName: "HERVE SIMON",
      clientKey: "herve-simon",
      clientName: "Herve Simon",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 13260.65,
      caContrat: 13260.65,
      plannedTotal: 13260.65,
      realizedTotal: 13260.65,
      invoicedTotal: 13260.65,
      invoiceSentTotal: 13260.65
    },
    {
      id: "8452a2f1-f794-5688-9b7d-37295e4ccc58",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "d0ae8ab7-4f27-5168-82fb-70f819df8dc2",
      chantierId: "96f1ddd3-ee0a-56c4-a8da-47bd600adbb4",
      sourceSheet: "2022-23",
      sourceRow: 57,
      rawName: "DELACOUR",
      clientKey: "delacour",
      clientName: "Delacour",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 57246.74,
      caContrat: 57246.74,
      plannedTotal: 34318.41,
      realizedTotal: 34318,
      invoicedTotal: 34318,
      invoiceSentTotal: 34318
    },
    {
      id: "01bb7149-97f0-5944-bbc5-c8cacc1ed443",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "2865daf2-1885-5396-bcb4-01b9fef5295d",
      chantierId: "e7029511-e9ec-5f34-ad04-fa349267a95a",
      sourceSheet: "2022-23",
      sourceRow: 58,
      rawName: "DEPREZ",
      clientKey: "deprez",
      clientName: "Deprez",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 59940.38,
      caContrat: 59940.38,
      plannedTotal: 59940.38,
      realizedTotal: 59940.14,
      invoicedTotal: 59940.14,
      invoiceSentTotal: 59940.14
    },
    {
      id: "f69f49a3-e867-5845-aac7-282e71f7db66",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "9200ccd5-aaba-519e-9796-6a26a0f39153",
      chantierId: "76dc61e6-c20c-506e-8caf-2a5bf8b88214",
      sourceSheet: "2022-23",
      sourceRow: 59,
      rawName: "SAUTOT",
      clientKey: "sautot",
      clientName: "Sautot",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 48133.21,
      caContrat: 48133.21,
      plannedTotal: 46546,
      realizedTotal: 46546.84,
      invoicedTotal: 46546.84,
      invoiceSentTotal: 46546.84
    },
    {
      id: "d9d24869-ec15-5463-80f6-45e9f0cd86ac",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "5a00bc9a-f1d7-553e-aea4-7192f70b00c3",
      chantierId: "251b98c3-4c56-5d51-8d4c-f1e4f1742adc",
      sourceSheet: "2022-23",
      sourceRow: 60,
      rawName: "MARIE Aurelien",
      clientKey: "marie-aurelien",
      clientName: "MARIE Aurelien",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 5706.45,
      caContrat: 5706.45,
      plannedTotal: 5706.45,
      realizedTotal: 5706,
      invoicedTotal: 5706,
      invoiceSentTotal: 5706
    },
    {
      id: "70892a4e-cfaa-51db-97b9-4c61932ba80b",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "2dd1a886-0316-57a8-b6d5-e0a2b528deec",
      chantierId: "57cb37ac-609b-535d-8b1e-4cbf93d1556d",
      sourceSheet: "2022-23",
      sourceRow: 61,
      rawName: "BRUNEAU",
      clientKey: "bruneau",
      clientName: "Bruneau",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 19413,
      caContrat: 19694,
      plannedTotal: 19694,
      realizedTotal: 19413.41,
      invoicedTotal: 19413.41,
      invoiceSentTotal: 19413.41
    },
    {
      id: "c375b33a-b8a8-5507-87ca-8b5b52929396",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "d1be87b6-38f1-53a9-a8cd-1fa532ae55bb",
      chantierId: "b1113619-5761-5b1e-947d-1662da198418",
      sourceSheet: "2022-23",
      sourceRow: 62,
      rawName: "SCHIEL",
      clientKey: "schiel",
      clientName: "Schiel",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 149282.21,
      caContrat: 149282.21,
      plannedTotal: 149282.21,
      realizedTotal: 149282.5,
      invoicedTotal: 149282.5,
      invoiceSentTotal: 149282.5
    },
    {
      id: "97cff997-aae6-5164-b9db-e79073601b3b",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "4af50642-1dd8-5c16-984d-339203432fb9",
      chantierId: "dd0b58d8-a98d-5df2-9329-22cf9e0cf834",
      sourceSheet: "2022-23",
      sourceRow: 64,
      rawName: "LEMOINE",
      clientKey: "lemoine",
      clientName: "Lemoine",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 53419,
      caContrat: 53240.56,
      plannedTotal: 52746.61,
      realizedTotal: 52746.08,
      invoicedTotal: 52746.08,
      invoiceSentTotal: 52746.08
    },
    {
      id: "aeca9a46-afc9-54e6-b086-6a63372fbb83",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "596fa2e5-5785-5c7c-b61f-9cb5542004e4",
      chantierId: "21884b59-44bc-5a56-bb9a-3cf39e89f7e9",
      sourceSheet: "2022-23",
      sourceRow: 65,
      rawName: "CHATRE",
      clientKey: "chatre",
      clientName: "Chatre",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 24062,
      caContrat: 23482.47,
      plannedTotal: 23482.47,
      realizedTotal: 23482.62,
      invoicedTotal: 23482.62,
      invoiceSentTotal: 23482.62
    },
    {
      id: "82a83f42-dbf3-536b-82c6-6ce9ae147ec4",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "864d95a4-f088-5b8f-8b6b-b67c8aec9542",
      chantierId: "a59fd5d5-c10b-56ce-8edc-faea52831f74",
      sourceSheet: "2022-23",
      sourceRow: 66,
      rawName: "BASSIERE 2",
      clientKey: "bassiere",
      clientName: "Bassiere 2",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 30351,
      caContrat: 30351,
      plannedTotal: 30351,
      realizedTotal: 30350.38,
      invoicedTotal: 30350.38,
      invoiceSentTotal: 30350.38
    },
    {
      id: "9560548c-23ea-5e7d-871b-c317543b8814",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "0236e8f0-ba50-56c0-9b4d-c17d0f35c96b",
      chantierId: "e2e30511-0646-50ab-ab40-2d57d7104d6c",
      sourceSheet: "2022-23",
      sourceRow: 67,
      rawName: "LEPLE",
      clientKey: "leple",
      clientName: "Leple",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 102485,
      caContrat: 102485.09,
      plannedTotal: 102485.09,
      realizedTotal: 102485.03,
      invoicedTotal: 102485.03,
      invoiceSentTotal: 102485.03
    },
    {
      id: "e66c759a-7f19-5a5c-8220-439b2ca11f5d",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "af227993-37d5-5aec-8a55-fb1fb4d22256",
      chantierId: "72f0b3dc-d48d-5091-bda1-47322f710b53",
      sourceSheet: "2022-23",
      sourceRow: 68,
      rawName: "HOFLACK",
      clientKey: "hoflack",
      clientName: "Hoflack",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 15510.44,
      caContrat: 15510.44,
      plannedTotal: 15510.44,
      realizedTotal: 15510.43,
      invoicedTotal: 15510.43,
      invoiceSentTotal: 15510.43
    },
    {
      id: "e19f0dd4-edfe-5798-b2fd-21929b61f51a",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "80a7c273-a527-53ab-ae90-4d8aa3136d18",
      chantierId: "c54f61f8-2614-5d8c-93b6-7a82a182d30d",
      sourceSheet: "2022-23",
      sourceRow: 69,
      rawName: "GRARD ORABONA",
      clientKey: "grard-orabona",
      clientName: "Grard Orabona",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 58074.51,
      caContrat: 61227.95,
      plannedTotal: 37905,
      realizedTotal: 37905.49,
      invoicedTotal: 37905.49,
      invoiceSentTotal: 37905.49
    },
    {
      id: "f2122e33-5795-5462-ab66-13ca32c06316",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "4cf828fd-51a0-5594-a4ff-7d7d2e9f4654",
      chantierId: "b083c982-5e05-53ad-9cb1-ac80130c141b",
      sourceSheet: "2022-23",
      sourceRow: 70,
      rawName: "LAINE JAMET",
      clientKey: "laine-jamet",
      clientName: "Laine Jamet",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 51007,
      caContrat: 51007,
      plannedTotal: 51007,
      realizedTotal: 51007.13,
      invoicedTotal: 51007.13,
      invoiceSentTotal: 51007.13
    },
    {
      id: "eb70c72f-7bef-5c52-b3d6-a173485d1c7e",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "4506245d-64e0-5f52-b41b-59b1532353c8",
      chantierId: "47ecada8-8967-5f9f-ab88-799b10eb00bc",
      sourceSheet: "2022-23",
      sourceRow: 71,
      rawName: "mairie de perrière 2",
      clientKey: "mairie-de-perriere",
      clientName: "Mairie de perrière 2",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 9393.34,
      caContrat: 9921.34,
      plannedTotal: 9921.34,
      realizedTotal: 9921.34,
      invoicedTotal: 9921.34,
      invoiceSentTotal: 9921.34
    },
    {
      id: "e11e97ae-ef0b-5fc7-b4bc-451e5a98dbfe",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "34f2886d-9e7b-5d10-9539-57aae281d063",
      chantierId: "f1e91b71-f9ae-56f1-822c-d365361ece68",
      sourceSheet: "2022-23",
      sourceRow: 72,
      rawName: "BOURGET/POPOVIC",
      clientKey: "bourget-popovic",
      clientName: "Bourget/Popovic",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 153607,
      caContrat: 153607,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "cbb35c6c-7e9e-52fb-891f-2c4b2218c23c",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "db2ce1d1-8b2f-5fdd-9e20-4388295072a2",
      chantierId: "f47a5ab9-dc10-5414-9864-a56b358008b3",
      sourceSheet: "2022-23",
      sourceRow: 74,
      rawName: "SAUSSAYE",
      clientKey: "saussaye",
      clientName: "Saussaye",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 62574,
      caContrat: 62573.88,
      plannedTotal: 62573.88,
      realizedTotal: 62573.41,
      invoicedTotal: 62573.41,
      invoiceSentTotal: 62573.41
    },
    {
      id: "dcb837a5-ec20-50d0-9ec1-54e799d743e3",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "65573c0d-ad78-59f0-a2d2-0bd4bd0054e6",
      chantierId: "31027a5f-beb7-5e52-999f-ad2243544978",
      sourceSheet: "2022-23",
      sourceRow: 75,
      rawName: "HERVIEUX",
      clientKey: "hervieux",
      clientName: "Hervieux",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 23000,
      caContrat: 23376.39,
      plannedTotal: 23376.39,
      realizedTotal: 23377.39,
      invoicedTotal: 23377.39,
      invoiceSentTotal: 23377.39
    },
    {
      id: "64a58b29-2a78-5c46-94d8-e6a6b456f565",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "90317170-bc7f-54f2-b585-68e02446d940",
      chantierId: "eab0716c-b0c2-52af-b7e9-1ff3474fc10a",
      sourceSheet: "2022-23",
      sourceRow: 76,
      rawName: "CLAPAREDE",
      clientKey: "claparede",
      clientName: "Claparede",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 23072,
      caContrat: 23072,
      plannedTotal: 15497,
      realizedTotal: 15497.58,
      invoicedTotal: 15497.58,
      invoiceSentTotal: 15497.58
    },
    {
      id: "65c43f45-e896-5823-94aa-69f7e75daf76",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "615b36fc-c736-5f7b-9bf8-c0476587aa69",
      chantierId: "d64c7a34-edbe-5930-9f7c-8adea921563b",
      sourceSheet: "2022-23",
      sourceRow: 77,
      rawName: "JAMIN",
      clientKey: "jamin",
      clientName: "Jamin",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 31728,
      caContrat: 31127.92,
      plannedTotal: 31127.92,
      realizedTotal: 31127.92,
      invoicedTotal: 31127.92,
      invoiceSentTotal: 31127.92
    },
    {
      id: "99b9c35e-7973-5450-b70b-36b8182bb0e9",
      exerciseId: "a39c3136-5996-522d-97e2-8c3d6e2db130",
      clientId: "30b60963-9a04-5170-9736-7e33b1fe4c4c",
      chantierId: "647a693e-3139-5263-96a3-d04663682ee1",
      sourceSheet: "2022-23",
      sourceRow: 78,
      rawName: "STENOU/BALOCHE",
      clientKey: "stenou-baloche",
      clientName: "Stenou/Baloche",
      category: "non_classe",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 857.64,
      caContrat: 857.64,
      plannedTotal: 857.64,
      realizedTotal: 858,
      invoicedTotal: 858,
      invoiceSentTotal: 858
    }
  ])
}
