mutation @transaction {
  lines015: previsionnelLine_upsertMany(data: [
    {
      id: "e55bf6a1-0e68-5e2a-bd1c-fc436afb2e23",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "cad9a4d2-f5f3-542a-b9db-0e57c48cd95d",
      chantierId: "50c818b7-18b6-5a69-8c12-d95aaf89dec1",
      sourceSheet: "2024-25",
      sourceRow: 34,
      rawName: "CROSVILLE",
      clientKey: "crosville",
      clientName: "Crosville",
      category: "maison",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 109744.14,
      caContrat: 108761.3,
      plannedTotal: 108761.3,
      realizedTotal: 108761.3,
      invoicedTotal: 108761.3,
      invoiceSentTotal: 108761.3
    },
    {
      id: "bc5bd410-0c9b-57a2-aef2-2655830c1e73",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "6ea37b28-db97-5cc3-853a-5604d9aad9cb",
      chantierId: "0fa83277-182c-5d18-b2b8-17ecd006d4b7",
      sourceSheet: "2024-25",
      sourceRow: 35,
      rawName: "BOMPTEMPS",
      clientKey: "bomptemps",
      clientName: "Bomptemps",
      category: "maison",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 312795.54,
      caContrat: 310476.93,
      plannedTotal: 316673.44,
      realizedTotal: 316673.44,
      invoicedTotal: 316673.44,
      invoiceSentTotal: 316673.44
    },
    {
      id: "8dce3bf2-037f-54a4-a993-3f0f8e40f95b",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "f20808f8-0a90-5b00-866f-511a3c5f001b",
      chantierId: "f199af14-7fc0-59d1-8358-01e1d593df3c",
      sourceSheet: "2024-25",
      sourceRow: 36,
      rawName: "CHAVENTRE",
      clientKey: "chaventre",
      clientName: "Chaventre",
      category: "maison",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 192000,
      caContrat: 0,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "610f2688-2b82-5542-8fbc-9c6efd1410d4",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "123da965-2f04-5d2b-a95b-3aa7f3487672",
      chantierId: "e9a6602f-fc86-51e9-9998-130353e91a9d",
      sourceSheet: "2024-25",
      sourceRow: 37,
      rawName: "GUILLOT 1",
      clientKey: "guillot",
      clientName: "Guillot 1",
      category: "maison",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 129873.63,
      caContrat: 129873.63,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "60da244f-e65b-5ce2-a05a-a1f3f78fe8bd",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "123da965-2f04-5d2b-a95b-3aa7f3487672",
      chantierId: "b3c3be58-0f2d-51f1-bd8c-bbf73780647c",
      sourceSheet: "2024-25",
      sourceRow: 38,
      rawName: "GUILLOT 2",
      clientKey: "guillot",
      clientName: "Guillot 2",
      category: "maison",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 129873.63,
      caContrat: 129873.63,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "1a0ecf95-7b90-575d-af7b-f874c4cb1640",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "123da965-2f04-5d2b-a95b-3aa7f3487672",
      chantierId: "b14efa22-9fd0-524e-996c-f41fbd57dfae",
      sourceSheet: "2024-25",
      sourceRow: 39,
      rawName: "GUILLOT 3",
      clientKey: "guillot",
      clientName: "Guillot 3",
      category: "maison",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 129619.04,
      caContrat: 129619.04,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "d81fa52a-474e-5408-9c80-15974768b65f",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "bb0123ad-0a33-51bc-a0f8-1b568f488144",
      chantierId: "ac8f09c7-08f3-5a04-85b9-12343efeae7a",
      sourceSheet: "2024-25",
      sourceRow: 40,
      rawName: "DUFOUR Gaêtan",
      clientKey: "dufour-gaetan",
      clientName: "DUFOUR Gaêtan",
      category: "maison",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 262000,
      caContrat: 276873.55,
      plannedTotal: 276873.55,
      realizedTotal: 276278.04,
      invoicedTotal: 276278.04,
      invoiceSentTotal: 276278.04
    },
    {
      id: "08c7a194-6177-535a-8057-1a612f21a2db",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "8ad958ab-e84e-53b1-9fd4-452671f41b5a",
      chantierId: "8fd6d0ee-f635-529f-82f5-703753fc4b67",
      sourceSheet: "2024-25",
      sourceRow: 44,
      rawName: "RENAUDE",
      clientKey: "renaude",
      clientName: "Renaude",
      category: "maison",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 101895,
      caContrat: 391,
      plannedTotal: 391,
      realizedTotal: 390.72,
      invoicedTotal: 390.72,
      invoiceSentTotal: 390.72
    },
    {
      id: "9a3b301b-e538-5426-82c6-4e6de3df779b",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "d34aff0b-6321-5e8b-9f9d-48f9737f7080",
      chantierId: "a45207a1-04a1-589d-89e3-1711af5d4f83",
      sourceSheet: "2024-25",
      sourceRow: 45,
      rawName: "BILLOIN HEUGUEBART",
      clientKey: "billoin-heuguebart",
      clientName: "Billoin Heuguebart",
      category: "maison",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 109863.16,
      caContrat: 79045.37,
      plannedTotal: 79045.37,
      realizedTotal: 79045.37,
      invoicedTotal: 79045.37,
      invoiceSentTotal: 79045.37
    },
    {
      id: "37bda2f4-e814-55ff-b1f2-ce4e5354979b",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "01e90885-b7d1-5f2d-8bf6-64013b058cf6",
      chantierId: "53d0f781-dbfc-5cea-9302-78de5ee6e115",
      sourceSheet: "2024-25",
      sourceRow: 46,
      rawName: "BERGAR",
      clientKey: "bergar",
      clientName: "Bergar",
      category: "maison",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 257744.9,
      caContrat: 842.24,
      plannedTotal: 842.24,
      realizedTotal: 842.24,
      invoicedTotal: 842.24,
      invoiceSentTotal: 842.24
    },
    {
      id: "8f9662ef-77b8-5478-92f4-c898233e232d",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "5e28e914-24f4-573d-9002-6c8036e77300",
      chantierId: "c5931420-e7b9-547b-b54c-305e8ebac887",
      sourceSheet: "2024-25",
      sourceRow: 49,
      rawName: "LEMAZURIEZ",
      clientKey: "lemazuriez",
      clientName: "Lemazuriez",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 51011.23,
      caContrat: 51011.23,
      plannedTotal: 51011.23,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "f4146824-f73e-5b8a-8067-3002bf300e44",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "f8b8960f-a4a1-58bf-93e9-26deaf9f5216",
      chantierId: "cc17a917-22f2-5164-afba-aa6a8431978d",
      sourceSheet: "2024-25",
      sourceRow: 50,
      rawName: "GESLAIN",
      clientKey: "geslain",
      clientName: "Geslain",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 79029.81,
      caContrat: 0,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "bacec641-4849-5e68-8655-1ba972caea2f",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "40cf37c4-f776-56f5-b367-5956e453f9c1",
      chantierId: "3dab7227-38cf-525c-bc54-effb9d1be359",
      sourceSheet: "2024-25",
      sourceRow: 51,
      rawName: "PHILIPPE",
      clientKey: "philippe",
      clientName: "Philippe",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 53705.82,
      caContrat: 53705.82,
      plannedTotal: 13836.57,
      realizedTotal: 13836.57,
      invoicedTotal: 13836.57,
      invoiceSentTotal: 13836.57
    },
    {
      id: "32285ac3-23a3-5d72-9d78-2bd795a6ce71",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "26adc391-ec3f-548d-b8b9-3ff5ea1e44e1",
      chantierId: "73d79324-cf52-56cb-a323-009e3341c2e9",
      sourceSheet: "2024-25",
      sourceRow: 52,
      rawName: "LEROYER PIOLINE",
      clientKey: "leroyer-pioline",
      clientName: "Leroyer Pioline",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 76200,
      caContrat: 0,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "a9d3501f-18ca-5eb9-a3c9-18c05bfd3799",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "2e7bdc80-ef0f-56bf-8a77-eff64d2b3622",
      chantierId: "adf4a067-58f0-5423-b5dc-0cc308daa60f",
      sourceSheet: "2024-25",
      sourceRow: 53,
      rawName: "RAOULT",
      clientKey: "raoult",
      clientName: "Raoult",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 170194.09,
      caContrat: 0,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "61eee21c-0656-5bc4-a2f2-736f43fe4516",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "5188b7be-98a3-5e14-afd7-8249e8d28068",
      chantierId: "c04c0e4c-65aa-5b06-ae68-6ade492819e4",
      sourceSheet: "2024-25",
      sourceRow: 54,
      rawName: "SIGNORET",
      clientKey: "signoret",
      clientName: "Signoret",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 32659.64,
      caContrat: 32659.64,
      plannedTotal: 6114.23,
      realizedTotal: 6114.23,
      invoicedTotal: 6114.23,
      invoiceSentTotal: 6114.23
    },
    {
      id: "ab916925-cdf4-5b2b-8793-5ac280bba9ba",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "a3e96c65-9ea1-57cf-81fc-9cffa6ec3a47",
      chantierId: "fc99f818-c184-5055-a621-d1276519ef82",
      sourceSheet: "2024-25",
      sourceRow: 55,
      rawName: "CHATEL LAURENT Alexandra",
      clientKey: "chatel-laurent-alexandra",
      clientName: "CHATEL LAURENT Alexandra",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 45000,
      caContrat: 45000,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "1a0dd6fc-2177-5390-aea3-1e8a9e58c448",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "696d8026-91d1-5e44-a57d-2701eed9429f",
      chantierId: "567c30c1-4236-525f-a9e9-fa2f850d0d1d",
      sourceSheet: "2024-25",
      sourceRow: 56,
      rawName: "DENOS KOPP",
      clientKey: "denos-kopp",
      clientName: "Denos Kopp",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 52395.31,
      caContrat: 52395.31,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "a84e8aad-4fa8-5cfb-870d-a717a08531b8",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "ece839d4-f69d-5867-ac20-a2a35d41c6ac",
      chantierId: "97076e50-03c5-5930-a275-7743e6625809",
      sourceSheet: "2024-25",
      sourceRow: 57,
      rawName: "LEPLUS",
      clientKey: "leplus",
      clientName: "Leplus",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 42452.3,
      caContrat: 42452.3,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "7ef4a548-37c7-5a88-90ce-1c0818701a95",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "a645467e-98df-5edb-b4bd-410c42db44a2",
      chantierId: "ff241eed-8c93-5314-a4d0-874249e1d37f",
      sourceSheet: "2024-25",
      sourceRow: 58,
      rawName: "BERTRAND",
      clientKey: "bertrand",
      clientName: "Bertrand",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 97232.53,
      caContrat: 0,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "8996ad8b-4310-5521-b9b9-10d4aac26b95",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "dcbb1bce-d6d7-539c-b6c5-2936b5a3d01e",
      chantierId: "4140a2cf-0ca0-5ae6-9ae6-9920a7b1f437",
      sourceSheet: "2024-25",
      sourceRow: 59,
      rawName: "CHAUVEAU",
      clientKey: "chauveau",
      clientName: "Chauveau",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 103929.82,
      caContrat: 103929.82,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "78f392c9-f7de-5785-abf0-b7dc751084b1",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "9b7ee751-e846-5f2c-9f2c-63daab5e4011",
      chantierId: "7ebfa1a6-abb7-5450-a366-fb07885fc31d",
      sourceSheet: "2024-25",
      sourceRow: 60,
      rawName: "GLOWACKI",
      clientKey: "glowacki",
      clientName: "Glowacki",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 141778.85,
      caContrat: 141778.85,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "24a831db-aa4d-5a56-b79b-0b52365a246e",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "86fca1cd-ed3a-5e24-baee-0dae918f5555",
      chantierId: "3ed57c78-17ec-561f-9585-89bbcd4abaf5",
      sourceSheet: "2024-25",
      sourceRow: 61,
      rawName: "DUFOUR Maxime",
      clientKey: "dufour-maxime",
      clientName: "DUFOUR Maxime",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 56945.15,
      caContrat: 56945.15,
      plannedTotal: 49048.09,
      realizedTotal: 49048.09,
      invoicedTotal: 49048.09,
      invoiceSentTotal: 49048.09
    },
    {
      id: "86d76fbf-5ec9-546e-8991-2d952f200e98",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "d6d2d11f-63a4-554e-b8e3-816551c4a0ee",
      chantierId: "d15f0e27-5bc8-5f82-ae36-dd9dcc63c7ce",
      sourceSheet: "2024-25",
      sourceRow: 62,
      rawName: "URBAIN",
      clientKey: "urbain",
      clientName: "Urbain",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 41577.75,
      caContrat: 41577.75,
      plannedTotal: 35348.2,
      realizedTotal: 35348.2,
      invoicedTotal: 35348.2,
      invoiceSentTotal: 35348.2
    },
    {
      id: "a7e778c7-f231-573e-b185-5613dd3028f2",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "f6f0b8ce-7eaf-5d70-9d1b-939b5ec1b7c1",
      chantierId: "ccd83cdf-6547-5f79-9efd-34840f540d5d",
      sourceSheet: "2024-25",
      sourceRow: 63,
      rawName: "CAMBAY",
      clientKey: "cambay",
      clientName: "Cambay",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 47741.7,
      caContrat: 47741.7,
      plannedTotal: 77165.13,
      realizedTotal: 29423.43,
      invoicedTotal: 29423.43,
      invoiceSentTotal: 29423.43
    },
    {
      id: "6170f21e-517f-5eac-adf8-15751430899d",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "5da63188-cf5c-501c-8fd3-24bcad2c8980",
      chantierId: "512a384b-5114-5abf-929a-575c465e9d72",
      sourceSheet: "2024-25",
      sourceRow: 64,
      rawName: "BEAUSSIER",
      clientKey: "beaussier",
      clientName: "Beaussier",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 82724,
      caContrat: 82724,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "63d608a1-d6f8-5ce1-9921-1ba97e15a9e5",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "77fd8ad4-4d80-5fa4-93a7-52d536f6194d",
      chantierId: "ad2471d6-05be-5887-9001-c7a4ebeb1116",
      sourceSheet: "2024-25",
      sourceRow: 65,
      rawName: "MARCHAIS",
      clientKey: "marchais",
      clientName: "Marchais",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 39152.01,
      caContrat: 39152.01,
      plannedTotal: 39152.01,
      realizedTotal: 39152.01,
      invoicedTotal: 39152.01,
      invoiceSentTotal: 39152.01
    },
    {
      id: "7d43638f-9f77-560d-8956-a2d4042ee183",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "80a65f16-3647-5ea8-aa1b-c349c29d5c8c",
      chantierId: "b82f96f5-8e39-5463-81c3-6f1e7e5be4b8",
      sourceSheet: "2024-25",
      sourceRow: 66,
      rawName: "PIERRE (Barbery)",
      clientKey: "pierre",
      clientName: "Pierre",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 30819.44,
      caContrat: 30819.44,
      plannedTotal: 30819.44,
      realizedTotal: 30819.8,
      invoicedTotal: 30819.8,
      invoiceSentTotal: 30819.8
    },
    {
      id: "c64ec2d5-9101-5004-a52e-855bbb2266c6",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "45405283-2b9d-5fa2-892a-ad50488a4a3c",
      chantierId: "6fafe505-b9c3-5466-a1c0-cb0a39a01e77",
      sourceSheet: "2024-25",
      sourceRow: 67,
      rawName: "OLIVIER",
      clientKey: "olivier",
      clientName: "Olivier",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 153286.86,
      caContrat: 156534.62,
      plannedTotal: 151066.34,
      realizedTotal: 151066.34,
      invoicedTotal: 151066.34,
      invoiceSentTotal: 151066.34
    },
    {
      id: "164903f4-ab9e-5d17-9f05-d39087d961f1",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "4b8dc882-7db0-5df2-91bc-ca5bfe663fa7",
      chantierId: "48959cbf-1a96-51a9-b5f2-f2bbbe0dc443",
      sourceSheet: "2024-25",
      sourceRow: 68,
      rawName: "ANQUETIL",
      clientKey: "anquetil",
      clientName: "Anquetil",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 59783.93,
      caContrat: 59634.03,
      plannedTotal: 59634.03,
      realizedTotal: 59634.03,
      invoicedTotal: 59634.03,
      invoiceSentTotal: 59634.03
    },
    {
      id: "8d53da14-201d-5c21-8a6c-e89b243f91b8",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "7d3a2a5e-0182-5e63-b83b-d4f0ffa32ddd",
      chantierId: "98869bdf-497a-5e88-9d00-493e8705dbe8",
      sourceSheet: "2024-25",
      sourceRow: 69,
      rawName: "HENRY",
      clientKey: "henry",
      clientName: "Henry",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 42074.15,
      caContrat: 31504.71,
      plannedTotal: 31504.71,
      realizedTotal: 31504.77,
      invoicedTotal: 31504.77,
      invoiceSentTotal: 31504.77
    },
    {
      id: "c86c9b67-7a54-549b-b5f7-30210b57b5ba",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "7e4baf46-14c2-50fc-a9f1-c7d460cd4a5e",
      chantierId: "b3da9bfa-4376-5c1d-aa08-ab9b8189f046",
      sourceSheet: "2024-25",
      sourceRow: 70,
      rawName: "MOULINET",
      clientKey: "moulinet",
      clientName: "Moulinet",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 104193.08,
      caContrat: 0,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "5d549029-bf14-54a6-b9c8-c226080f3dbc",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "7e37aa26-817b-52c1-a60b-96f4b2a9838d",
      chantierId: "dbc9df49-7fa8-55e9-8523-2a29dfe8c193",
      sourceSheet: "2024-25",
      sourceRow: 71,
      rawName: "GROUSSARD",
      clientKey: "groussard",
      clientName: "Groussard",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 28788.02,
      caContrat: 28788.02,
      plannedTotal: 28788.02,
      realizedTotal: 28788.05,
      invoicedTotal: 28788.05,
      invoiceSentTotal: 28788.05
    },
    {
      id: "0f0ed6cd-0b5d-5fd1-9fe3-183041a4f627",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "e803033c-d85d-5cee-bde5-ca7903b50ec0",
      chantierId: "f54ff34b-0f4f-5601-aabf-da2841067524",
      sourceSheet: "2024-25",
      sourceRow: 72,
      rawName: "MARTIN (Bourguebus)",
      clientKey: "martin",
      clientName: "Martin",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 55000,
      caContrat: 0,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "ecaa7f35-9674-5ecb-b5a8-51c9437da1e5",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "25da6189-c359-5e76-981d-a381b86f1573",
      chantierId: "6e5e79e5-0499-5b43-a63b-1162f0e340fa",
      sourceSheet: "2024-25",
      sourceRow: 74,
      rawName: "POREE Romane",
      clientKey: "poree-romane",
      clientName: "POREE Romane",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 25000,
      caContrat: 0,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "3370d4f2-8308-56c7-962d-496610f105a1",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "77bed385-9ad7-5cc8-9ec1-e991b420029f",
      chantierId: "68f0881e-e2c0-5b68-8eeb-360047cd1304",
      sourceSheet: "2024-25",
      sourceRow: 75,
      rawName: "MARIE (Sannerville)",
      clientKey: "marie",
      clientName: "Marie",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 44221.75,
      caContrat: 44221.61,
      plannedTotal: 44221.61,
      realizedTotal: 44221.61,
      invoicedTotal: 44221.61,
      invoiceSentTotal: 44221.61
    },
    {
      id: "ee335b3c-1069-599f-a232-baf11b1c0c3d",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "27d890b9-ec3f-5714-bf0b-970bf9f6b48f",
      chantierId: "a7dbc3c5-03bf-584d-8755-e75732be4423",
      sourceSheet: "2024-25",
      sourceRow: 76,
      rawName: "PARISOTTO",
      clientKey: "parisotto",
      clientName: "Parisotto",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 33961,
      caContrat: 6425.89,
      plannedTotal: 6425.89,
      realizedTotal: 6425.66,
      invoicedTotal: 6425.66,
      invoiceSentTotal: 6425.66
    },
    {
      id: "1a9f5844-8c88-508b-97e3-88f4856cf39b",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "e5eac775-755b-5ca3-aa4c-590034a1292e",
      chantierId: "a897035c-9773-5435-b169-fbda9824d202",
      sourceSheet: "2024-25",
      sourceRow: 77,
      rawName: "ISABELLE",
      clientKey: "isabelle",
      clientName: "Isabelle",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 135515.7,
      caContrat: 74518.58,
      plannedTotal: 74518.58,
      realizedTotal: 74518.48,
      invoicedTotal: 74518.48,
      invoiceSentTotal: 74518.48
    },
    {
      id: "464745ab-1bfa-52b3-94ae-fe577e4f90ef",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "5d4845d0-cddb-5696-86d4-95d3ff9b902d",
      chantierId: "c9508999-68fb-58bf-a375-1fa727ace5a7",
      sourceSheet: "2024-25",
      sourceRow: 78,
      rawName: "SAVARY 01",
      clientKey: "savary",
      clientName: "Savary 01",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 3377,
      caContrat: 3376.52,
      plannedTotal: 3376.52,
      realizedTotal: 3377,
      invoicedTotal: 3377,
      invoiceSentTotal: 3377
    },
    {
      id: "9614420e-9d08-576c-8dd1-8f1a443847da",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "5d4845d0-cddb-5696-86d4-95d3ff9b902d",
      chantierId: "03a620e9-a60c-55a0-a1d6-e53b775eb37e",
      sourceSheet: "2024-25",
      sourceRow: 79,
      rawName: "SAVARY 2",
      clientKey: "savary",
      clientName: "Savary 2",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 136000.38,
      caContrat: 5382.22,
      plannedTotal: 5382.22,
      realizedTotal: 5382.38,
      invoicedTotal: 5382.38,
      invoiceSentTotal: 5382.38
    },
    {
      id: "ef9fe050-029c-5fee-b5cb-976f0aaf2a39",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "a2f470b3-45bd-59fc-8ec2-76dab4c44813",
      chantierId: "b5505cd8-97e0-557b-965c-c3763f08898b",
      sourceSheet: "2024-25",
      sourceRow: 83,
      rawName: "LEGENDRE",
      clientKey: "legendre",
      clientName: "Legendre",
      category: "charpente",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 12089.97,
      caContrat: 12089.97,
      plannedTotal: 12089.97,
      realizedTotal: 10276.91,
      invoicedTotal: 10276.91,
      invoiceSentTotal: 10276.91
    },
    {
      id: "cc700c0d-f810-5642-b3b9-4156b4214c27",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "96a6df6e-48a9-5031-aa74-917c9c51297c",
      chantierId: "550740c4-e495-53bc-8d50-0f2e7bffbe8a",
      sourceSheet: "2024-25",
      sourceRow: 84,
      rawName: "ECURIE BASSENEVILLE",
      clientKey: "ecurie-basseneville",
      clientName: "Ecurie Basseneville",
      category: "charpente",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 36197.62,
      caContrat: 36197.62,
      plannedTotal: 36197.62,
      realizedTotal: 36197.79,
      invoicedTotal: 36197.79,
      invoiceSentTotal: 36197.79
    },
    {
      id: "f9ad4d39-9ac5-5853-b081-5981b287f359",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "dc1333ba-f82b-5519-968a-a9769e7be0c3",
      chantierId: "1f39db9e-2db1-5d0d-8ddd-9f4955ebadb6",
      sourceSheet: "2024-25",
      sourceRow: 85,
      rawName: "TESSON",
      clientKey: "tesson",
      clientName: "Tesson",
      category: "charpente",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 2380.21,
      caContrat: 2380.21,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "4f70a66a-b2f8-5f97-899f-6fbbf948032c",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "1e9cffaa-92a1-58d4-ab23-2d1cd71c8ef5",
      chantierId: "bc297d97-cd58-5844-97fb-ec21d39c499b",
      sourceSheet: "2024-25",
      sourceRow: 86,
      rawName: "ALTO",
      clientKey: "alto",
      clientName: "Alto",
      category: "charpente",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 1422.02,
      caContrat: 1422.02,
      plannedTotal: 1422.02,
      realizedTotal: 1422,
      invoicedTotal: 1422,
      invoiceSentTotal: 1422
    },
    {
      id: "c5c9f1d1-e92d-539a-8f35-18e089913ae0",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "598238f3-e7b8-56aa-a43b-0b7b50b4ebd3",
      chantierId: "35a78f01-b6ac-5755-9871-508ac083edd4",
      sourceSheet: "2024-25",
      sourceRow: 87,
      rawName: "CHATELET",
      clientKey: "chatelet",
      clientName: "Chatelet",
      category: "charpente",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 95064,
      caContrat: 13865,
      plannedTotal: 13865,
      realizedTotal: 13864.68,
      invoicedTotal: 13864.68,
      invoiceSentTotal: 13864.68
    },
    {
      id: "2c25f7be-e7e1-528c-a00b-279280c71a09",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "6f852fde-70c3-5db6-9f9d-c0acb9ac3803",
      chantierId: "df93df77-8ce9-50d6-92f4-f82633e4b1ae",
      sourceSheet: "2024-25",
      sourceRow: 88,
      rawName: "LE TANNEUR",
      clientKey: "le-tanneur",
      clientName: "Le Tanneur",
      category: "charpente",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 46206,
      caContrat: 17014.62,
      plannedTotal: 7348.63,
      realizedTotal: 7348.63,
      invoicedTotal: 7348.63,
      invoiceSentTotal: 7348.63
    },
    {
      id: "fea21221-75b7-5992-836c-f0519b2ea33a",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "c7be6f26-b6d1-5657-a321-86468fc6ff3d",
      chantierId: "0243e538-b561-5783-be6d-6714c483b035",
      sourceSheet: "2024-25",
      sourceRow: 89,
      rawName: "SCI FELAH",
      clientKey: "sci-felah",
      clientName: "Sci Felah",
      category: "charpente",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 6213,
      caContrat: 0,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "0a2cbf01-b75d-57ce-93a6-6887f645df33",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "5c9e3bcb-415f-5f37-828d-73a45cfb50a9",
      chantierId: "3c59cf9b-db61-5689-aa87-df60876bc719",
      sourceSheet: "2024-25",
      sourceRow: 93,
      rawName: "BOUQUIN",
      clientKey: "bouquin",
      clientName: "Bouquin",
      category: "divers",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 3428.96,
      caContrat: 3428.96,
      plannedTotal: 3428.96,
      realizedTotal: 3428.96,
      invoicedTotal: 3428.96,
      invoiceSentTotal: 3428.96
    },
    {
      id: "8d0eee2d-b69b-5095-80ca-638da152adb4",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "012b9ff6-be15-594f-83f0-3f15753c5c52",
      chantierId: "6dcebe5b-453f-5ad5-a009-35ec67627ea2",
      sourceSheet: "2024-25",
      sourceRow: 94,
      rawName: "MAISON BOIS METAL",
      clientKey: "bois-metal",
      clientName: "Maison Bois Metal",
      category: "divers",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 223.8,
      caContrat: 223.8,
      plannedTotal: 223.8,
      realizedTotal: 223.8,
      invoicedTotal: 223.8,
      invoiceSentTotal: 223.8
    },
    {
      id: "ceb47287-a36e-50cf-bc03-207b6ac54b5f",
      exerciseId: "139213a0-302f-59cc-aa47-ddf6d0731154",
      clientId: "5b46c239-8469-518f-ae4b-6f14b3b0ff84",
      chantierId: "51cb8be1-4af6-56cf-acfd-7cba01a32ff4",
      sourceSheet: "2024-25",
      sourceRow: 95,
      rawName: "FRANCOIS",
      clientKey: "francois",
      clientName: "Francois",
      category: "divers",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 2118.44,
      caContrat: 2118.44,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    }
  ])
}
