mutation @transaction {
  lines017: previsionnelLine_upsertMany(data: [
    {
      id: "4315b3c9-498d-592d-9825-c4b0b1951cfa",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "72687797-12a8-5d43-9810-b94e6a95f7cd",
      chantierId: "bc507c6d-8955-5c4b-b01d-98d77c0fb36d",
      sourceSheet: "2025-26",
      sourceRow: 28,
      rawName: "LEPROVOT",
      clientKey: "leprovot",
      clientName: "Leprovot",
      category: "maison",
      lineType: "chantier",
      caTce: 350000,
      caPrevision: 250000,
      caContrat: 0,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "09c7e236-9bff-50fe-89b6-149f3c034908",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "f58370c1-c53e-5a8b-b911-ac1c7d1b317e",
      chantierId: "0699760b-a092-530c-8cee-75f4b26d85f9",
      sourceSheet: "2025-26",
      sourceRow: 29,
      rawName: "BRIERE",
      clientKey: "briere",
      clientName: "Briere",
      category: "maison",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 64018.49,
      caContrat: 0,
      plannedTotal: 64018,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "77d036a7-8d3d-5784-9e0f-f64d74906624",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "18f01e4a-f64d-5718-976b-6b98e18eaa79",
      chantierId: "e8dd67f9-97b7-588e-a84c-58c06fe99f4e",
      sourceSheet: "2025-26",
      sourceRow: 30,
      rawName: "DUTRIPON R",
      clientKey: "dutripon-r",
      clientName: "Dutripon R",
      category: "maison",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 120525,
      caContrat: 120525,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "891b53ce-a1ea-5503-8bd1-3ff4de1be3e9",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "8122f8b8-3880-5c8e-ae3e-fc1b06e5e92c",
      chantierId: "098bd892-9c74-53ab-af55-13d12abf57e8",
      sourceSheet: "2025-26",
      sourceRow: 31,
      rawName: "HUCHET",
      clientKey: "huchet",
      clientName: "Huchet",
      category: "maison",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 243414.37,
      caContrat: 0,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "17a58a97-77eb-5681-aea1-9f65b3c32d0a",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "1e73a246-2bed-56db-add3-4407b1dc8955",
      chantierId: "999d7cb5-2602-52ed-a993-cfc0ed88d396",
      sourceSheet: "2025-26",
      sourceRow: 32,
      rawName: "CRUCHON  LEGUEVASQUES",
      clientKey: "cruchon-leguevasques",
      clientName: "Cruchon Leguevasques",
      category: "maison",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 355371.46,
      caContrat: 355371,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "fdd5b12c-a848-508a-bff2-6e2e9e72cbf3",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "9680236d-39ca-5b89-aaf8-fb2713f22a40",
      chantierId: "55034ec3-a2c6-5cec-a6af-640b25584478",
      sourceSheet: "2025-26",
      sourceRow: 33,
      rawName: "CAMPAGNILE",
      clientKey: "campagnile",
      clientName: "Campagnile",
      category: "maison",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 277431,
      caContrat: 0,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "44980082-8158-57c3-8538-6215f144724d",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "5ea660d8-1cb5-5f0b-b6b7-626f93ed32ef",
      chantierId: "2d826e7d-9d79-5d82-9e41-1878475c447f",
      sourceSheet: "2025-26",
      sourceRow: 34,
      rawName: "GAUDIN",
      clientKey: "gaudin",
      clientName: "Gaudin",
      category: "maison",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 269759,
      caContrat: 269759,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "52b066d6-ec08-5f8f-a7fb-9d771aba0731",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "f7f7d35c-b0e7-5e32-a2f0-be432895270b",
      chantierId: "4bd79d6f-1c06-5c89-8c8b-0714148fc086",
      sourceSheet: "2025-26",
      sourceRow: 35,
      rawName: "RAVENEL",
      clientKey: "ravenel",
      clientName: "Ravenel",
      category: "maison",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 149852,
      caContrat: 149852,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "15b7272d-d3fc-5202-865f-6684272a2c1b",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "f4f38322-7ea4-506b-87d5-9af7be4f6442",
      chantierId: "54b4b9ff-459c-52f4-9a8d-9ab7fbc03eac",
      sourceSheet: "2025-26",
      sourceRow: 36,
      rawName: "SEEGERS",
      clientKey: "seegers",
      clientName: "Seegers",
      category: "maison",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 156294,
      caContrat: 0,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "69a2bdc7-ec30-5953-8b13-7a769e0381a9",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "13edb9df-a731-5917-9790-1c32484a0cca",
      chantierId: "3674c50e-b421-5903-80ac-6038abc62718",
      sourceSheet: "2025-26",
      sourceRow: 37,
      rawName: "BRETEAU",
      clientKey: "breteau",
      clientName: "Breteau",
      category: "maison",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 109674.7,
      caContrat: 0,
      plannedTotal: 109674.7,
      realizedTotal: 10964.12,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "84bd13b4-255d-50b7-a1e8-f50676ee785e",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "b473dae8-89f2-5866-a8c1-1971ca159997",
      chantierId: "1a5a85c9-b3e7-591b-a30b-f7c8cfa83047",
      sourceSheet: "2025-26",
      sourceRow: 38,
      rawName: "HERMILLY CARREAU",
      clientKey: "hermilly-carreau",
      clientName: "Hermilly Carreau",
      category: "maison",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 340161.92,
      caContrat: 0,
      plannedTotal: 340161.92,
      realizedTotal: 266422.04,
      invoicedTotal: 217203.48,
      invoiceSentTotal: 217203.48
    },
    {
      id: "b33650f5-d1a2-57c0-aaf6-c2a8d19945a3",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "123da965-2f04-5d2b-a95b-3aa7f3487672",
      chantierId: "f3938f7b-efd3-5a56-85ef-113dc8223dbc",
      sourceSheet: "2025-26",
      sourceRow: 39,
      rawName: "GUILLOT 1",
      clientKey: "guillot",
      clientName: "Guillot 1",
      category: "maison",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 129874,
      caContrat: 0,
      plannedTotal: 129874,
      realizedTotal: 118927.29,
      invoicedTotal: 115974.54,
      invoiceSentTotal: 115974.54
    },
    {
      id: "f6f34a45-38c5-50e9-b989-00054fab11b5",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "123da965-2f04-5d2b-a95b-3aa7f3487672",
      chantierId: "dd7b4e8d-31be-5f0c-a634-e2200132ab7a",
      sourceSheet: "2025-26",
      sourceRow: 40,
      rawName: "GUILLOT 2",
      clientKey: "guillot",
      clientName: "Guillot 2",
      category: "maison",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 129874,
      caContrat: 0,
      plannedTotal: 129874,
      realizedTotal: 120933.44,
      invoicedTotal: 117331.12,
      invoiceSentTotal: 117331.12
    },
    {
      id: "8be93e94-ddbc-5f3c-9ab9-f91f308cd362",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "123da965-2f04-5d2b-a95b-3aa7f3487672",
      chantierId: "13b8d2c1-c758-5ea7-aeb1-7ebc65c24992",
      sourceSheet: "2025-26",
      sourceRow: 41,
      rawName: "GUILLOT 18",
      clientKey: "guillot",
      clientName: "Guillot 18",
      category: "maison",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 129619,
      caContrat: 0,
      plannedTotal: 129619,
      realizedTotal: 114377.41,
      invoicedTotal: 90981.64,
      invoiceSentTotal: 90981.64
    },
    {
      id: "704e0718-548b-50a0-8722-3d5ef07a6cab",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "1265ab84-a735-5ada-871b-21ff600fb178",
      chantierId: "3d96fb2d-0f66-5df8-8f78-6ba3ce3b1064",
      sourceSheet: "2025-26",
      sourceRow: 42,
      rawName: "SIMONET",
      clientKey: "simonet",
      clientName: "Simonet",
      category: "maison",
      lineType: "chantier",
      caTce: 151473.59,
      caPrevision: 134688.76,
      caContrat: 0,
      plannedTotal: 139055.89,
      realizedTotal: 13522.4,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "f6e16bba-cccb-5403-88bb-e420bed4c0db",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "4483f8fd-2f95-5cb1-9bc3-41407eb04270",
      chantierId: "7e0bd6c1-b90c-5dd4-9527-00ad0b1dfc76",
      sourceSheet: "2025-26",
      sourceRow: 43,
      rawName: "MORIVAL (abris cloture)",
      clientKey: "morival",
      clientName: "Morival",
      category: "maison",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 6381.36,
      caContrat: 0,
      plannedTotal: 6381.36,
      realizedTotal: 6381.36,
      invoicedTotal: 6381.36,
      invoiceSentTotal: 6381.36
    },
    {
      id: "2f21a623-4fd2-54b2-9a7e-017c759fd945",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "c9a7c679-f79c-55c8-baf6-92f3f9f40e79",
      chantierId: "991d8a99-9b0a-5150-8ec6-41aadf89e3fe",
      sourceSheet: "2025-26",
      sourceRow: 44,
      rawName: "DUFOUR G",
      clientKey: "dufour-g",
      clientName: "Dufour G",
      category: "maison",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 1502.01,
      caContrat: 0,
      plannedTotal: 1502.01,
      realizedTotal: 1502,
      invoicedTotal: 1502,
      invoiceSentTotal: 1502
    },
    {
      id: "86478adf-8944-5426-8524-e6f28f7e4c4d",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "a01b4901-1d01-5890-ba60-0d9019c1f774",
      chantierId: "8479532a-da1a-5f44-8557-f88b722eda88",
      sourceSheet: "2025-26",
      sourceRow: 46,
      rawName: "BOUTY",
      clientKey: "bouty",
      clientName: "Bouty",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 51000,
      caContrat: 51000,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "c2674c56-d519-541d-a372-decaa5fecb35",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "c7644622-1f80-5d6f-a01b-c71633487b33",
      chantierId: "9ba6d61a-27bc-5690-bc2b-de7b965b647e",
      sourceSheet: "2025-26",
      sourceRow: 47,
      rawName: "SAMSON Agnes",
      clientKey: "samson-agnes",
      clientName: "SAMSON Agnes",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 63000,
      caContrat: 63000,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "9eff2e27-c29d-5dd7-9c10-04494fc04821",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "d12afc56-5fb3-5c87-8ca6-04dbd7a09f4c",
      chantierId: "c6ccd62e-4b4a-51b2-aa5a-c9b9b96ca1ff",
      sourceSheet: "2025-26",
      sourceRow: 48,
      rawName: "BARON",
      clientKey: "baron",
      clientName: "Baron",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 78076.47,
      caContrat: 0,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "cff4ed8d-548f-5874-bf79-38a8af932473",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "d1ae3495-d48e-51a4-ba78-fafec9ea06a2",
      chantierId: "41d466ca-27c1-587a-a9f0-bda969a5f17a",
      sourceSheet: "2025-26",
      sourceRow: 49,
      rawName: "VALSEMEY",
      clientKey: "valsemey",
      clientName: "Valsemey",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 61127.78,
      caContrat: 61127.78,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "037a51f6-7814-5c2f-b462-fa18a876e7c8",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "3adf8744-8ad7-56b4-b791-4f041947b3bf",
      chantierId: "1ae3f728-3b8b-5358-a922-d0e27484a402",
      sourceSheet: "2025-26",
      sourceRow: 50,
      rawName: "DEFRETIN Q",
      clientKey: "defretin-q",
      clientName: "Defretin Q",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 45710.77,
      caContrat: 0,
      plannedTotal: 45710.77,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "244420be-32eb-5c12-a016-23f1b4dd7620",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "63b65a9d-97c0-5b09-b96f-60ddfa5b0691",
      chantierId: "0367c3c6-603d-530c-8e7f-66610f8d304c",
      sourceSheet: "2025-26",
      sourceRow: 51,
      rawName: "MONIN M",
      clientKey: "monin-m",
      clientName: "Monin M",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 92232.69,
      caContrat: 0,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "cafa4b39-e55e-58e0-9edc-015565b7f7a6",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "0bb3e3be-16ce-576a-abdd-586a41e7f13a",
      chantierId: "90b85f3e-8607-51c3-8a1a-cbfdd2028ccf",
      sourceSheet: "2025-26",
      sourceRow: 52,
      rawName: "GUESNON",
      clientKey: "guesnon",
      clientName: "Guesnon",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 32718.45,
      caContrat: 32718,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "3453ed60-7e88-5e5e-b651-82eb9a683a78",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "d800d795-e348-57d9-a184-54f77db2406d",
      chantierId: "66fe3bb3-cf13-5f01-9710-9b1c658fb680",
      sourceSheet: "2025-26",
      sourceRow: 53,
      rawName: "DELASALLE",
      clientKey: "delasalle",
      clientName: "Delasalle",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 142549.41,
      caContrat: 0,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "72ca8f60-5302-599f-85b9-55b6923c195b",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "a55d275e-d567-5b24-b713-f78f21544a34",
      chantierId: "636d4c5c-e7ff-5cd4-bbb0-6f7b86ba53f0",
      sourceSheet: "2025-26",
      sourceRow: 54,
      rawName: "VIRAY (ami larcher)",
      clientKey: "viray",
      clientName: "Viray",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 76547.95,
      caContrat: 0,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "6f2d03e0-1695-5ad6-aff5-4a3855f3d178",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "90a663da-6d23-54ac-abdc-07fd76de61fe",
      chantierId: "074cb0c0-d213-554c-826a-a1e752503219",
      sourceSheet: "2025-26",
      sourceRow: 55,
      rawName: "COISSAC",
      clientKey: "coissac",
      clientName: "Coissac",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 29182.48,
      caContrat: 0,
      plannedTotal: 29182.48,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "d07f8479-6613-5291-8702-52a3ec6eaade",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "1418f0a0-f7a8-5c87-84a6-6d635ff36929",
      chantierId: "48fb45fa-76a0-5dcb-bc38-728749e814ee",
      sourceSheet: "2025-26",
      sourceRow: 56,
      rawName: "GUAY LEMAZURIER",
      clientKey: "guay-lemazurier",
      clientName: "Guay Lemazurier",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 57581.9,
      caContrat: 0,
      plannedTotal: 57581.9,
      realizedTotal: 51232.75,
      invoicedTotal: 37510.45,
      invoiceSentTotal: 37510.45
    },
    {
      id: "cdfdc439-39ec-50a4-bc93-c5debd397aca",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "25d5c13a-fcb3-53cf-8ec0-4d33edaa13aa",
      chantierId: "c38e534a-8dfd-51aa-bc39-0306f7bacea9",
      sourceSheet: "2025-26",
      sourceRow: 57,
      rawName: "GERVAIS",
      clientKey: "gervais",
      clientName: "Gervais",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 129236,
      caContrat: 0,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "dda61403-1e34-528c-b8cc-21c77618efcc",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "f8b8960f-a4a1-58bf-93e9-26deaf9f5216",
      chantierId: "6e021ef7-3bc0-59a6-8ae4-3f8dee504da6",
      sourceSheet: "2025-26",
      sourceRow: 58,
      rawName: "GESLAIN",
      clientKey: "geslain",
      clientName: "Geslain",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 66982.32,
      caContrat: 0,
      plannedTotal: 66982.32,
      realizedTotal: 33766.44,
      invoicedTotal: 33766.44,
      invoiceSentTotal: 33766.44
    },
    {
      id: "0eb339da-7e9b-5b34-82a3-0a55259fdd39",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "8d33de21-fda7-59e1-86ed-0f91679b0dce",
      chantierId: "841dcaaf-75d2-5c63-a07a-9abe2b6787d2",
      sourceSheet: "2025-26",
      sourceRow: 59,
      rawName: "DECLERCK NORGOLL",
      clientKey: "declerck-norgoll",
      clientName: "Declerck Norgoll",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 37831.45,
      caContrat: 0,
      plannedTotal: 37831.45,
      realizedTotal: 29407.4,
      invoicedTotal: 9248.54,
      invoiceSentTotal: 9248.54
    },
    {
      id: "f29ebed8-721a-5650-a151-4bd595ab1878",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "2e7bdc80-ef0f-56bf-8a77-eff64d2b3622",
      chantierId: "533719ca-7143-57a5-9407-f87527e87651",
      sourceSheet: "2025-26",
      sourceRow: 60,
      rawName: "RAOULT",
      clientKey: "raoult",
      clientName: "Raoult",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 196666,
      caContrat: 0,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "bf520ceb-ada9-5fd3-86ea-2ae9d7f5c1c1",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "5da63188-cf5c-501c-8fd3-24bcad2c8980",
      chantierId: "1e15207c-ee36-5ac3-ace6-8fe0707339e8",
      sourceSheet: "2025-26",
      sourceRow: 61,
      rawName: "BEAUSSIER",
      clientKey: "beaussier",
      clientName: "Beaussier",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 88843.61,
      caContrat: 0,
      plannedTotal: 94350.59,
      realizedTotal: 85272.65,
      invoicedTotal: 70010.49,
      invoiceSentTotal: 70010.49
    },
    {
      id: "1e08d4c9-d447-597f-9036-8844cf151f4a",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "4c95b45b-c861-59db-9bc0-183800c1023c",
      chantierId: "95f6f0af-3c9a-56a0-90bf-06740da740b8",
      sourceSheet: "2025-26",
      sourceRow: 62,
      rawName: "CHAPRON",
      clientKey: "chapron",
      clientName: "Chapron",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 20997.32,
      caContrat: 0,
      plannedTotal: 20997.32,
      realizedTotal: 20596.49,
      invoicedTotal: 14494.93,
      invoiceSentTotal: 14494.93
    },
    {
      id: "df6e5d5f-5611-5dd9-a9cf-0c871d319b20",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "dcbb1bce-d6d7-539c-b6c5-2936b5a3d01e",
      chantierId: "f4cd571d-c96d-5bbd-bceb-4b78bec37d36",
      sourceSheet: "2025-26",
      sourceRow: 63,
      rawName: "CHAUVEAU",
      clientKey: "chauveau",
      clientName: "Chauveau",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 86969,
      caContrat: 0,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "206941be-3676-54f4-83de-7db534c73bc5",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "696d8026-91d1-5e44-a57d-2701eed9429f",
      chantierId: "bc98281e-0969-5387-aa7d-ebb990ad6891",
      sourceSheet: "2025-26",
      sourceRow: 64,
      rawName: "DENOS KOPP",
      clientKey: "denos-kopp",
      clientName: "Denos Kopp",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 52395,
      caContrat: 0,
      plannedTotal: 52395,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "fec1c86a-2c65-5405-a128-c50b4276d3b8",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "5ea660d8-1cb5-5f0b-b6b7-626f93ed32ef",
      chantierId: "2fa53521-7f79-5a08-9ac7-839784e879a8",
      sourceSheet: "2025-26",
      sourceRow: 65,
      rawName: "GAUDIN",
      clientKey: "gaudin",
      clientName: "Gaudin",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 71806.76,
      caContrat: 71806.76,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "daac8201-c318-5aa4-aaa0-234d1b6e919d",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "9b7ee751-e846-5f2c-9f2c-63daab5e4011",
      chantierId: "a17c3ea0-0ae9-5a52-8f68-cfc5ff9b990e",
      sourceSheet: "2025-26",
      sourceRow: 66,
      rawName: "GLOWACKI",
      clientKey: "glowacki",
      clientName: "Glowacki",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 141779,
      caContrat: 0,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "0bff243d-6c83-5883-984b-45cfbeec0a80",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "7d66bd09-ed1d-5d26-bd81-fbdf64f036ca",
      chantierId: "6e7dd610-943e-5d45-97a6-ba06167b56d3",
      sourceSheet: "2025-26",
      sourceRow: 67,
      rawName: "LAUVERGNE",
      clientKey: "lauvergne",
      clientName: "Lauvergne",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 67113.22,
      caContrat: 67113.22,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "75898e88-e2bd-5984-9c8b-f89d32b46465",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "a321f589-097f-5f94-b7cf-7a20df4a3003",
      chantierId: "8b79afd5-48c6-5ff2-bfaf-3c270d1458e8",
      sourceSheet: "2025-26",
      sourceRow: 68,
      rawName: "GUILLEMOT",
      clientKey: "guillemot",
      clientName: "Guillemot",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 80923.61,
      caContrat: 0,
      plannedTotal: 80923.61,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "93447d41-3cf5-5aa6-894b-62563bcb0b24",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "c85b4884-b586-5109-ad57-d71d57b1ec87",
      chantierId: "f02b8626-e266-5a4b-907d-1437b1467aca",
      sourceSheet: "2025-26",
      sourceRow: 69,
      rawName: "KUFEL",
      clientKey: "kufel",
      clientName: "Kufel",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 76836,
      caContrat: 0,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "e0e60487-7b0f-5ac7-8161-31b527e3765d",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "b5cd01d4-51d4-5a44-a701-483aaf13c15b",
      chantierId: "c63cc02e-dcc5-5b98-a335-1551024eccf8",
      sourceSheet: "2025-26",
      sourceRow: 70,
      rawName: "LAURENT",
      clientKey: "laurent",
      clientName: "Laurent",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 80706.6,
      caContrat: 0,
      plannedTotal: 80706.6,
      realizedTotal: 9300.34,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "2ab1b53d-ad4e-58dc-86b3-f59e6e77d00b",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "038b9de4-ecde-562a-8649-f1828f7910d1",
      chantierId: "1c9c5c90-c8e2-5b09-81f3-f129040c15cc",
      sourceSheet: "2025-26",
      sourceRow: 71,
      rawName: "LECLERC DUMARAIS",
      clientKey: "leclerc-dumarais",
      clientName: "Leclerc Dumarais",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 160086,
      caContrat: 0,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "2e084703-553e-5db6-8039-1e995b0c50a5",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "10e5643d-3601-5f58-8e46-50aa4fd44c6d",
      chantierId: "70aa9376-b294-575a-8396-d6811a4f4cf8",
      sourceSheet: "2025-26",
      sourceRow: 72,
      rawName: "LEMOIGNE",
      clientKey: "lemoigne",
      clientName: "Lemoigne",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 19248,
      caContrat: 0,
      plannedTotal: 19248,
      realizedTotal: 19248.07,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "7e2cc563-0559-5417-8d24-fc2b2a9e5c72",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "ece839d4-f69d-5867-ac20-a2a35d41c6ac",
      chantierId: "8e8432ff-0010-5f69-846f-cccf377f67d5",
      sourceSheet: "2025-26",
      sourceRow: 73,
      rawName: "LEPLUS",
      clientKey: "leplus",
      clientName: "Leplus",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 30937,
      caContrat: 0,
      plannedTotal: 30937,
      realizedTotal: 28898.44,
      invoicedTotal: 28548.44,
      invoiceSentTotal: 28548.44
    },
    {
      id: "91c391c2-e448-5522-9691-cf8233c41d8c",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "ca446c99-029c-5cbb-8e50-632b5dc09251",
      chantierId: "48cbfa72-9c8a-525e-97a7-812d8e07f31e",
      sourceSheet: "2025-26",
      sourceRow: 74,
      rawName: "LEPRETE",
      clientKey: "leprete",
      clientName: "Leprete",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 98822,
      caContrat: 0,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "e877cd51-f15b-5d7d-b569-4246c22b6936",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "cb2905dd-adb1-5f50-a8e6-0817f32e4e71",
      chantierId: "34baeb6b-b1b5-5e7d-9483-d8b905b92336",
      sourceSheet: "2025-26",
      sourceRow: 75,
      rawName: "LEROYER",
      clientKey: "leroyer",
      clientName: "Leroyer",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 76200,
      caContrat: 76200,
      plannedTotal: 0,
      realizedTotal: 0,
      invoicedTotal: 0,
      invoiceSentTotal: 0
    },
    {
      id: "5f80149c-c3ed-5e0d-a145-f2d99525478b",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "45405283-2b9d-5fa2-892a-ad50488a4a3c",
      chantierId: "2263e71b-3373-5bc9-9f35-a29914904f76",
      sourceSheet: "2025-26",
      sourceRow: 76,
      rawName: "OLIVIER",
      clientKey: "olivier",
      clientName: "Olivier",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 5468,
      caContrat: 0,
      plannedTotal: 5468,
      realizedTotal: 5468,
      invoicedTotal: 5468,
      invoiceSentTotal: 5468
    },
    {
      id: "572e1774-ecc8-5af9-9afb-db822e3afca3",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "d6d2d11f-63a4-554e-b8e3-816551c4a0ee",
      chantierId: "addab9a3-92b1-544e-82cd-53d6f2cde96f",
      sourceSheet: "2025-26",
      sourceRow: 77,
      rawName: "URBAIN",
      clientKey: "urbain",
      clientName: "Urbain",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 6229.55,
      caContrat: 0,
      plannedTotal: 7237.78,
      realizedTotal: 7237.35,
      invoicedTotal: 7237.35,
      invoiceSentTotal: 7237.35
    },
    {
      id: "d7ac94fe-2598-5a11-9137-d1937dace6c7",
      exerciseId: "c68a6b71-5557-5840-9cbf-0944df329ae0",
      clientId: "5188b7be-98a3-5e14-afd7-8249e8d28068",
      chantierId: "1070c9af-0c7e-5d03-ac1e-5cc7378323bb",
      sourceSheet: "2025-26",
      sourceRow: 78,
      rawName: "SIGNORET",
      clientKey: "signoret",
      clientName: "Signoret",
      category: "extension",
      lineType: "chantier",
      caTce: 0,
      caPrevision: 26545.41,
      caContrat: 0,
      plannedTotal: 26545.41,
      realizedTotal: 26545.42,
      invoicedTotal: 26545.42,
      invoiceSentTotal: 26545.42
    }
  ])
}
